### ISSUE TITLE
Getting RServe error while conencting to TabPy

### ISSUE THREAD

**Issue by Mdamir11** [tableau/TabPy#10]
Hi All,

I am quite new to Tableau. Wanted to connect Tableau to Python. As per the instruction mentioned, I installed TabPy server and started it. But while Testing the connection using Tableau ( Help --> Manage External Service Connection : Sever as 127.0.0.1 and Port as 9004). I am unable to Test connection. It gives me below error:
**RServe: Rserve is busy or not responding. Failed to create socket to Rserve. ExtSvc: Server returned nothing (no headers, no data)**

I was Earlier using Rserve to connect Tableau to R to access Python code using rPython. 

Not sure, where I am doing wrong. Any help will be appreciated. Thanks.

Regards
Amir

**Comment by BBeran** [comment]
Hi Amir,
Can you check whether your operating system is blocking the port? Also can you also try going to localhost:9004 in your browser and see if you're seeing a Tableau logo?

Thank you,

Bora

**Comment by Mdamir11** [comment]
Hi Bora,

Thanks for your quick reply. Yes I did check on my PC using netstat -na command and it shows results as below: 
Proto   Local Address      Foreign Address         State
TCP    [::]:9004                  [::]:0                            LISTENING

So I am assuming its opened. Also I tried the link : http://localhost:9004/ . Is showing a big Tableau logo.

Regards
Amir

**Comment by BBeran** [comment]
Hi Amir,
Thanks for clarifying. Then my next guess is that it could be a version issue. What version of Tableau are you using? TabPy requires Tableau 10.1.

Thanks,

Bora

**Comment by Mdamir11** [comment]
Hi Bora,

Yes I upgraded to 10.1.1 for connecting to TabPy.

Regards
Amir

**Comment by BBeran** [comment]
Hi Amir,
Were you using Rserve at the same port earlier by any chance and had not tried test connection after you swapped to using Python on the same port? 

Since you mentioned "Earlier using Rserve to connect Tableau to R to access Python code using rPython."

Once you do the configuration and test connection succeeds, Tableau decides it is R or Python. It doesn't check on every single connection for performance reasons.

So if you want to use Python with the same IP address and port after using it for Python, you can open external services and hit test connection option again, which will check if it is R or Python again and figure out that now it is Python running on the same port.

Thanks,

Bora

**Comment by Mdamir11** [comment]
Hi Bora,

I was using Rserve at port 6311 and that is still working fine. For connecting to TabPy, I used port 9004 as it was mentioned in documentation.  I did test the connection as well again today but I am still getting the same error message. Surprisingly my TabPy server was not running today and it showed a different error ( Connection Refused) but once I initialized it, I started getting same Rserve error.

Regards
Amir

**Comment by ghousepeer** [comment]
Hi Amir,

Run Command prompt as Administrator and go to the tabpy folder in which tabpy_server path.
for example my tabpy_server path is "C:\Users\Administrator\Desktop\Tableau\TabPy-master\tabpy-server\tabpy_server"
type "startup.bat" command

Gegards
Ghouse

**Comment by Mdamir11** [comment]
Hi Ghouse,

Thanks for your reply. 
I already have my TabPy server running. However location is bit different

C:\Users\<user name>\Anaconda\envs\Tableau-Python-Server\Lib\site-packages\tabpy_server

Hope that's correct!!

Regards
Amir

**Comment by BBeran** [comment]
Hi Amir,
I meant whether you hit [Test Connection] button in the Manage External Services dialog. 

After changing from R to Python, you may want to hit that button for Tableau to discover what kind of service it is connecting to. If you were connected to R then opened the dialog and changed the port number and hit OK, it may still think that it is R you're trying to talk to. Pushing [Test Connection] will make sure that it discovers it is a Python endpoint.

Thanks,

Bora
