### ISSUE TITLE
Running in windows produces "PermissionError: [WinError 5] Access is denied: '/tmp'"

### ISSUE THREAD

**Issue by graham-macleod** [tableau/TabPy#101]
Due to the config.py specifying a path in UNIX format thi causes a failure when running startup.bat.

The error received is 

> PermissionError: [WinError 5] Access is denied: '/tmp'

And the offending line config.py seems to be 

`TABPY_QUERY_OBJECT_PATH = '/tmp/query_objects'`

Changing this to 

`TABPY_QUERY_OBJECT_PATH = 'tmp\query_objects'`

seemed to stop the error occurring.

Windows 7 64 bit. Using pyCharm IDE with virtual environments. Python 3.6.4. tabpy version 0.2.

**Comment by nmannheimer** [comment]
Thanks for the information @graham-macleod !

**Comment by nmannheimer** [comment]
This change has been added to our backlog for TabPy and is a known issue. As such I'm going to close this issue.
