### ISSUE TITLE
script_real returning wrong value - possibly a TabPy issue

### ISSUE THREAD

**Issue by marcusjc** [tableau/TabPy#102]
This script, where I've hardcoded the value from my Tableau calculations:

`SCRIPT_REAL(
"from scipy.stats import ttest_ind_from_stats
t = ttest_ind_from_stats(17.697,12.4123,1118871,17.717,8.178,551339,False)
p = t[1].tolist()
return p",
MAX([Avg Order Value - Control]),
MAX([Order Value - SD - Control]),
MAX([Orders - Control]),
MAX([Avg Order Value]),
MAX([Order Value - SD]),
MAX([Orders])
)
`
GIves a correct value for p of 0.214

This script:
`SCRIPT_REAL(
"from scipy.stats import ttest_ind_from_stats
t = ttest_ind_from_stats(_arg1[0],_arg2[0],_arg3[0],_arg4[0],_arg5[0],_arg6[0],False)
p = t[1].tolist()
return p",
MAX([Avg Order Value - Control]),
MAX([Order Value - SD - Control]),
MAX([Orders - Control]),
MAX([Avg Order Value]),
MAX([Order Value - SD]),
MAX([Orders])
)`

Gives an incorrect value for p of 0.197.

To understand what the values are for each argument, this script returns a string of each of the arguments to expose each individual one:
`SCRIPT_STR(
"mean1 = _arg1
std1 = _arg2
nobs1 = _arg3
mean2 = _arg4
std2 = _arg5
nobs2 = _arg6
return str(mean1[0]) + ' - ' + str(std1[0]) + ' - ' + str(nobs1[0]) + ' - ' + str(mean2[0]) + ' - ' + str(std2[0]) + ' - ' + str(nobs2[0])",
MAX([Avg Order Value - Control]),
MAX([Order Value - SD - Control]),
MAX([Orders - Control]),
MAX([Avg Order Value]),
MAX([Order Value - SD]),
MAX([Orders])
)`

It shows that the values being passed into the arguments are the same as the hardcoded version. 

How is it possible that I get different answers when the same values appear to be passed into the script?

Is this a bug in TabPy somewhere? 

Or is it something else?

**Comment by johng42** [comment]
Can you post  a workbook (*.twbx) with enough data to demonstrate the error?  I tried to repro but could not with the data I was using.

**Comment by nmannheimer** [comment]
Just following up on this, @marcusjc if you're able to send a .twbx workbook we can take a look.
