### ISSUE TITLE
Tabpy not working in 2018.1

### ISSUE THREAD

**Issue by ltwedgar** [tableau/TabPy#106]
Hi,

We were using Tabpy as the external service on Tableau Server in Linux environment. However, **after upgrading Tableau Server to 2018.1, the functionality is not working**. The view keeps loading for a while then shows the error message in the following screenshot.

![screen shot 2018-06-06 at 4 44 00 pm](https://user-images.githubusercontent.com/32426641/41027152-dc40249a-69a8-11e8-8402-672361b5b9df.png)

It worked previously before the upgrading to 2018.1. We can install tabpy-server with no problem. The server is also **listening to the port normally**. Please see the output of netstat -tanp for your reference

![screen shot 2018-06-06 at 4 49 43 pm](https://user-images.githubusercontent.com/32426641/41027614-0bb72b8c-69aa-11e8-81b5-321c2fdc6883.png)

We tried **Rserver and it work well**. May I ask if there is any changes need to made for version 2018.1?

**Comment by johng42** [comment]
We are investigating.

**Comment by johng42** [comment]
And can you check the port #?  Did you change the port to 6311?  That is the default port for R and would explain why R works.  Tabpy uses port 9004 be default.

**Comment by PoradaKev** [comment]
HI! 
We faced the same issue as ltwedgar today. Previously I didn't use TabPy integration. Now we have Tableau Desktop and Server 2018.1. TabPy Server is listening to 9004 port. 

Everything works perfect on Dekstop. However, when the dashboard is published to server it loads for about 15-20 minutes and sends this error  
 
![2018-06-07_1828](https://user-images.githubusercontent.com/35397315/41109899-c2d414fc-6a80-11e8-87d9-f120418411a4.png)

After clicking yes I received this error. 
![2018-06-07_1826](https://user-images.githubusercontent.com/35397315/41109928-d4f6fa96-6a80-11e8-9dd7-ff9f4e9942e9.png)
 
Tried to do this a few times with two different dashboards (one with big arima model, second one with simple np.corrcoef func) and had the same error messages all the time.

Does anyone have any ideas how to fix this?

**Comment by johng42** [comment]
Do you have server logs you can share?

**Comment by nmannheimer** [comment]
This is now a known issue that we are in the process of addressing.

**Comment by ltwedgar** [comment]
Hi johng42 and nmannheimer,

We upgraded the Tableau Server from version 10.5.2 to 2018.1. As I said, I could make Tabpy work before the upgrade. So I am confident that we configure all the things correctly including the port.

We set the port correctly as 6311, in both the argument after the startup.sh and tsm. Please see the following screenshots for your reference.
<img width="343" alt="external service connection in desktop" src="https://user-images.githubusercontent.com/32426641/41145455-b7cb77d2-6b32-11e8-93db-800b9be20dfb.png">
![tsm external service configuration](https://user-images.githubusercontent.com/32426641/41145456-b7fa1cd6-6b32-11e8-93f9-b2afbfb09e5f.png)
![command with startup](https://user-images.githubusercontent.com/32426641/41145457-b8289a52-6b32-11e8-9ec1-d5e962f268c6.png)

I also searched the server logs by the Session ID shown in the error message box. In particular, I read a couple of line showing "Non-guest user session found" in vizqlserver_node. Please see the attached logs for your reference.

[nativeapi_vizqlserver_1-3_2018_06_08_00_00_00.txt (log with C02159C792F443EA9B8279DE5A1A2213) .txt](https://github.com/tableau/TabPy/files/2083427/nativeapi_vizqlserver_1-3_2018_06_08_00_00_00.txt.log.with.C02159C792F443EA9B8279DE5A1A2213.txt)
[vizqlserver_node1-1.log (log with C02159C792F443EA9B8279DE5A1A2213)  .log](https://github.com/tableau/TabPy/files/2083430/vizqlserver_node1-1.log.log.with.C02159C792F443EA9B8279DE5A1A2213.log)

Please let me know if you want any more information. I can help on that.

**Comment by PoradaKev** [comment]
johng42, could you clarify please, what logs exactly do you need?
I can send them as well

**Comment by johng42** [comment]
We have a set another user uploaded here: https://github.com/tableau/TabPy/issues/106#issuecomment-395680272

**Comment by PoradaKev** [comment]
johng42, hello! 
Don't you have any estimates when the issue will be fixed?

**Comment by johng42** [comment]
We are still actively investigating and unfortunately do not have an ETA.  Been busy investigating and I apologize for not updating this sooner.

**Comment by nmannheimer** [comment]
Hi All,

So we now have a workaround for the issue. An error is occurring in the default timeout value for communications with TabPy. By manually setting this value in the server configuration using Tabadmin we can allow for connections to operate normally. The command to set is <vizqlserver.extsvc.connect_timeout_ms> and the default value to set it to is 1000. If setting this value to 1000 ms causes a timeout error, experiment with extending the timeout time. For more documentation on setting values with Tabadmin refer here:

https://onlinehelp.tableau.com/current/server/en-us/reconfig_tabadmin.htm

The exact series of commands in the command line should look like:

cd "C:\Program Files\Tableau\Tableau Server\2018.1\bin"

tabadmin stop
tabadmin set vizqlserver.extsvc.connect_timeout_ms 1000
tabadmin config
tabadmin start

**Comment by ltwedgar** [comment]
Thanks a lot. This works!
