### ISSUE TITLE
Using Pipenv Instead of Conda / Pip

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#108]
In reading through the installation instructions I get the impression that this project is using anaconda simply to generate virtual environments, and not necessarily for its package management features as well, as it instructs users to still use pip for the actual installation.

As an alternate would you consider using Pipenv? I saw a talk on this at PyCon this year and it seems to have a bright future in the world of Python (it was made by the same guy that made the requests library):

https://docs.pipenv.org

The advantages of Pipenv here will be that:
 - Installation instructions will be simplified
 - You can distribute a Pipfile as part of the package to manage dependencies
 - It is arguably easier to use for activating / deactivating virtual environments

Happy to give it a go if you think its worthwhile

**Comment by nmannheimer** [comment]
Hi @WillAyd,

If you're interested in exploring this we'd certainly be interested in seeing it set up!

Creating a containerized setup for TabPy is something we are considering, but it isn't on our immediate roadmap.

**Comment by WillAyd** [comment]
Closed by #110
