### ISSUE TITLE
.zip file doesn't contain the anaconda.exe

### ISSUE THREAD

**Issue by Brian3000** [tableau/TabPy#112]
Hi all,

I made my first attempt to install TabPy today and after running setup.bat I'm running into an error tied to no anaconda executable being present. Is there a different .zip package that contains everything I need? I just went here - https://github.com/tableau/TabPy and then clicked the clone or download button. 

Thanks for any help.

![2018-07-05_13-18-37](https://user-images.githubusercontent.com/40867526/42337859-83d1f87a-8077-11e8-991b-1c85d7d2dac4.jpg)

**Comment by WillAyd** [comment]
Well you can see from the error message that the call to download anaconda is getting blocked by your proxy, which is also going to cause issues down the road when installing from pip.

I'm not a Windows person and I can't really advise how to solve, but you may find luck with some of the proxy settings called out on this SO article before installing:

https://stackoverflow.com/questions/14149422/using-pip-behind-a-proxy

**Comment by Brian3000** [comment]
Thanks William!
