### ISSUE TITLE
Execute 3.x code

### ISSUE THREAD

**Issue by sajozsattila** [tableau/TabPy#113]
Hello,

I try to run 3.x client code on TabPy. But how it is looking for me, it is running only on 2.7 (ex: the setup.sh 206 line: hardcoded the 2.7.)
Am I right?  
   If yes is there any plan to port to 3.x?
   If no, what is the biggest problem which prevents this?

**Comment by 0golovatyi** [comment]
sajozsattila,

As described on https://github.com/tableau/TabPy/blob/master/server.md page setup script downloads and installs Anaconda unless it already exists in the current folder. The script downloads Anaconda 2.3 which uses python 2.7.

You may need to modify the script to install and/or use different Python version as explained on the same page.

**Comment by nmannheimer** [comment]
Hello @sajozsattila,

So just to elaborate a little bit further, the default script will install Anaconda with Python 2.7 if you don't modify it. But if you do modify it, or install TabPy via pip, 3.x Python is supported.
