### ISSUE TITLE
 TabPy/tabpy-client/setup.py

### ISSUE THREAD

**Issue by sajozsattila** [tableau/TabPy#114]
I think need the 'future' in the request also ( I have just installed from pip in a plain system))

**Comment by sajozsattila** [comment]
--- /tmp/setup.py	2018-07-10 10:10:03.831580910 +0000
+++ setup.py	2018-07-10 10:09:17.355920868 +0000
@@ -21,6 +21,7 @@
     packages=['tabpy_client'],
     license='MIT',
     install_requires=[
+        'future',
         'cloudpickle',
         'decorator',
         'python-dateutil',

**Comment by nmannheimer** [comment]
@sajozsattila If you are still experiencing this issue, please try the latest version of TabPy which no longer requires an install from pip!
