### ISSUE TITLE
tabpe_client rest.py

### ISSUE THREAD

**Issue by sajozsattila** [tableau/TabPy#116]
there is an  ` import common.tabpy_logging` , which is I think should be tabpy_server.common as if we install tapy_client from pip this import fails.

Patch: 

```
--- /mnt/rest.py	2018-07-10 10:06:56.863925625 +0000
+++ rest.py	2018-07-10 10:07:39.837535929 +0000
@@ -7,7 +7,7 @@
 
 import json as json
 
-from common.tabpy_logging import (
+from tabpy_server.common.tabpy_logging import (
     PYLogging,
     log_error,
     log_info,

```

**Comment by WillAyd** [comment]
Yea the name spacing here needs a little updating. I believe I tackled this as part of #124

**Comment by nmannheimer** [comment]
This issue should be fixed with the latest TabPy releases.
