### ISSUE TITLE
Error while Connecting to Python Code

### ISSUE THREAD

**Issue by PraveenDNA** [tableau/TabPy#119]
An error occurred while communicating with the Predictive Service.
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

**Comment by nmannheimer** [comment]
Hi Praveen, 

Can you tell me a little bit more about how your seeing the error? Is this in Python code outside of Tableau or are you seeing this result inside of Tableau from a SCRIPT_* function? 

The immediate things to check would be to make sure TabPy is running and on the port you expect and that you have the name of the deployed model/function spelled exactly correctly in the code you are using to call it.
