### ISSUE TITLE
Keras Support

### ISSUE THREAD

**Issue by zac-moran** [tableau/TabPy#120]
I have been trying to train a model (with Keras) then use it in a function that i have deployed to TabPy server. I don't believe that TabPy supports Keras? 

Keras docs says 

> _"It is not recommended to use pickle or cPickle to save a Keras model."

Does this mean it is not possible to load Keras models in a TabPy function? 

My function is below,

```
def predict(a,b,c,d,e,f,g,h,i,j,k):

	model = load_model('ChurnModel.h5')

	A = [a,b,c,d,e,f,g,h,i,j,k]

	A = np.asarray(A)

	A = A.swapaxes(0,1)

	A = sc.transform(A)

	prediction = model.predict(A)

	return prediction.tolist()
```

**Comment by nmannheimer** [comment]
Hey @ai-high,

Officially, due to TabPy's use of pickle to deploy models, the deployment of a Keras model won't be supported. I've also experimented with this and was not able to get it to work correctly.

Were you seeing an error when you tried to deploy the function in your code?

**Comment by ai-high** [comment]
Yes, I believe it was a pickle error, But i cant remember exactly. I have managed to get it working with scikit-learn model.

Found this blog post that may be able to pickle Keras models: http://zachmoshe.com/2017/04/03/pickling-keras-models.html

Going to check that out now.

**Comment by ngocbaosp** [comment]
Hey @zac-moran 
Did you have a solution for this issue ? If so, please share it to us.
Please help to check my workaround solution
https://github.com/ngocbaosp/TabPyAndKeras
