### ISSUE TITLE
"no such file or directory"

### ISSUE THREAD

**Issue by Brian3000** [tableau/TabPy#122]
we were able to install Python on a server but then during the pip install -r requirements.txt step we got hit with a “could not open requirements.txt Error No 2 no such file or directory” which stumped us.

**Comment by WillAyd** [comment]
Perhaps I'm overlooking it but I don't see a `requirements.txt` file anywhere in the source - what installation instructions are you following exactly?

FWIW I just put in a PR to simplify the install instructions in #110 which may be easier to follow

**Comment by Brian3000** [comment]
After following your instructions, we got stuck at another spot...
Does the machine where TabPy is being installed need access to the index URL and the trusted host URL mentioned on the pip config file? 
For example -
index-url=https://xxxxxx
trusted-host=xxxxx

The install is not working and both the index and trusted host URLs can't be reached from the machine we are trying to install on...is this the cause?

**Comment by WillAyd** [comment]
I'm not entirely sure I follow your issue but generally you need outbound access to PyPi to install packages via pip and/or pipenv
