### ISSUE TITLE
Remove Logging Module (?)

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#126]
It's not entirely clear what the purpose of the logging module is in `tabpy-server`. I assume it's something that will eventually be integrated more tightly with Tableau's logging, but at the moment it's not quite there.

Would be preferable to create just one (or more) application wide logging mechanisms and import those when the server starts. The way the code base directly instantiates and manages imports now is needlessly complex.

https://docs.python.org/3/howto/logging-cookbook.html

**Comment by slewt** [comment]
second that.
