### ISSUE TITLE
Missing setup.bat files?

### ISSUE THREAD

**Issue by daudk** [tableau/TabPy#127]
The repo does not seem to contain setup files? And the pip install seems to install but I'm not sure how to launch the tabpy local server?

**Comment by WillAyd** [comment]
There's a startup.bat file in the `tabpy_server` directory. That said, I recently rewrote installation instructions which you might want to take a look at to see if it makes configuration any easier - #110

**Comment by nmannheimer** [comment]
Hi @daudk , the setup.py file has been re-added to the repo. We are also working on an improved install experience that should work more smoothly for users in all environments. Look for updates shortly!

**Comment by amruutharao** [comment]
@nmannheimer The setup.py file is not helping to install the tabpy. there is no batch files also available in the repository.

**Comment by sahil0094** [comment]
> @amruutharao with the latest updates to TabPy, the install should now be performed per the instructions on the readme using startup.cmd (or startup.sh for mac). The install of the server and startup have been combined into a single script that checks requirements, installs any missing packages if needed, then runs the server.
> 
> https://github.com/tableau/TabPy/blob/master/docs/server-startup.md

The link is missing @nmannheimer
