### ISSUE TITLE
Published workbook hangs on loading screen

### ISSUE THREAD

**Issue by afreeland** [tableau/TabPy#128]
I have a workbook utilizing TabPy for sentiment analysis which runs fine in Tableau Desktop but when publishing to Tableau Server it fails to load in.  It just shows the loading spinner and eventually ends the session after a LONGGG timeout.

We are experimenting with the new 2018.2 release, which replaces `tabadmin` with `tsm` so not sure about TabPy support in the newest version.

Tableau Desktop:
**10.2.1 64-bit**

Tableau Server:
**Tableau Server Version: 2018.2.0 (20182.18.0627.2230) 64-bit Windows**
  
Tried running the following commands on our Tableau server:
```
tsm configuration set -k vizqlserver.extsvc.host -v k8s
tsm configuration set -k vizqlserver.extsvc.port -v 9004
tsm pending-changes apply
```
Tried loading the workbook and still received the never ending loading screen. 

So kept on looking up other possibilities when we discovered:
```
tsm configuration set -k vizqlserver.allow_insecure_scripts -v true
tsm configuration set -k vizqlserver.script.disabled -v false
```
Still no luck

Are there any other configurations that need to be checked?  I see that there is also a `vizqlserver.esxtsvc.connect_timeout_ms` but our response time is pretty fast and dont believe that is the issue.

We have been using the [External Service Help](https://onlinehelp.tableau.com/current/pro/desktop/en-us/r_connection_manage.html) but not having success yet.

Any ideas would be greatly appreciated.

**Comment by GitAMoveOn** [comment]
For us, explicitly setting the timeout as [detailed in 106](https://github.com/tableau/TabPy/issues/106) was what worked for us. 

I think it would be (not 100% sure, I don't do the server admin side):
`tsm configuration set -k vizqlserver.esxtsvc.connect_timeout_ms -v 1000`

Prior to that, also had the never-ending loading spinner.

We are in a similar setup, Desktop at 10.5, Server at 2018.2.0

**Comment by afreeland** [comment]
@GitAMoveOn @nmannheimer will hopefully get a chance to try and verify for our setup too, will post as soon as I do.  Tableau is super slow restarting so will have to do after hours.  Was hoping to look at the Linux distro and see if it could be put in Kubernetes to allow for on the fly changes smoothly.

**Comment by kavyapc01** [comment]
https://community.tableau.com/thread/273385[](url)
