### ISSUE TITLE
Not able to see log on windows command

### ISSUE THREAD

**Issue by parameshjoy** [tableau/TabPy#129]
When i install Tabpy with recommendation on windows server am unable to see the logs in command prompt.

![image](https://user-images.githubusercontent.com/42235378/44267266-3168d180-a24b-11e8-8ae7-fb9fbda527d9.png)

But if i install the same version on my laptop windows 7 am able to see the logs.

![image](https://user-images.githubusercontent.com/42235378/44267325-607f4300-a24b-11e8-8004-530fb1ed23ac.png)

**Comment by parameshjoy** [comment]
Thanks for update.

Can you let us know how to get the logs from the latest release.

**Comment by slewt** [comment]
I'm not currently running the latest, but looking at source code, it should be logging to your <temp dir>/tabpy_log.log by default.

You can find your temp dir by `python -c "import tempfile;print(tempfile.gettempdir())"`

If you have made a tabpy_server/common/config.py file (not the template file), you may want to look at the TABPY_LOG_LEVEL entry and make sure that it is low enough to capture the logs (for example if you set it to ERROR, then the INFO lines you see won't be shown).

**Comment by parameshjoy** [comment]
Thanks Slewt.

I was able to find logs in Temp directory.

For latest i will look at the tabpy_log_level entry.

**Comment by parameshjoy** [comment]
Hi Slewt,

Installed latest version of tabpy and configure tabpy_log_level in config.py.
Am able to locate the tabpy.log file in my local temp directory.
Thanks for your help.
