### ISSUE TITLE
The endpoint you're trying to query did not respond. 

### ISSUE THREAD

**Issue by kitakoj18** [tableau/TabPy#130]
I've deployed a function to the server and am trying to pass in variables from Tableau to make new predictions. However, I'm getting an error that the endpoint is not responding. In the command line, I'm getting the error below. I have 4 variables that my model takes in as inputs and I have 4 arguments from Tableau to pass to make new predictions. 

ERROR:__main__:{"ERROR": "AttributeError : 'ValueError' object has no attribute 'message'"}
ERROR:__main__:{"response": ["direct", "AttributeError : 'ValueError' object has no attribute 'message'"], "ERROR": "Failed query"}
OrderedDict([('uri', 'direct'), ('error', "AttributeError : 'ValueError' object has no attribute 'message'"), ('type', 'QueryFailed')])
ERROR:__main__:{"info": {"uri": "direct", "error": "AttributeError : 'ValueError' object has no attribute 'message'", "type": "QueryFailed"}, "ERROR": "Error querying GLS"}
ERROR:tornado.access:500 POST /query/direct (127.0.0.1) 9.97ms
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.
ERROR:__main__:{"info": "The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.", "ERROR": "Error processing script"}
WARNING:tornado.access:404 POST /evaluate (127.0.0.1) 1043.74ms

**Comment by FrancoSwiss** [comment]
@kitakoj18, did you solve it? We have the same problems :-(

**Comment by heidiporter** [comment]
Franco, did you solve this?

**Comment by FrancoSwiss** [comment]
Heidi, pickling seemed the issue in our case. It did not work with Keras/TensorFlow, but did work with Scikit-Learn. Does that help?

**Comment by Santhoshsekar89** [comment]
What is the pickling issue Franco? Can you explain because im also facing the same issue now.

**Comment by FrancoSwiss** [comment]
@Santhoshsekar89, I remember vaguely ......that TabPy did not like the pickling in combination with Keras/TensorFlow. It simply didn't work. Only with Scikit-Learn.
