### ISSUE TITLE
Error in connection

### ISSUE THREAD

**Issue by Chiangkim** [tableau/TabPy#135]
Hello all,

I met a trouble in configuration: Tableau is unable to connect the server.
"External Service: The external server is busy or not responding. Failed to create socket to it. ExtSvc: Couldn't connect to server"
![image](https://user-images.githubusercontent.com/13915357/47301888-51888880-d620-11e8-99d9-a1b17fd6b7f8.png)

After clicking startup.bat, http://localhost:9004/ can be open, and tableau logo is there.
Meanwhile, I also tried to use other ports using 
`startup.bat [port] `

in shell, but the error remains.

I also tried to type 
`python tabpy.py`
in shell, and it raised an error:
```
  File "tabpy.py", line 761, in <module>
    main()
  File "tabpy.py", line 707, in main
    state_file_path = os.environ['TABPY_STATE_PATH']
  File "C:\Anaconda3\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TABPY_STATE_PATH'
```

Based on a previous discussion github.com/tableau/TabPy/issues/24 , because my PC is under company's firewall, it would be caused by firewall settings. I added inbound rules in windows firewall, to enable ports and Tableau, but it still doesn't work. 

> %ProgramFiles%\Tableau\Tableau 10.4\bin\tableau.exe

![image](https://user-images.githubusercontent.com/13915357/47301753-ee96f180-d61f-11e8-8d84-081f6dffd844.png)
![image](https://user-images.githubusercontent.com/13915357/47301783-066e7580-d620-11e8-9824-2613d1e07c50.png)

OS: windows 7
Version: Tableau desktop 10.4.8

-------
update: Rserve works in the same condition, but Tabpy not.

Thank you in advance

**Comment by WillAyd** [comment]
Based off of your traceback it looks like this is an older version of TabPy. Can you run against the master branch?

**Comment by WillAyd** [comment]
@nmannheimer what is the policy to update the version of TabPy on PyPi? Seems like there are some bugs out there that a new release might help

**Comment by leonardolins** [comment]
I was having the same problem. Try run the script tabpy_server/startup.sh. After doing that try to connect the external service at Tableau.
MacOS High Sierra
Tableau 10.5.0

**Comment by nmannheimer** [comment]
@leonardolins Are you able to connect to TabPy through the browser by going to http:<TAbPyIP>:9004 on your Mac?
