### ISSUE TITLE
how to run Tabpy server on localhost:9001?

### ISSUE THREAD

**Issue by maxmansouri** [tableau/TabPy#137]
Hello,

I feel the answer to my question is a stupid easy one. Here it is, I'm trying to integrate Tableau with Tabpy. I have installed Tabpy and ran "pip install tabpy-server" in terminal and looks like it installed successfully. I am trying to manage external service connection and connect the two but I get an error message saying "Tableau is unable to connect to the service. Verify that service is running.." 

Ok I don't think my service is running on any port. I believe that's the step I'm missing. Let me know what I'm doing wrong? I'm working off of a mac. Thank you.

**Comment by johng42** [comment]
Tabpy uses port 9004 (not 9001) by default.
If you want to use 9001, you will need to modify Tabpy to use that port.

From the docs:
Creating a config.py file
    copy the template file from tabpy_server/common/config.py.template to tabpy_server/common/config.py and edit the settings that need changing.

In this case, the port in that file will need to be changed from 9004 to 9001.

Alternately, you could just use 9004.

**Comment by BBeran** [comment]
Startup script looks if there are any arguments passed to it, if not picks 9004. You can pass 9001 in the command line when starting the service.

e.g.

startup.bat 9001

**Comment by maxmansouri** [comment]
I'm okay with using the default port 9004. I just dont know how to get it going in tabpy. This is all I have done so far > download the tabpy zip > install tabpy-server.. whats my next step here so that tableau recognizes the port and connects to tabpy?

**Comment by maxmansouri** [comment]
Anyone?

**Comment by nmannheimer** [comment]
Hi @maxmansouri, once you have installed TabPy, you can run it with the startup.bat script or navigate to the directory where tabpy.py is and run from the command line: python tabpy.py 

(the second route assumes that you have python on your system path).

Either of these options will start the tabpy server. To connect to it from Tableau, follow these instructions: https://www.tableau.com/about/blog/2016/11/leverage-power-python-tableau-tabpy-62077

**Comment by nmannheimer** [comment]
We are also working on a set of improvements for TabPy, including a major simplification of the setup process. Look for more information soon!

**Comment by 0golovatyi** [comment]
@maxmansouri do you still experience the issue?

**Comment by ibsherzod** [comment]
@0golovatyi 
I have issue with running tabpy-server as startup.bat file doesn't run at ll. I ran as admin, with cmd but still no result. Please see errors I am getting. I feel like it is path issue, but it is my guess. Thank you.
![issue-0](https://user-images.githubusercontent.com/47643045/52811540-fc530580-305a-11e9-8c98-2713bbe0b6d2.png)
![issue-1](https://user-images.githubusercontent.com/47643045/52811541-fc530580-305a-11e9-8154-77201c4251f8.png)
![issue-2](https://user-images.githubusercontent.com/47643045/52811543-fc530580-305a-11e9-8e09-00833e2e4b6d.png)

**Comment by nmannheimer** [comment]
Hi @maxmansouri and @ibsherzod, please use these instructions to start TabPy: https://github.com/tableau/TabPy/blob/master/docs/server-startup.md

We have made numerous improvements to the install process and documentation that should help with these issues.

**Comment by ibsherzod** [comment]
Thank you for reply, but again startup.bat file doesn't run at all. I hope you had a chance to look at attached pictures for the problem. Really appreciate.

**Comment by nmannheimer** [comment]
Hi @ibsherzod yes looking at the pictures you are using an older version of TabPy that is designed to run with Anaconda. This complicated the install workflow and is something we have removed in the latest versions. I would suggest deleting the version you have now and following the setup instructions in the link above. The new start file is called startup.cmd which will both install TabPy and start the server.

**Comment by ibsherzod** [comment]
@nmannheimer 
I really appreciate your reply. Per your request, I am using new installation that has cmd extension. Again, it started but I am getting python is not recognized error as seen below. Would you please help to what to create in PATH (under user/system environment variables ) so that it will trigger python to run? Thank you so much. 

![image](https://user-images.githubusercontent.com/47643045/52861994-b39e5980-30f9-11e9-83d8-d4a06e77af56.png)

**Comment by ibsherzod** [comment]
@nmannheimer 
Here is update. I was eventually able to run python as it is recognized now. I added new path to system variable as _C:\Users\userxxx\AppData\Local\Continuum\anaconda3_ . However, I am getting another error as below: 
![image](https://user-images.githubusercontent.com/47643045/52870551-b99e3580-310d-11e9-889c-3939d879c42a.png)
Please, advise what I am doing wrong here. Really appreciate your help/hint.

**Comment by ibsherzod** [comment]
Finally, I was able to successfully to run it. Thanks again.

**Comment by nmannheimer** [comment]
Hi @ibsherzod can you post here what steps you took to get it running?

**Comment by 0golovatyi** [comment]
My guess is the problem was caused by @ibsherzod trying to run tabpy-server not from the local repo but form Python packages folder.

**Comment by ibsherzod** [comment]
I haven't done anything other than deleting Anaconda and installing Python 3.6.5 version and clicking add PATH option and the rest of them are same as described in the installation process.

**Comment by 0golovatyi** [comment]
@maxmansouri was your issue resolved or you still can't make TabPy start?

**Comment by vallimangai** [comment]
> @0golovatyi
> My question could be very simply, but I think I am doing something wrong here. I successfully installed tabpy-server, however I have issue with running tabpy-server as startup.bat file doesn't run at all. I ran as admin, with cmd but still no result. Please see errors I am getting. I feel like it is path issue, but it is my guess. Thank you and any suggestions or directions appreciated.
> 
> ![issue-0](https://user-images.githubusercontent.com/47643045/52811540-fc530580-305a-11e9-8c98-2713bbe0b6d2.png)
> 
> ![issue-1](https://user-images.githubusercontent.com/47643045/52811541-fc530580-305a-11e9-8154-77201c4251f8.png)
> 
> ![issue-2](https://user-images.githubusercontent.com/47643045/52811543-fc530580-305a-11e9-8e09-00833e2e4b6d.png)

I have the same issue is there any way to come out of it

**Comment by 0golovatyi** [comment]
@vallimangai  you don't need to install tabpy-server. Here are instructions for how to install and start TabPy - https://github.com/tableau/TabPy/blob/master/docs/server-install.md
