### ISSUE TITLE
LoadFailed: u'Load failed: No module named model_selection._search'

### ISSUE THREAD

**Issue by AprilWang93** [tableau/TabPy#141]
Hi, When I deploy Suggest Diagnosis to Tabpy Server
connection.deploy('DiagnosticsDemo111',
                  SuggestDiagnosis,
                  'Returns diagnosis suggestion based on ensemble model trained using Wisconsin Breast Cancer dataset')

It got an error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-24-623dc082c3eb> in <module>()
      3 connection.deploy('DiagnosticsDemo111',
      4                   SuggestDiagnosis,
----> 5                   'Returns diagnosis suggestion based on ensemble model trained using Wisconsin Breast Cancer dataset')
/usr/local/lib/python2.7/site-packages/tabpy_client/client.pyc in deploy(self, name, obj, description, schema, override)
    330             self._service.set_endpoint(_Endpoint(**obj))
    331 
--> 332         self._wait_for_endpoint_deployment(obj['name'], obj['version'])
    333 
    334     def _gen_endpoint(self, name, obj, description, version=1, schema=[]):
/usr/local/lib/python2.7/site-packages/tabpy_client/client.pyc in _wait_for_endpoint_deployment(self, endpoint_name, version, interval)
    451                 if ep['status']  == 'LoadFailed':
    452                     raise RuntimeError("LoadFailed: %r" % (
--> 453                         ep['last_error'],
    454                     ))
    455 
RuntimeError: LoadFailed: u'Load failed: No module named model_selection._search'

But SuggestDiagnosis function runs well when I test it with a test case locally. Like this: SuggestDiagnosis(1,1,1,1,1,1,1,1,1), it returns ['benign']

Any ideas why that error occurs?
Thanks,

**Comment by WillAyd** [comment]
Probably a versioning issue. See here:

https://stackoverflow.com/a/40704570/621736
