### ISSUE TITLE
Tableau is unable to connect to the service.

### ISSUE THREAD

**Issue by l0r1w1lson** [tableau/TabPy#143]
I'm able to connect to my Tabpy server via my browser, but the External Connection via Tableau is giving me this error:

Tableau is unable to connect to the service. Verify that the service is running and that you have access privileges.

The port is obviously open on the server; does 9004 have to be "unblocked" on my desktop?

**Comment by 0golovatyi** [comment]
@l0r1w1lson what version of Tableau you are using (I am assuming it is Tableau Desktop)?
