### ISSUE TITLE
python-requires 

### ISSUE THREAD

**Issue by leightonium** [tableau/TabPy#148]
https://github.com/tableau/TabPy/blob/c9b1d1ce32f01cad0523cdeee72447173fc8ab13/tabpy-server/setup.py#L11

SyntaxError: keyword can't be an expression

Shouldn't it be python_requires not python-requires ?
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by nmannheimer** [comment]
Hi @leightonium, thanks for the catch, we're correcting this now!

**Comment by nmannheimer** [comment]
@leightonium we've corrected the issue and the install should proceed normally now!
