### ISSUE TITLE
ModuleNotFoundError: No module named 'tabpy_server'

### ISSUE THREAD

**Issue by rongfactual** [tableau/TabPy#149]
I got a ModuleNotFoundError: No module named 'tabpy_server' when try to run ./startup.sh.

**Comment by nmannheimer** [comment]
Hi @rongfactual, thanks for the alert, we're looking into this now!

**Comment by nmannheimer** [comment]
@rongfactual  thanks for the note! We have just added a quick fix that should address this issue! Please let us know if you continue to have trouble.
