### ISSUE TITLE
ImportError: No module named tabpy_server.psws.python_service

### ISSUE THREAD

**Issue by l0r1w1lson** [tableau/TabPy#153]
Hello - I need help with a tabby install on Mac OS please.

**Comment by nmannheimer** [comment]
@l0r1w1lson thanks for the note! We have just added a quick fix that should address this issue! Please let us know if you continue to have trouble.

**Comment by l0r1w1lson** [comment]
So I have to re-do the install?

Lori G. Wilson | Bioinformatics Senior Software Engineer
CareDx, Inc. | Your Partner in Transplant Care
Email: lwilson@caredx.com<mailto:mmartell@caredx.com> | Phone: 415.287.2334 | Mobile: 510.685.6571 | www.CareDx.com<http://www.caredx.com/>

**Comment by nmannheimer** [comment]
@l0r1w1lson yeah download the latest version from here, unzip, and run startup.cmd and it should run just fine.

**Comment by l0r1w1lson** [comment]
Sorry for the delayed response, but it is still not working.  The new error is:

ImportError: No module named configparser

Lori G. Wilson | Bioinformatics Senior Software Engineer
CareDx, Inc. | Your Partner in Transplant Care
Email: lwilson@caredx.com<mailto:mmartell@caredx.com> | Phone: 415.287.2334 | Mobile: 510.685.6571 | www.CareDx.com<http://www.caredx.com/>

**Comment by nmannheimer** [comment]
Hi @l0r1w1lson, 

Which version of Python are you using? TabPy requires 3.x and we strongly recommend 3.6.5+ to ensure full compatibility.

**Comment by 0golovatyi** [comment]
@l0r1w1lson what are your installation steps, what command you are trying to run when you see the error?
