### ISSUE TITLE
Deploying objects on the TabPy server

### ISSUE THREAD

**Issue by idanivanov** [tableau/TabPy#16]
Hi,

I think it would be great if there was the option to deploy not only functions but also objects on the TabPy server.

I am using scikit-learn models to predict values in Tableau. Currently, when having a pre-trained model (a Python object), I store it in a pickle file and read it from the file system every time I execute my TabPy deployed function.

Deploying the object to the TabPy server can save the trouble of manually managing pickle files. It may also slightly improve performance (considering my use case).

Best regards,
Ivan

**Comment by BBeran** [comment]
Hi Ivan,
Did you try referring to the trained model in the function you're publishing without manually pickling it? It should automatically pickle it and store as part of the model on publish.

Thank you,

Bora

**Comment by idanivanov** [comment]
Hi Bora,

I tried it now. It works great! Thank you!

Best regards,
Ivan

**Comment by yelizkilinc** [comment]
Hello,
Where are you putting the trained model on tabPy and how (.py?)? Or should I firstly pickle.dump(modelobject,file) and then by using this object, should I put it into a function (return modelobject.predict())?

Could you please write me steps with file extensions/where to put?

Thank you
