### ISSUE TITLE
NUMPY_MKL error

### ISSUE THREAD

**Issue by Alro10** [tableau/TabPy#162]
HI! 

I found this error when I tried to run calculated field that uses numpy and scipy:

ERROR:__main__:{"info": "ImportError : cannot import name 'NUMPY_MKL'", "ERROR": "Error processing script"}

The script is:

SCRIPT_REAL("

import numpy as np
import pandas as pd

from scipy.stats import norm

y_normal = norm.pdf(_arg1)

return y_normal",
SUM([Score Quaasar])
)

I reinstalled numpy+mkl whl and scipy whl but didn't work.

Thanks in advance!

**Comment by nmannheimer** [comment]
Hi @Alro10, what version of Python are you running and on which OS?

**Comment by Alro10** [comment]
Hi @nmannheimer 

python 3.5
windows 10

**Comment by nmannheimer** [comment]
Hey @Alro10,

Are you able to run this script on the same data outside of Tableau but in the same Python environment where your TabPy instance is running? Also, TabPy is officially supported for 3.6.5 so I would suggest running it in that version as well.

Sincerely,
Nathan
