### ISSUE TITLE
Error on executing setup.bat

### ISSUE THREAD

**Issue by tdries** [tableau/TabPy#17]
Hi,

Whenever I try to install the setup.bat file the installation runs for a while but stops on this error:

![install_fail](https://cloud.githubusercontent.com/assets/25056342/21856050/d760938a-d820-11e6-9568-5e93d5dfab9f.PNG)

any ideas what is going on here?

Kind Regards,
Tim Dries

**Comment by BBeran** [comment]
Hi Tim,
Does installation fail if you hit OK or still completes? This error happens when Anaconda fails to create Windows Start Menu shortcuts. It could be due to user privileges and/or menu items already being there.

Thank you,

Bora

**Comment by BBeran** [comment]
If this issue resulted in a failed installation and caused TabPy not to function, please reactivate this issue. 

Thank you,

Bora
