### ISSUE TITLE
Setup ignores installed Anaconda3 

### ISSUE THREAD

**Issue by mimakaev** [tableau/TabPy#18]
I have Anaconda3 on Windows, and tried to run a setup. Setup script told me "No existing Anaconda installations found".  It then proceeded to download it's own Anaconda and failed. 

I tried doing a fresh install of Anaconda3, and it did not help.

**Comment by BBeran** [comment]
Hi Maksim,
Install script looks for Anaconda in the registry and the path. If it can't find it either place, assumes it is not there.

You can manually create a Python 2.7 environment in your existing Anaconda installation.

``conda create --name Tableau-Python-Server python=2.7 anaconda
``

then activate it

and do the pip install from local folders

``
pip install -r ./tabpy-server/requirements.txt
pip install ./tabpy-client
pip install ./tabpy-server
``

**Comment by jorwoods** [comment]
Same issue here. It ignored my existing install of Anaconda3.

**Comment by rileyrustad** [comment]
I'm still getting the same message as @mimakaev . Even after following the instructions above from @BBeran. I don't think TabPy is Anaconda3 compatible yet. I tried editing the setup.bat file to look in the correct directory, but I'm not able to figure it out.

**Comment by BBeran** [comment]
if you already have Anaconda, all you need to do is to activate the environment in which you would like to install TabPy then from the command line do 

pip install tabpy-server

As of February, tabpy is on PyPI so you don't need to go through setup script at all if you have Anaconda installed already.

**Comment by MarleenMeier** [comment]
I have similar problems, I get e.g. this error:
![error comment](https://user-images.githubusercontent.com/34099686/33382393-eac79790-d520-11e7-9623-47f981bf9c77.PNG)

**Comment by Proteusiq** [comment]
if you have conda, you do not pip to get tabpy-server.

conda install tabpy-server

Works without problem on my end. The best way is it update your conda, then create TabPy environment with a Python version of your choice and install anaconda and tabpy-server libraries.

**Comment by BBeran** [comment]
The error messages indicate not being able to hit the server to get packages. It might be your IT admin blocking internet access through that port etc. You may try to do conda install as in the previous message, but it might fail due to same reasons. I am not sure if conda and pip use different ports or not.

**Comment by MarleenMeier** [comment]
Thanks guys! In the meanwhile my local IT team confirmed that it is being blocked by global IT security. Weird enough, it worked with Rserve though. 
Anyways, is there a zip file which I can download and then install tabpy-server out of that file?
