### ISSUE TITLE
Unable to install Tabpy using Start cmd

### ISSUE THREAD

**Issue by v1ewlakes** [tableau/TabPy#184]
On Windows 2012 Server, Unable to install Tabpy using Start cmd
Error message - python not found

**Comment by johng42** [comment]
If you type 
where python

at a command prompt what do you see?

By default, python does not add itself to the system path.

I suggest adding the location of the python instance you want to run to the end of the system path.  

set PATH=%PATH%; <<<add the path to your instance of python here>>>

You can also modify the system path by right clicking My Computer | Properties | Advanced System Settings (link in the left pane) and then open the Environment Variables UI.

**Comment by v1ewlakes** [comment]
This is resolved. Installed 64 bit python first..than ran start.cmd script
Thanks

⁣Get BlueMail for Android ​
