### ISSUE TITLE
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

### ISSUE THREAD

**Issue by a9337435352ankitarichi** [tableau/TabPy#186]
I checked in localhost:9004/endpoints to check if my model has been correctly deployed and i found that my model is present along with 3 other models that i previously deployed for other tableau workbooks.
Now when i use this model in my calculation i get an error regarding the endpoint.

I think the endpoints is holding a lot of models which is the reason that the Tableau calculation is not working. Kindly help me

**Comment by nmannheimer** [comment]
Hi @a9337435352ankitarichi Following these instructions, are you able to query the endpoints using code?
https://github.com/tableau/TabPy/blob/master/docs/tabpy-tools.md#evaluating-arbitrary-python-scripts

Each endpoint should only hold one model, though it can be overwritten and previous versions will get saved.
