### ISSUE TITLE
Cannot setup

### ISSUE THREAD

**Issue by ettobias** [tableau/TabPy#2]
I ran setup.bat, and ran into a failed install. I also tried installing manually, but in both cases I have one error. During the "pip install -r ./tabpy-server/requirements.txt" command I get "no such file or directory". And indeed, there is no tabpy-server directory anywhere in the Anaconda directory. I'm assuming one of the previous commands didn't retrieve it or something.

**Comment by BBeran** [comment]
Hi ettobias,
Setup.bat is in Tabpy-master folder while requirements.txt is under Tabpy-master/tabpy-server/ so when you initialize setup.bat it is looking for the file in a subdirectory in the same folder as setup.bat as opposed to looking for it in Anaconda directory.

When you unzip Tabpy-master.zip and do a `cd tabpy-server` while you're in Tabpy-master folder in Windows command line, do you see the requirements.txt or is it missing? If so, does it still fail the same way when you do a `cd ..` to go back into Tabpy-master folder and try running setup.bat from there.

Thanks,

Bora

**Comment by ettobias** [comment]
OK, hopefully I'm not just being dense, but I don't see a "tabpy-master.zip" anywhere. I've looked on GitHub, in the installation directories. No tabpy-master.zip to be found. Where would I find that file, and where have I missed it in the install instructions?

**Comment by BBeran** [comment]
On the Github landing page, there should be a green link on the right hand side [Clone or download]. You can get a zip from there. Once you download you can navigate into the folder containing setup.bat and initiate from there.

**Comment by ettobias** [comment]
Ugh... I was afraid it was something obvious. I'm new to GitHub, as you can probably tell. Thank you. Setup.bat ran just fine. Thanks for the help.
