### ISSUE TITLE
Install Pep8speaks

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#208]
After #205 and #206 are merged I would suggest installing pep8speaks:

https://github.com/OrkoHunter/pep8speaks

It's easy to install and something I've used with the pandas codebase. It automatically calls out styling issues with code which streamlines automation and keeps your code generally looking nicer

**Comment by 0golovatyi** [comment]
We actually have it configured for the repo as github app - https://github.com/tableau/TabPy/settings/installations. Currently, it runs with pushing and merge request creation for dev branch.

**Comment by WillAyd** [comment]
Looks like this is available when targeting dev - closing!
