### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#209]
Right now there is nothing to run the tests automatically once PRs are pushed. Travis and Azure are two popular apps you should consider installing for the project:

https://github.com/marketplace/travis-ci
https://github.com/marketplace/azure-pipelines

At a minimum I think CI should run the startup scripts provided and subsequently run the test suites. 

I do think there are some things hacky with the current codebase that code pose a challenge. The biggest thing is the fact that the startup scripts not only perform all installation but also being the application. I *think* we'll want to separate out environment creation / setup from running the applications, but it's worth trying as is with CI and seeing how far we get

**Comment by 0golovatyi** [comment]
We have Travis CI configured and running for dev branch: unit tests, pep8speak, code coverage. Planning to merge some of it to master soon.
