### ISSUE TITLE
Logically Separate Tools and Server Packages

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#210]
There is at least one dependency in the server package on the tools package:

https://github.com/tableau/TabPy/blob/20776676e6d8cfb2ad53e4573a4857565b769ed3/tabpy-server/tabpy_server/psws/python_service.py#L7

With the current project structure this implicitly bundles the packages together, but from a true distribution perspective this would be less than ideal.

**Comment by 0golovatyi** [comment]
@WillAyd What I am planning to do instead is create one single `tabpy` package with server and tools included in it. Here's PR if you are interested - https://github.com/tableau/TabPy/pull/330.

I am going to close this issue in a few days FYI.
