### ISSUE TITLE
Clean Up Bare Exception Catching

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#212]
There's quite a few places in the code base where we do `except Exception` - this can lead to unintended consequences since we are blanket catching any and everything that could happen within the try block.

It's almost always preferable to catch the actual Exceptions instead; will post a list of what is in master after #205 gets merged as this is something that likely will be done in multiple PRs

**Comment by 0golovatyi** [comment]
I believe all `except:` cases were fixed, closing the issue.
