### ISSUE TITLE
Render Code Blocks in Documentation

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#213]
Follow up to https://github.com/tableau/TabPy/pull/205/files#r264515662 we could potentially use the Sphinx [iPython directive](https://ipython.org/ipython-doc/rel-0.13.1/development/ipython_directive.html) to generate code in docstrings

**Comment by 0golovatyi** [comment]
@WillAyd I looked at the IPython directives and how those are applicable for TabPy and not sure I understand what exactly you suggest we do. Could you show some example for other repos use it or point me to an article or something where I can find more info?

**Comment by WillAyd** [comment]
Here's the documentation I am referring to:

https://ipython.org/ipython-doc/rel-0.13.1/development/ipython_directive.html

**Comment by 0golovatyi** [comment]
Yeah, I saw the link and read the whole thing. I am probably missing something obvious there but still can't see how it is applicable anywhere in TabPy :(

**Comment by WillAyd** [comment]
Yea the main point was to not have to hard code output in docstrings which is in a few places. 

Would require Sphinx which we aren’t using and there’s probably bigger things to take care of so can close this for now.
