### ISSUE TITLE
Tabpy installation fails

### ISSUE THREAD

**Issue by bashiiiwa** [tableau/TabPy#22]
Hi, Let me ask one question:
Our customer trying to install Tabpy on MAC OS.
When running  sh setup.sh , it fails with following logs.
Please give me advice on how to install Tabpy on MAC.

MAC-0035N:TabPy gm3293$ sh setup.sh
~~~~~~~~~~~~~~~ Downloading and installing Anaconda ~~~~~~~~~~~~~~~
Anaconda installed already.
prepending //anaconda/bin to PATH
~~~~~~~~~~~~~~~ Activating the environment ~~~~~~~~~~~~~~~
Conda env 'Tableau-Python-Server' already exists.
prepending //anaconda/envs/Tableau-Python-Server/bin to PATH
~~~~~~~~~~~~~~~ Installing dependencies ~~~~~~~~~~~~~~~
Processing /Users/gm3293/TabPy/tabpy-client
Requirement already satisfied (use --upgrade to upgrade): tabpy-client==0.2 from file:///Users/gm3293/TabPy/tabpy-client in ./envs/Tableau-Python-Server/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
Requirement already satisfied (use --upgrade to upgrade): decorator in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
Requirement already satisfied (use --upgrade to upgrade): requests in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
Requirement already satisfied (use --upgrade to upgrade): genson in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from python-dateutil->tabpy-client==0.2)
Building wheels for collected packages: tabpy-client
Running setup.py bdist_wheel for tabpy-client ... done
Stored in directory: /Users/gm3293/Library/Caches/pip/wheels/f5/75/7a/7335361e6574d929e9815d4d8cdd7c24de279153f0cc3e3001
Successfully built tabpy-client
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /Users/gm3293/TabPy/tabpy-server
Requirement already satisfied (use --upgrade to upgrade): tabpy-server==0.2 from file:///Users/gm3293/TabPy/tabpy-server in ./envs/Tableau-Python-Server/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): future in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): futures in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): requests in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): simplejson in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): Tornado-JSON in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): tornado in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): decorator in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): genson in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): tabpy-client in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): numpy in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from python-dateutil->tabpy-server==0.2)
Building wheels for collected packages: tabpy-server
Running setup.py bdist_wheel for tabpy-server ... done
Stored in directory: /Users/gm3293/Library/Caches/pip/wheels/50/db/71/f27071d4a2cafa208f19a43bc95f14a6d1b497d401c59355e7
Successfully built tabpy-server
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~~~~~~~~~~~~~~~~~ Installation failed ~~~~~~~~~~~~~~~~
MAC-0035N:TabPy gm3293$ pip install --upgrade pip
Requirement already up-to-date: pip in /anaconda/lib/python3.5/site-packages

**Comment by BBeran** [comment]
Can you try going to the folder

./envs/Tableau-Python-Server/lib/python3.5/site-packages/tabpy_server

and running startup.sh

It looks like it installed but exited with incorrect error message.

Thank you,

Bora

**Comment by bashiiiwa** [comment]
Thank you for quick response. I'll ask customer to check.
Thank you.
Tomohiro.

**Comment by bashiiiwa** [comment]
The directory:
./envs/Tableau-Python-Server/lib/python3.5/site-packages/tabpy_server
Cannot be found.

So customer executed from install directory
MAC-0035N:tabpy_server gm3293$ pwd
/Users/gm3293/TabPy/tabpy-server/tabpy_server
MAC-0035N:tabpy_server gm3293$ ls -ls
total 96
0 drwxr-xr-x 8 gm3293 staff 272 3 1 13:37 common
0 drwxr-xr-x 5 gm3293 staff 170 3 1 13:37 management
0 drwxr-xr-x 5 gm3293 staff 170 3 1 13:37 psws
8 -rw-r--r-- 1 gm3293 staff 445 3 1 13:37 startup.bat
8 -rw-r--r-- 1 gm3293 staff 511 3 1 13:37 startup.py
8 -rw-r--r-- 1 gm3293 staff 664 3 1 13:37 startup.sh
8 -rw-r--r-- 1 gm3293 staff 169 3 2 11:59 state.ini
8 -rw-r--r-- 1 gm3293 staff 169 3 1 13:37 state.ini.template
0 drwxr-xr-x 4 gm3293 staff 136 3 1 13:37 static
56 -rw-r--r-- 1 gm3293 staff 27969 3 1 13:37 tabpy.py
MAC-0035N:tabpy_server gm3293$ sh startup.sh
Found existing state.ini
Traceback (most recent call last):
File "/Users/gm3293/TabPy/tabpy-server/tabpy_server/tabpy.py", line 3, in
<module>
import simplejson
ImportError: No module named 'simplejson'


simplejson is missing 
Is it possible to install simplejason file ?

Best Regards,
Tomohiro

**Comment by bashiiiwa** [comment]
Customer reported that he could start with following start.sh
/anaconda/envs/Tableau-Python-Server/lib/python3.5/site-packages/tabpy_server/startup.sh
Thank you for support.

**Comment by BBeran** [comment]
Great to hear

**Comment by Tinni88** [comment]
Hello Bora,
I have downloaded TabPy_Master from github and run setup.bat file. Its showing anaconda installed but there are few errors at the end. And in c:\Users\User Name\Anaconda\envs\Tableau-Python-Server\Lib\site-packages,the tabpy_server folder is missing. I even tried out the path /anaconda/envs/Tableau-Python-Server/lib but here I couldn't find the folder python3.5. Can you please guide me as how to proceed.
Thanks,
Ankita

**Comment by karatikasssssss** [comment]
> Hi, Let me ask one question: Our customer trying to install Tabpy on MAC OS. When running sh setup.sh , it fails with following logs. Please give me advice on how to install Tabpy on MAC.
> 
> MAC-0035N:TabPy gm3293$ sh setup.sh
> 
> ```
> Anaconda installed already.
> prepending //anaconda/bin to PATH
> ~~~~~~~~~~~~~~~ Activating the environment ~~~~~~~~~~~~~~~
> Conda env 'Tableau-Python-Server' already exists.
> prepending //anaconda/envs/Tableau-Python-Server/bin to PATH
> ~~~~~~~~~~~~~~~ Installing dependencies ~~~~~~~~~~~~~~~
> Processing /Users/gm3293/TabPy/tabpy-client
> Requirement already satisfied (use --upgrade to upgrade): tabpy-client==0.2 from file:///Users/gm3293/TabPy/tabpy-client in ./envs/Tableau-Python-Server/lib/python3.5/site-packages
> Requirement already satisfied (use --upgrade to upgrade): cloudpickle in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
> Requirement already satisfied (use --upgrade to upgrade): decorator in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
> Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
> Requirement already satisfied (use --upgrade to upgrade): requests in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
> Requirement already satisfied (use --upgrade to upgrade): genson in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
> Requirement already satisfied (use --upgrade to upgrade): jsonschema in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-client==0.2)
> Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from python-dateutil->tabpy-client==0.2)
> Building wheels for collected packages: tabpy-client
> Running setup.py bdist_wheel for tabpy-client ... done
> Stored in directory: /Users/gm3293/Library/Caches/pip/wheels/f5/75/7a/7335361e6574d929e9815d4d8cdd7c24de279153f0cc3e3001
> Successfully built tabpy-client
> You are using pip version 8.1.1, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Processing /Users/gm3293/TabPy/tabpy-server
> Requirement already satisfied (use --upgrade to upgrade): tabpy-server==0.2 from file:///Users/gm3293/TabPy/tabpy-server in ./envs/Tableau-Python-Server/lib/python3.5/site-packages
> Requirement already satisfied (use --upgrade to upgrade): future in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): futures in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): requests in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): simplejson in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): Tornado-JSON in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): tornado in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): cloudpickle in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): decorator in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): genson in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): jsonschema in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): tabpy-client in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): numpy in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from tabpy-server==0.2)
> Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./envs/Tableau-Python-Server/lib/python3.5/site-packages (from python-dateutil->tabpy-server==0.2)
> Building wheels for collected packages: tabpy-server
> Running setup.py bdist_wheel for tabpy-server ... done
> Stored in directory: /Users/gm3293/Library/Caches/pip/wheels/50/db/71/f27071d4a2cafa208f19a43bc95f14a6d1b497d401c59355e7
> Successfully built tabpy-server
> You are using pip version 8.1.1, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ~~~~~~~~~~~~~~~~~ Installation failed ~~~~~~~~~~~~~~~~
> MAC-0035N:TabPy gm3293$ pip install --upgrade pip
> Requirement already up-to-date: pip in /anaconda/lib/python3.5/site-packages
> ```

**Comment by karatikasssssss** [comment]
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\tabpy.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\tabpy\tabpy.py", line 41, in main
    from tabpy.tabpy_server.app.app import TabPyApp
  File "C:\Python310\lib\site-packages\tabpy\tabpy_server\app\app.py", line 17, in <module>
    from tabpy.tabpy_server.handlers import (
  File "C:\Python310\lib\site-packages\tabpy\tabpy_server\handlers\__init__.py", line 1, in <module>
    from tabpy.tabpy_server.handlers.base_handler import BaseHandler
  File "C:\Python310\lib\site-packages\tabpy\tabpy_server\handlers\base_handler.py", line 6, in <module>
    import tornado.web
  File "C:\Python310\lib\site-packages\tornado\web.py", line 88, in <module>
    from tornado import httputil
  File "C:\Python310\lib\site-packages\tornado\httputil.py", line 107, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
    



anybody can help me?

**Comment by 0golovatyi** [comment]
@karatikasssssss Have you tried installing TabPy with installation instructions - https://github.com/tableau/TabPy/blob/master/docs/server-install.md ?

**Comment by karatikasssssss** [comment]
yes
actually 2 problems are there after installing tabpy-server it was not showing in file and second the above one mutablemapping is showing dont know

**Comment by 0golovatyi** [comment]
@karatikasssssss what tabpy-server? There's nothing about installing tabpy-server in the instructions. What steps are you following?
