### ISSUE TITLE
Daemon mode?

### ISSUE THREAD

**Issue by astewart-twist** [tableau/TabPy#23]
Does TabPy currently have some sort of daemon mode built in?  If not, what's the current recommended practice - screen/tmux?  Docker container?

**Comment by BBeran** [comment]
On Mac instead of this
```bash
./startup.sh
```
you can start it this way if you want to write to a log file
```bash
nohup ./startup.sh 0<&- &> my.log.file &
```

if you don't want to write errors to a log file
```bash
nohup ./startup.sh 0<&- &>/dev/null &
```

**Comment by rvschaffer** [comment]
To run TabPy in Virtual Environment, the file startup.sh' contents would be:
`source my-tabpy-env/bin/activate` 
`tabpy`
Is this correct?

**Comment by rvschaffer** [comment]
How do you stop the service later? I tried to `deactivate` the virtual environment a few days later, and it says:
`-bash: deactivate: command not found`

**Comment by 0golovatyi** [comment]
@rvschaffer For "background" service on Linux/mac check `screen` command - https://linux.die.net/man/1/screen. For Windows read this - http://tabscifi.golovatyi.info/2021/01/how-to-run-tabpy-as-windows-service/

`deactivate` command is for virtual environment, not for service itself. Some reading on that - http://tabscifi.golovatyi.info/2020/11/running-tabpy-with-python-virtual-environment/.
