### ISSUE TITLE
Error Running Script. No Return Value

### ISSUE THREAD

**Issue by JacobRColp** [tableau/TabPy#231]
I am having trouble starting up TabPy. I can get the server to run, but it consistently spits out an error message and I cannot connect from Tableau. I am at a loss as to what to do next. 

[https://i.imgur.com/LdRjAHg.png](url)
Link to picture of issue.

The error code that it spits out says "ExtSvc: Error running script. No return value."

Does anyone have any idea what I am doing wrong?

**Comment by 0golovatyi** [comment]
<img src="https://i.imgur.com/LdRjAHg.png" />

**Comment by 0golovatyi** [comment]
@JacobRColp could you try 127.0.01 instead of localhost?

**Comment by JacobRColp** [comment]
Unfortunately, I get that same error.

**Comment by 0golovatyi** [comment]
@JacobRColp What version of Tableau are you running?

**Comment by JacobRColp** [comment]
I am running 2018.3

**Comment by 0golovatyi** [comment]
@JacobRColp I'll try if can repro the failure. Just to confirm - your TabPy version is 0.3.2? You can check it either with VERSION file it TabPy root folder or in browser with "http://localhost/info" as URL.

**Comment by JacobRColp** [comment]
<img width="562" alt="Screen Shot 2019-03-29 at 11 36 30 AM" src="https://user-images.githubusercontent.com/45046429/55248013-f2562200-5216-11e9-9693-583d725bd760.png">
Yessir. Thank you so much for your help!

**Comment by johng42** [comment]
Can you post the Help | About Tableau dialog from Tableau?
Like this:
![image](https://user-images.githubusercontent.com/8153554/55251166-1876c480-520d-11e9-83f4-07e56c77c15f.png)

**Comment by JacobRColp** [comment]
<img width="558" alt="Screen Shot 2019-03-29 at 12 45 53 PM" src="https://user-images.githubusercontent.com/45046429/55252384-d0fa3380-5220-11e9-81e8-0f409358d329.png">
There's the screen.

**Comment by 0golovatyi** [comment]
No version info? Is this some private build?

**Comment by JacobRColp** [comment]
<img width="562" alt="Screen Shot 2019-03-29 at 12 54 49 PM" src="https://user-images.githubusercontent.com/45046429/55252921-f2a7ea80-5221-11e9-9348-8bc76e18758b.png">

My apologies. I misunderstood. That is the correct menu.

**Comment by johng42** [comment]
Thanks for the report.  I can repro and we are investigating.

**Comment by JacobRColp** [comment]
You guys rock! Thank you so much!

**Comment by 0golovatyi** [comment]
@JacobRColp we just submitted hotfix for the issue, could you get the latest TabPy and try with it? https://github.com/tableau/TabPy/archive/master.zip

**Comment by JacobRColp** [comment]
<img width="549" alt="Screen Shot 2019-03-29 at 5 52 27 PM" src="https://user-images.githubusercontent.com/45046429/55266542-893cd180-524b-11e9-85e8-c372622e3ab4.png">
That worked! Thank you guys so much! You rock!
