### ISSUE TITLE
Master vs Dev

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#235]
I think this may have been discussed before but it's not entirely clear what the purpose of the dev and master branches are in this repo. I think master is specifically for releases whereas dev is for active changes.

One of the problems here though is that these branches seem to be pretty divergent. IIUC correctly the current process is to manually copy changes over from dev into master, but that kind of defeats the purpose of using git in the first place

Most people coming to a GH site I think would just clone master. Would it be possible to start fresh and completely overwrite master with the dev branch as things are now? If that's the case it would be easier to do things like cherry-pick going forward to start leveraging the VCS instead of manual copying efforts

**Comment by 0golovatyi** [comment]
We are using `dev` as a branch for working on relatively big features (like authentication) and when merging to-from `master` we (Tableau) will take care of porting all the changes. The inconvenience for a contributor is when there's need to merge from `origin/master` to a fork and solution is to not accumulate a lot of changes and only keep your feature branches for a short time.

One of the reasons for us to use `dev` is to be able to work on it iteratively and have incomplete changes available for when working on changes for Tableau Desktop/Server at the same time. We are not going to ask contributors to bring changes in `dev` unless they want to.

**Comment by WillAyd** [comment]
So in terms of workflow if I start a new branch I should fork that off of master and PR request should be to merge into master right?

Only downside there is we only have CI configured against dev so IIUC most changes wouldn't get that

**Comment by 0golovatyi** [comment]
Yes, we want to keep as simple as possible for contributors and forking/merging with master is what we expect people do.

As for CI I opened PR which adds CI for master. With some recent issues we had in master it seems like we really need CI for it. There will be an incomplete auth feature which shouldn't affect any existing flow. And when we are done with auth there will be another merge from `dev` and release will be created.

**Comment by WillAyd** [comment]
Gotcha - thanks for clarifying
