### ISSUE TITLE
Tableau 10.2.0 No connection to tabpy

### ISSUE THREAD

**Issue by ramonrod** [tableau/TabPy#24]
Hi All,

I installed the latest Tabpy version in my OS (win7, Tableau Version 10.2.0). The installation was successful and the "Tableau-Python-Server" instance was created. Just after the installation the server started itself without problems using the startup.bat script.

Now I am having the following issue, when I open tableau or a workbook in Tableau with Python code I am not able to create a connection, I am following the steps described in the Github documentation, but I keep getting the same error: 
![image](https://cloud.githubusercontent.com/assets/1073588/23659419/5bb68888-0346-11e7-852e-36076a3f0fac.png)

I know, the error-message is in German, but I guess the important is the one in English. 

I did not see any errors while installing Tabpy, and the server seems to be running: 
_[Tableau-Python-Server] C:\Users\RODRIR\Anaconda\envs\Tableau-Python-Server\Lib
site-packages\tabpy_server>startup.bat
Deactivating environment "Tableau-Python-Server"...
Activating environment "Tableau-Python-Server"...
Initializing TabPy...
Done initializing TabPy.
Web service listening on port 9004_

Did I miss something? why I am not able to create a connection?

Hope someone can help me here.

**Comment by BBeran** [comment]
Hi,
Is Tableau and TabPy on the same machine? If so does your External Services configuration have host=http://localhost and port=9004? If both are correct and you're seeing an error when you hit [Test Connection] this is most likely a firewall issue.

Thanks,

Bora

**Comment by ramonrod** [comment]
Hi Bora,

Thanks for your reply. Yes, I have the correct information in External Services configuration, and I do work in my local computer.

I am getting the error-message:
"_IPC_Network::Resolve(hostname="http://localhost"): The requested name is valid, but no data of the requested type was found_"

I guess this is related to a Firewall issue since I'm doing this from office. Is there a known walk-around for this, may be extending the host-address to the environment? 

Best,
Ramon

**Comment by ramonrod** [comment]
Hi,
I found a way to deactivate our firewall, which works fine when connecting to other external services. The problem is, I am not able to connect to the tabpy-server, even when I specified a different port like 8080, which seems to work fine for other external services, as said.

I get this error every time when trying to connect:
"The requested name is valid, but no data of the requested type was found"

I get this error even outside office. Do you have an idea what could be the problem? I really would like to try Tabpy and tableau.

Thanks,
Ramon

**Comment by BBeran** [comment]
Hi Ramon,
"The requested name is valid, but no data of the requested type was found"
This error typically happens when there is something running on that port but it is not TabPy. When you go to the same address you entered in External Services dialog in your browser, do you see a Tableau logo?

E.g. http://localhost:9004

Thanks,

Bora

**Comment by ramonrod** [comment]
Hi Bora,

Yes, I see the tableau logo when I enter the address. I am using port '8080', it seems it is configured to work fine with my firewall. I also see the following result after 'netstat -na':  
TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING

By the way, the connection to Rserve is working without problems with port '6311'.

I guess there is a misconfiguration with port in tableau, I just can't figure it out.

here a new error for https://localhost:8080:
External Service: IPC_Network::Resolve(hostname="https://localhost"): The requested name is valid, but no data of the requested type was found ExtSvc: Failure when receiving data from the peer

Thanks,
Ramon

**Comment by ramonrod** [comment]
Hi Bora,
I was able to solve the problem. The issue was the company's firewall. After some configuration I got to work the way I wanted. Now Tableau is communicating to tabpy server.

Thanks a lot for your comments. Waiting for the final release of tabpy.

Thanks

**Comment by Chiangkim** [comment]
> Hi Bora,
> I was able to solve the problem. The issue was the company's firewall. After some configuration I got it to work the way I wanted. Now Tableau is communicating to tabpy server.
> 
> Thanks a lot for your comments. Waiting for the final release of tabpy.
> 
> Thanks
Hello Ramon,

Could you please show how did you solve this firewall question?
I met the same trouble when I am trying to use Tabpy in company's PC.

Thanks,
Kim
