### ISSUE TITLE
Syntax Error in tabpy-server/tabpy_server/app/util.py

### ISSUE THREAD

**Issue by silmor** [tableau/TabPy#260]
In the latest release (0.4) there seems to be a syntax error in tabpy-server/tabpy_server/app/util.py

python tabpy-server/tabpy_server/app/util.py

```
File "tabpy-server/tabpy_server/app/util.py", line 39
    f'The certificate provided expired on {not_after}.',
                                                      ^
SyntaxError: invalid syntax
```

**Comment by johng42** [comment]
https://github.com/tableau/TabPy/pull/261 has the fix for this.  Thanks for the report!

**Comment by 0golovatyi** [comment]
@silmor @johng42 How do you repro the issue?

**Comment by silmor** [comment]
@0golovatyi I can reproduce the issue by just cloning the repo and trying to run the start script. Or like described above by directly giving the file tabpy-server/tabpy_server/app/util.py a call.

OS is Linux and macOS, both with the same result.

**Comment by 0golovatyi** [comment]
Just tried on Mac, no repro. What Python version are you running?

**Comment by silmor** [comment]
Seems to be related to Python versions < 3.6. I tried a few different versions. From 3.6.0 onwards there no errors.

3.4.0 -> Error
3.5.3 -> Error
3.5.7 -> Error
3.6.0 -> OK
3.6.3 -> OK
3.6.8 -> OK
3.7.3 -> OK

**Comment by johng42** [comment]
We require Python 3.6 and support 3.6.5 or higher.  Your testing seems to bear that out.
The syntax between this logging call and the others does differ, though, so thanks for pointing that out.
I can close this out since your tests worked with supported versions of Python.

**Comment by WillAyd** [comment]
F-strings weren't introduced until Py36 so this is expected and not an issue with TabPy
