### ISSUE TITLE
Module Object has no attribute 'ABC'

### ISSUE THREAD

**Issue by caitlyngUR** [tableau/TabPy#262]
I am getting the following error:

    File "tabpy-tools\tabpy_tools\query_object.py", line 13, in <module>
        class QueryObject(abc.ABC):

    AttributeError: 'module' object has no attribute 'ABC'

**Comment by 0golovatyi** [comment]
@caitlyngUR Could you provide more details about your environment?
- What TabPy release are you using?
- What Python version are you running it with?
- What OS are you running it on?

**Comment by caitlyngUR** [comment]
TabPy version = 0.4
Python = 2.7
OS = Windows 10

**Comment by nmannheimer** [comment]
Hi @caitlyngUR 

TabPy requires at least python 3.x and we require 3.6.5 for full support (that's what we confirm test coverage on).

**Comment by caitlyngUR** [comment]
Thank you. I went through the following steps and it is now up and running:

1. Installed Python 3.7.3

2. Uninstalled both tornado and nbconvert
```
    pip uninstall tornado
    pip uninstall nbconvert

```
3. Re-installed those with correct versions
```
    pip install nbconvert==5.3.1
    pip install tornado==4.2
```

4. Navigated to tabpy_server folder 
`    cd C:\Users\CaitlynG\Anaconda3\Lib\site-packages\tabpy_server`

5. Ran the startup.bat file
`   startup.bat 9001`

**Comment by nmannheimer** [comment]
Great!
