### ISSUE TITLE
LoadFailed: "Load failed: No module named 'tabpy_client'"

### ISSUE THREAD

**Issue by caitlyngUR** [tableau/TabPy#264]
I am getting the following error when I go to publish a neural network model I had created to the TabPy localhost server:

![LoadFailed Error](https://user-images.githubusercontent.com/49031005/56440691-2a9dcd00-62b8-11e9-8ed6-a6823cdb5606.PNG)

I have already imported the module as so...
`import tabpy_client`

I even tried appending the PATH of the module to see if that would fix the issue...

![Path](https://user-images.githubusercontent.com/49031005/56440419-59677380-62b7-11e9-8615-340e1d927fbe.PNG)

And I have called the tabpy_client.Client previously with no error/warning:
`connection = tabpy_client.Client('http://localhost:9004/')`

I have already successfully connected to the localhost server through Tableau so it should run without a problem.

![Successful Connection to Localhost](https://user-images.githubusercontent.com/49031005/56440479-7bf98c80-62b7-11e9-9ad3-325d80aec150.PNG)

I am not sure as to what might be the issue. 
Any help would be fantastic!!

**Comment by 0golovatyi** [comment]
@caitlyngUR What release of TabPy are you running? You can confirm it with `curl localhost:9004/info` command.
For newer versions of TabPy it is `tabpy_tools` you need to use, see more details here - https://github.com/tableau/TabPy/blob/master/docs/tabpy-tools.md. You may need to run `pip install -e tabpy-tools` first for the steps to work.

**Comment by caitlyngUR** [comment]
I am running version 0.4

**Comment by 0golovatyi** [comment]
@caitlyngUR try `pip install -e tabpy-tools` from the repo root folder to install tabpy-tools package and then follow the steps mentioned at https://github.com/tableau/TabPy/blob/master/docs/tabpy-tools.md.

**Comment by caitlyngUR** [comment]
@0golovatyi forgive me if this is trivial but I successfully installed in the Tabpy-master folder
![Tabpy-tools](https://user-images.githubusercontent.com/49031005/56442921-676dc200-62c0-11e9-8e8b-7b5d0ffaaa9c.PNG)

I went through the the detailed post that you sent and everything seems to be in order but I am still getting the same error.

**Comment by 0golovatyi** [comment]
@caitlyngUR the main difference is you need to `import tabpy-tools` and not `tabpy-client`

**Comment by caitlyngUR** [comment]
Sorry, this is the error I am getting...

![Tabpy-tools no module](https://user-images.githubusercontent.com/49031005/56443291-ff1fe000-62c1-11e9-8897-07fe98db0a8a.PNG)

**Comment by nmannheimer** [comment]
Hi @caitlyngUR, are you running Jupyter in Anaconda? Is it possible that you are using multiple virtual environments and your Jupyter notebook is running in a different environment than the one you installed TabPy to?

**Comment by caitlyngUR** [comment]
@nmannheimer I am running Jupyter in Anaconda but I only have the one base environment.

**Comment by nmannheimer** [comment]
Is that environment also where you installed TabPy? Ie did you run the 'activate ...' command before installing TabPy?

**Comment by caitlyngUR** [comment]
@nmannheimer yes it is installed in the same base(root) environment

**Comment by 0golovatyi** [comment]
@caitlyngUR Let's try this:
- in cmd navigate to you repo root folder
- run  `SET PYTHONPATH=.\tabpy-server;.\tabpy-tools;%PYTHONPATH%`
- start python
- try you script again

**Comment by caitlyngUR** [comment]
@0golovatyi  Okay that seemed to fix the original issue but then I am getting the following error:

1st Time I ran it:
`Load failed: No module name 'sklearn'`

2nd time:
`Load failed: No module name 'keras'`

When I import both of these in the beginning of the script I don't run into any errors

**Comment by 0golovatyi** [comment]
@caitlyngUR For all the modules you use in your model you need to install them for your Python environment with `pip`, e.g. `pip install sklearn`

**Comment by caitlyngUR** [comment]
@0golovatyi I have them both installed and imported. They aren't throwing any errors throughout my script until I try and deploy the connection to TabPy server.

**Comment by 0golovatyi** [comment]
I would guess it means you run TabPy and your deployment code in different Python environments. If you stop running TabPy instance and run `pip list` you can see if the packages are installed. And if they are not you'll need either to install them or use the same Python environment for both TabPy server and tabpy-tools deployment script.

**Comment by caitlyngUR** [comment]
So all of the modules seem to installed in the same environment:

![pip list code](https://user-images.githubusercontent.com/49031005/56449675-c6483100-62ea-11e9-8e6c-24c852e28899.PNG)

![pip list keras](https://user-images.githubusercontent.com/49031005/56449677-ca744e80-62ea-11e9-95b3-8a43dc03b9c5.PNG)

![pip list scikit](https://user-images.githubusercontent.com/49031005/56449679-ccd6a880-62ea-11e9-9733-4ac2e7cb29bd.PNG)

![pip list tabpy](https://user-images.githubusercontent.com/49031005/56449680-cea06c00-62ea-11e9-9771-8471dcf60615.PNG)


But yet still getting this error:
![sklearn load failed](https://user-images.githubusercontent.com/49031005/56449683-d52ee380-62ea-11e9-8f92-64545a93778b.PNG)

**Comment by 0golovatyi** [comment]
I see console screenshot (is it Anaconda env?) and some other env (is it Jupiter or something similar)? My theory is the env you run deployment script is not the same as the env where tabpy server runs. If you run python from command line in the same console where you run pip you should be able to execute `import sklearn` to prove the package can be used in that env.

**Comment by caitlyngUR** [comment]
@0golovatyi thank you! I seemed to have fixed that problem now. The Jupyter notebook runs with no errors but when I try to use the following calculation in Tableau it throws the following error:


![Wine Suggestion Calc](https://user-images.githubusercontent.com/49031005/56505480-c8c4a980-64e9-11e9-919e-2ddd4b167861.PNG)

![Calc Errors Message](https://user-images.githubusercontent.com/49031005/56505468-c2363200-64e9-11e9-951b-98c3365799fe.PNG)

I checked the localhost:9004/endpoints where my TabPy server is running:

![9004 endopoints](https://user-images.githubusercontent.com/49031005/56505500-dbd77980-64e9-11e9-85c0-2cdd35d92b8c.PNG)


And this is the error from the command line:

![cmd error](https://user-images.githubusercontent.com/49031005/56505519-e5f97800-64e9-11e9-93af-0f7ced22d447.PNG)

I've also checked to see if my model/function from Jupyter Notebook works and it seems to be working fine:

![code check](https://user-images.githubusercontent.com/49031005/56505617-180ada00-64ea-11e9-9f23-ba1a8628c151.PNG)

**Comment by nmannheimer** [comment]
Hi @caitlyngUR when Tableau passes variables they are sent as lists to python, not single values (scalars). Looking at your code in block 20 in the last image you sent, it looks like you are expecting to receive single values in your function, so I suspect the lack of response from the endpoint is due to this. If you add index selectors to your code in your Tableau calculation, ie _arg1[0], _arg2[0], this should fix the problem.

**Comment by caitlyngUR** [comment]
@nmannheimer I tried adjusting the Tableau Calculation but I am getting the same error

**Comment by nmannheimer** [comment]
Are you able to query the endpoint from your code as described in the query section here? https://github.com/tableau/TabPy/blob/master/docs/tabpy-tools.md

**Comment by caitlyngUR** [comment]
I tried researching what this error means but it is still unclear to me

![endpoint error](https://user-images.githubusercontent.com/49031005/56513281-fc123300-64ff-11e9-9d9e-e2aa6cc00457.PNG)

**Comment by caitlyngUR** [comment]
![endpoint error](https://user-images.githubusercontent.com/49031005/56514204-af7c2700-6502-11e9-8c3f-8d33b457824f.PNG)


![endpoint error 2](https://user-images.githubusercontent.com/49031005/56514209-b30fae00-6502-11e9-9ac9-b7afb2f7a86a.PNG)

**Comment by nmannheimer** [comment]
Hi @caitlyngUR , what happens if you pass the variables individually, ie connection.query('WineQuality', 6, .3, .3,...) instead of as a single tuple query_check? Also just to make sure on the last idea, did you add [0] to all variables in your Python code? Would you mind sending a picture of how your calculation looks now in Tableau?

**Comment by caitlyngUR** [comment]
Tried this instead `connection.query('WineQuality', 6,.3,.3,2,.03,20,100,.98,3,.35,11)` but still getting the same error. 

Also, here is the calc that still returns this error "Unable to complete action
An error occurred while communicating with the External Service.
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided."

![new calc](https://user-images.githubusercontent.com/49031005/56514946-a8eeaf00-6504-11e9-8dad-9193c0323bd2.PNG)

**Comment by nmannheimer** [comment]
@caitlyngUR that's strange. Are you able to deploy and test a simple function like:

def add(x,y):
    return x + y

**Comment by caitlyngUR** [comment]
![add deploy](https://user-images.githubusercontent.com/49031005/56516645-008f1980-6509-11e9-9bc0-be5e47515f2e.PNG)

yeah that seems to work fine

**Comment by nmannheimer** [comment]
Are all of your parameters the correct types that the model is expecting for each field?

**Comment by caitlyngUR** [comment]
Yeah all of the parameters are set to datatype= float which is what each of the inputs are...
![dtypes](https://user-images.githubusercontent.com/49031005/56517742-b491a400-650b-11e9-9322-5e4e093bcb3d.PNG)

Could it be something with how I am returning the value?

So I have the model predicting what quality_bin a wine falls into (0,1,or 2). Then the function returns the inverse encoding:
![quality_check](https://user-images.githubusercontent.com/49031005/56517813-e86cc980-650b-11e9-9e38-334463e2f22d.PNG)

And for Tableau I am starting off my calculation with SCRIPT_STR.

**Comment by nmannheimer** [comment]
Hey @caitlyngUR , is it possible that you could send this jupyter notebook and data to nmannheimer@tableau.com so I can take a look?

The return type looks good, and the fact that you can deploy a simple function shows that TabPy tools is working as expected. Also, what library are you building your model with?

**Comment by nmannheimer** [comment]
Hi @caitlyngUR , looking through your notebook I believe I've identified the issue: TabPy's model deployment service uses Pickle in Python. As has been documented in another feature request (https://github.com/tableau/TabPy/issues/120), and here: https://keras.io/getting-started/faq/ Keras does not fully support pickling of models. I've tested the same code with an sklearn logistic regression model to confirm that everything else is working as expected. This is something we would like to explore in the future, but as of now models from Keras are not supported by TabPy.

**Comment by caitlyngUR** [comment]
Ahhh I see. That would solve the problem. Thank you so much for all your help.

Caitlyn Garger | Business Intelligence Analyst
C: (516) 474-8814
E: caitlyng@useready.com<mailto:caitlyng@useready.com>
[USEReady]<http://t.sidekickopen69.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1p1FbvW1qMLx24WJ7JnW3MPft-56dGvtf7LtlY402?t=http://www.useready.com/&si=6407247951429632&pi=8004520d-daf8-44d0-cb4d-ad5897aab361>

FAST TRACKING BUSINESS PERFORMANCE WITH
ADVANCED BI, DATA AND SECURITY SOLUTIONS
Follow Us:  Twitter<http://t.sidekickopen69.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1p1FbvW1qMLx24WJ7JnW3MPft-56dGvtf7LtlY402?t=https%3A%2F%2Ftwitter.com%2FUSEReadyInc&si=6407247951429632&pi=8004520d-daf8-44d0-cb4d-ad5897aab361> | Facebook<http://www.facebook.com/usereadyinc> |  LinkedIn<http://t.sidekickopen69.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1p1FbvW1qMLx24WJ7JnW3MPft-56dGvtf7LtlY402?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fuseready&si=6407247951429632&pi=8004520d-daf8-44d0-cb4d-ad5897aab361>

**Comment by sahil0094** [comment]
> @caitlyngUR Let's try this:
> 
> * in cmd navigate to you repo root folder
> * run  `SET PYTHONPATH=.\tabpy-server;.\tabpy-tools;%PYTHONPATH%`
> * start python
> * try you script again

what is repo root folder?Pls help

**Comment by 0golovatyi** [comment]
@sahil0094 There is no repo folder unless you are developing for TabPy. If your scenario is using TabPy for Python script execution during Data Prep or Tableau viz calculation follow these instructions to install and configure TabPy - https://tableau.github.io/TabPy/
