### ISSUE TITLE
TabPy server startup

### ISSUE THREAD

**Issue by raiello801** [tableau/TabPy#270]
I successfully installed tabpy using anaconda prompt.  When I attempt to run the startup.bat file in the Anaconda\Lib\site-packages\tabpy_server subdirectory, I get the following error msg:
AttributeErrror: module 'tornado.web' has no attribute 'asynchronous'

thank you for any assistance you can provide,
Rob

**Comment by nmannheimer** [comment]
Hi @raiello801 , how did you install TabPy? Running with startup.bat sounds like it came from the older version in pip (which is available for legacy reasons).  This is the link to the current setup instructions: https://github.com/tableau/TabPy/blob/master/docs/server-startup.md

**Comment by raiello801** [comment]
Thanks for the quick response! I originally downloaded it using pip in the Anaconda command prompt screen.  Then I went to github and downloaded the zip file and extracted it to the anaconda subdirectory.  when i run startup.cmd I get the above error message.  Is it because the startup.cmd file is in the anaconda subdirectory and not further down in the tabpy_server subdirectory?
Screenshot of error msg:
![image](https://user-images.githubusercontent.com/49923605/56679631-88089400-6693-11e9-8a67-45b99dd4685d.png)

**Comment by 0golovatyi** [comment]
@raiello801 TabPy needs Tornado to be of version 5, not 6 which you probably have on your env. You can confirm it with `pip list` command. If it is the case you can run `pip install Tornado==5.1.1` to install the version TabPy uses.

**Comment by raiello801** [comment]
Excellent Ogolovatyi, that was it!
Thanks much!
Rob
