### ISSUE TITLE
How to translate python script into TabPy

### ISSUE THREAD

**Issue by knozaw** [tableau/TabPy#272]
Hello,

I've received an Invalid Syntax Error in tableau calculation:
![image](https://user-images.githubusercontent.com/23086503/56763024-252c0100-6756-11e9-981b-e12e82030846.png)

When I looked at the tableau calculation, the line 8 is:
`print([p for p in nx.shortest_path(G,source=[Source Parameter],target=[Target Parameter])])`
![image](https://user-images.githubusercontent.com/23086503/56763105-5c9aad80-6756-11e9-9359-81ef6c283cd2.png)

Here is the original script written in JupyterLab:
![image](https://user-images.githubusercontent.com/23086503/56763397-2e699d80-6757-11e9-87bc-c5c0f1e50198.png)

In tableau calculation, I've updated the source and target value to be dynamically changed using [Source Parameter] and [Target Parameter].

The [Source Parameter] uses the field list "From".
![image](https://user-images.githubusercontent.com/23086503/56763649-c36c9680-6757-11e9-88df-a73544c6d77c.png)

The [Target Parameter] uses the field list "To".
![image](https://user-images.githubusercontent.com/23086503/56763711-e26b2880-6757-11e9-89f8-f7c424427ab2.png)

Does anyone know how to translate the python script for tableau calculation?

Sincerely,
knozawa

**Comment by 0golovatyi** [comment]
@knozaw As specified in the documentation at https://github.com/tableau/TabPy/blob/master/docs/TableauConfiguration.md#anatomy-of-a-python-calculation you need to use positional arguments in your Python script as `_arg1`, `_arg2`, etc. When the script is passed to TabPy there is no notion of fields, columns or anything like that.

**Comment by nmannheimer** [comment]
@knozaw this video should also help answer some of your questions: https://youtu.be/nRtOMTnBz_Y

**Comment by knozaw** [comment]
Thank you, @0golovatyi  and @nmannheimer.

I looked at those documents and YouTube video.  It helped me writing a script in tableau.
![image](https://user-images.githubusercontent.com/23086503/56973826-7c4d1f80-6b22-11e9-9dca-63967c5f8064.png)

However, exactly the same code in Jupyter gives me "True" output, but TabPy gives me an error message.
![image](https://user-images.githubusercontent.com/23086503/56973495-cd104880-6b21-11e9-9133-e5c7ea5b8405.png)

![image](https://user-images.githubusercontent.com/23086503/56973618-0fd22080-6b22-11e9-8aaf-e33be5aa2539.png)

Did anyone had the similar issue?

Sincerely,
knozawa

**Comment by 0golovatyi** [comment]
My guess is `pd.read_csv` created different frame then `pd.DataFrame`.

**Comment by nmannheimer** [comment]
@knozaw your script needs to have a return value, so try adding:
return nx.has_path(....

**Comment by knozaw** [comment]
Thank you, @0golovatyi and @nmannheimer.

I've added return in front of the nx.has_path
![image](https://user-images.githubusercontent.com/23086503/56978661-deab1d80-6b2c-11e9-8b79-9e550ce14650.png)

However, I received the same issue:
![image](https://user-images.githubusercontent.com/23086503/56978897-685aeb00-6b2d-11e9-882b-6dbcd9be06f8.png)

**Comment by nmannheimer** [comment]
@knozaw it looks like your parameter you are passing is a string, but in your jupyter code, you are looking for integers. What happens if you convert the parameter type in Tableau to integer, or convert the strings in your python code to ints?

**Comment by WillAyd** [comment]
Instead of using `os.chdir` does it work if you specify the full path to the file in `pd.read_csv`? The error is getting raised by networkx and if it works on a Jupiter notebook but not on Tableau server I would guess that `os.chdir` isn't doing what you expect it to on TabPy

**Comment by 0golovatyi** [comment]
@knozaw Has the issue been resolved or you are still experiencing it?

**Comment by knozaw** [comment]
Hello,

Sorry.  I hadn't had a chance to test converting the parameter type and pd.read_csv yet.
I'll get back to this once as soon as possible.

Thank you all for your kind help!

Sincerely,
knozawa

**Comment by knozaw** [comment]
@nmannheimer - I tested converting str to int in tableau, but it didn't work either.

@WillAyd - pd.read_csv worked on jupyter. 

When I tried to filter by the calculation in tableau, I received this error message:
![image](https://user-images.githubusercontent.com/23086503/58442581-20ce6d00-80a1-11e9-89a7-d6a77fa4ecda.png)

It seems like `pandas.DataFrame` is not working correctly in tableau.

Sincerely,
knozawa

**Comment by WillAyd** [comment]
> @WillAyd - pd.read_csv worked on jupyter.

Did you specify a full path to the file in read_csv in both Jupyter and TabPy? Using `os.chdir` may seemingly be fragile on the TabPy side since you are relying on the server to actually execute that and update the current directory, which it might not guarantee execution of. If you use an absolute path in TabPy you would remove that confounding factor

**Comment by knozaw** [comment]
Hi @WillAyd,

No. At first, I specified the full path using the `os.chdir` in the Jupyter Lab.  But next, I uploaded the csv file into the Jupyter Lab and used the `pd.read_csv("ToFrom.txt", delimiter = '\t')` to read the file on the Jupyter Lab.  Both ways worked on Jupyter Lab.

I didn't use the full path on TabPy.  I read the data from Tableau data source using `df = pd.DataFrame({'source':_arg1,'target':_arg2})`.
![image](https://user-images.githubusercontent.com/23086503/58496108-09899100-812e-11e9-94cf-21891896d506.png)

According to the command prompt, I'm getting 500 post error (internal server error) message.
![image](https://user-images.githubusercontent.com/23086503/58495937-98e27480-812d-11e9-9a8a-78e989ab3a02.png)

Sincerely,
knozawa

**Comment by WillAyd** [comment]
Are you sure your dtypes are consistent across both sources? What is the output of `df.dtypes` in Jupyter?

**Comment by knozaw** [comment]
Hi @WillAyd,

Yes, I believe so.

**os.char**
![image](https://user-images.githubusercontent.com/23086503/58500680-7e14fd80-8137-11e9-9dc1-8942a73c3cc9.png)

**pd.read_csv**
![image](https://user-images.githubusercontent.com/23086503/58500603-5cb41180-8137-11e9-813c-8f68adce3115.png)

**Tableau**
![image](https://user-images.githubusercontent.com/23086503/58500938-1f03b880-8138-11e9-9876-20a7fa62b0c5.png)

The data type is integers for all data sources. 

Sincerely,
knozawa

**Comment by WillAyd** [comment]
In Tableau your data type is string. Does changing that to a number resolve?
