### ISSUE TITLE
Make Endpoints that Should Fail Actually Fail

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#273]
As a follow up to #266 there are a couple endpoints which should be throwing an exception for invalid requests but actually don't (any marked as expectedFailure in that PR).

This issue is a follow up to see what's going on and actually trigger exceptions as required

**Comment by 0golovatyi** [comment]
Fix for the tests is in PR https://github.com/tableau/TabPy/pull/330

**Comment by 0golovatyi** [comment]
Fixed in https://github.com/tableau/TabPy/releases/tag/0.8
