### ISSUE TITLE
Remove platform specify logic from deploying models 

### ISSUE THREAD

**Issue by sbabayan** [tableau/TabPy#289]
Both in integ_test_base.py and in models/setup.py we check for windows or mac to specify which python to use when running the script files (python3 vs python).

**Comment by 0golovatyi** [comment]
I spent some time looking at other Python projects and it seems like what we do is the same thing other projects do. Unless we start using some library which hides the specifics I think we are good to close this issue.

**Comment by johng42** [comment]
Oddly, I spent this morning looking at the same thing.  Until debian based distros update their python environments they ship to not include the '3' (or '4' or whatever in the future) there is no other way I could find to work around this.

**Comment by 0golovatyi** [comment]
Closing this as what we have in TabPy code is the same people do in other Python projects.
