### ISSUE TITLE
Can TabPy be used for a remote python on a server ?

### ISSUE THREAD

**Issue by cailiangliang765** [tableau/TabPy#292]
**Environment information:**
 - OS: [Windows, Linux, Mac] and version
 - Python version: [e.g. 3.6.5]
 - TabPy release: [e.g. 0.4.1]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior: what commands to run, what files to modify, where to look for an error.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 0golovatyi** [comment]
@cailiangliang765 TabPy is an HTTP server which allows evaluating Python scripts, more details here - https://tableau.github.io/TabPy/.

Could you clarify why your question is marked as a bug? Also, bug details seem like an unmodified issue template - could you provide more details about the bug?

**Comment by 0golovatyi** [comment]
@cailiangliang765 any comments?

**Comment by cailiangliang765** [comment]
> @cailiangliang765 any comments?

I still can not connect the remote tabpy on my server. it seems to me that rserver was okay. The user and password fill form was grey and can not been filled.

**Comment by 0golovatyi** [comment]
@cailiangliang765 To connect to TabPy server you need "TabPy/External API" connection. For Rserve use "Rserve" connection. More details here - https://onlinehelp.tableau.com/current/pro/desktop/en-us/r_connection_manage.htm.

**Comment by 0golovatyi** [comment]
@cailiangliang765 Did you figure this out?
