### ISSUE TITLE
State file path is validated using regex.

### ISSUE THREAD

**Issue by jnegara** [tableau/TabPy#308]
In `tabpy-server/tabpy_server/handlers/management_handler.py `, TabPy's state file path is validated using regex.

For example:
```
            src_path = (request_data['src_path'] if 'src_path' in request_data
                        else None)
            target_path = get_query_object_path(
                self.settings[SettingsParameters.StateFilePath], name, version)
            self.logger.log(logging.DEBUG,
                            f'Checking source path {src_path}...')
            _path_checker = _compile(r'^[\\\:a-zA-Z0-9-_~\s/\.]+$')
            # copy from staging
            if src_path:
                if not isinstance(request_data['src_path'], str):
                    raise gen.Return("src_path must be a string.")
                if not _path_checker.match(src_path):
                    raise gen.Return(
                        'Endpoint source path name can only contain: '
                        'a-z, A-Z, 0-9, underscore, hyphens and spaces.')
```

Issues:
- The validation is redundant. Path validation is and should be done using Python's native file handling tools.
- The validation is proven risky. It has already caused bugs in which we reject valid paths, such as the one addressed by PRs #305 and #306.

Fix:
- Remove regex path validation throughout TabPy code base, and test where applicable.

**Comment by 0golovatyi** [comment]
Absolutely agree. Even with current code models deployment won't work for mounted network drives, paths with non-Latin characters and UNC paths. We should get rid of the validation.

**Comment by KobaKhit** [comment]
Hello. I saw this issue and decided to give it a try. I removed the path validation step and submitted a pull request #365 . I ran unit tests (`pytest tests/unit`) and they completed without errors. Is it what you were looking for? Do you think additional unit tests are required? Thanks.

**Comment by 0golovatyi** [comment]
There's at least one integrations test which fails with the change - https://travis-ci.org/tableau/TabPy/builds/617346945?utm_source=github_status&utm_medium=notification. You can run all the tests locally with just `pytest` command.

**Comment by KobaKhit** [comment]
@0golovatyi yep I see. Thank you for following up. Having some issues setting up my development environment. Will make sure everything is setup properly and resolve the failing integration test.

**Comment by 0golovatyi** [comment]
Seems like there is no cross-platform way to check file path validity in Python other than writing additional code as https://stackoverflow.com/questions/9532499/check-whether-a-path-is-valid-in-python-without-creating-a-file-at-the-paths-ta suggests.
