### ISSUE TITLE
use TabPy for aggregate calculations?

### ISSUE THREAD

**Issue by astewart-twist** [tableau/TabPy#31]
Right now it looks like TabPy can only accept scalar inputs.  Is there any plan to have TabPy be able to compute vector calculations?

**Comment by BBeran** [comment]
TabPy does work with vectors. If you look at the criminal hotspot examples in the linked blog post below, data being passed is about 16K GPS coordinates (latitude-longitude vectors) in addition to two scalars (max allowed distance between points and min # points required to constitute a hot spot).
 
https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916
