### ISSUE TITLE
Unable To Run startup.sh on MacOS and Linux

### ISSUE THREAD

**Issue by PatrickUtz** [tableau/TabPy#314]
**Environment information:**
 - OS: MacOS Mojave & Ubuntu 18
 - Python version: 3.7

**Describe the issue**
When trying to startup a server with TabPy using the command `./startup.sh` I get the following error: `AttributeError: module 'tornado.web' has no attribute 'asynchronous'`. I have also attached a screenshot. It is worth mentioning that the same issue occurred when I tried running the server on Linux and it said that I had an incompatible version of tornado-json. Any form of help would be greatly appreciated. Thank you.  
<img width="957" alt="Screen Shot 2019-06-08 at 5 27 09 PM" src="https://user-images.githubusercontent.com/30327204/59152508-6c730600-8a13-11e9-8e15-717bc99b846c.png">
<img width="653" alt="Screen Shot 2019-06-08 at 5 31 37 PM" src="https://user-images.githubusercontent.com/30327204/59152509-6ed56000-8a13-11e9-86a6-41649fe41d77.png">

**Comment by 0golovatyi** [comment]
@PatrickUtz It looks like you env has a version of Tornado with some incompatible changes. Could you try `pip install tornado==5.1.1` and then `./startup.sh` again.

**Comment by PatrickUtz** [comment]
@0golovatyi After doing `pip install tornado==5.1.1` and `pip install jsonschema==2.3.0` it worked! Thank you.
