### ISSUE TITLE
Nothing happens after startup.bat

### ISSUE THREAD

**Issue by ttlenguy** [tableau/TabPy#315]
I have downloaded anaconda and followed the steps in https://community.tableau.com/docs/DOC-18235 to get up TabPy (though i wasn't able to use the Anaconda Prompt) and then created a virtual environment as recommended here: https://github.com/tableau/TabPy/blob/master/docs/server-startup.md

When try to run startup.bat, nothing happens. I don't even get an error message. Did I do something wrong?

![image](https://user-images.githubusercontent.com/11530371/59378231-181c9e80-8d11-11e9-9115-57e78830f91d.png)
 
Thank you in advance

**Comment by nmannheimer** [comment]
Hi @ttlenguy,

This is an older version of TabPy. Please follow the current install instructions here: https://github.com/tableau/TabPy/blob/master/docs/server-startup.md

**Comment by ttlenguy** [comment]
> Hi @ttlenguy,
> 
> This is an older version of TabPy. Please follow the current install instructions here: https://github.com/tableau/TabPy/blob/master/docs/server-startup.md

Thank you! I didn't realize I had an older version.
