### ISSUE TITLE
TabPy failed to work on server

### ISSUE THREAD

**Issue by odiwan1991** [tableau/TabPy#318]
**Environment information:**
 - OS: [Windows 10] 
 - Python version: [e.g. 3.6.5]
 - TabPy release: [e.g. 0.5]

**Describe the issue**
All certificates are declared and valid. Tableau Server uses the same certificates. 

**Current Tableau Server config:**
vizqlserver.extsvc.host
http://127.0.0.1
vizqlserver.extsvc.port
9004
vizqlserver.allow_insecure_scripts
true
vizqlserver.script.disabled
true

**Expected behavior**
On local machine everything is working fine. I think that issue is related to SSL. 

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/52253765/60200827-8dc75500-984f-11e9-8242-0ce1da1b1258.png)

![Screenshot_2](https://user-images.githubusercontent.com/52253765/60200846-9a4bad80-984f-11e9-80c2-515bc3755021.png)

Thank you a lot for you attention!

**Comment by nmannheimer** [comment]
Hey @odiwan1991,

One thing to try right away, the vizqlserver.script.disabled parameter is a little confusing, but the actual setting to **allow** external connection is _false_ : 

https://onlinehelp.tableau.com/current/server-linux/en-us/cli_security_tsm.htm#vizql-extsvc-ssl-list

"Disable scripts originating from the external service from running on Tableau Server. Default is true. To allow scripts from the external service to run on Tableau Server, set to false."

**Comment by odiwan1991** [comment]
hi @nmannheimer 
Thanks for prompt response. I've changed settings accordingly however got the same error.

**Comment by nmannheimer** [comment]
Are you seeing pings from Tableau Server in the CLI where you're running TabPy? ie failed connection attempts? From your config, it looks like you put the endpoint as http, but if you've configured SSL certs you'll want to make that https://127.0.0.1

**Comment by odiwan1991** [comment]
@nmannheimer sounds reasonable, I didn't note it. Can you please clarify how to make this changes?

**Comment by nmannheimer** [comment]
just set vizqlserver.extsvc.host to
https://127.0.0.1

**Comment by nmannheimer** [comment]
@odiwan1991 can you also let me know which version of Server you are using?

**Comment by odiwan1991** [comment]
Hi!
Server version is Tableau Server Version: 2019.1.2.

**Comment by odiwan1991** [comment]
@nmannheimer i've changed  vizqlserver.extsvc.host to https://127.0.0.1 and got the following error 
![Screenshot_1](https://user-images.githubusercontent.com/52253765/60283394-b57ef180-9911-11e9-8f04-42ba5785ed46.png)

**Comment by nmannheimer** [comment]
Are you seeing anything on the TabPy command line when you are trying to connect?

**Comment by odiwan1991** [comment]
No

**Comment by odiwan1991** [comment]
BTW i've upgraded TapPy to latest version

**Comment by nmannheimer** [comment]
My apologies, I missed this when you shared your Server version. Secure connection for TabPy was added in Tableau Server version 2019.2. Secure Connection for RServe was added in 2019.1, which is why the capability exists to set those parameters in your 2019.1 version of Tableau Server. To communicate securely with TabPy, you will need to upgrade your Tableau Server to 2019.2.

**Comment by odiwan1991** [comment]
Thank you! I'll try it and get back with results ASAP

**Comment by 0golovatyi** [comment]
@odiwan1991 Are you still experiencing the issue or it has been resolved?

**Comment by DimaVS1991** [comment]
Hi @0golovatyi  and @nmannheimer. Sorry for keeping you with no feedback for so long. I was on holidays. 

Unfortunately I am experiencing this issue. 
I have upgraded Tableau Server to 2019.2.2. 
vizqlserver.allow_insecure_scripts is set to true
vizqlserver.script.disabled is set tot true

All certificates are declared in default.conf file

However i got this reposnse from TabPy server: [WARNING] (iostream.py:iostream:1518): SSL Error on 816 ('127.0.0.1', 63148): [SSL: HTTP_REQUEST] http request (_ssl.c:833)

And this from Tableau Server:
![image](https://user-images.githubusercontent.com/47948357/64100404-31634300-cd74-11e9-9277-23e00a3af7b9.png)

Can you please help me to figure this out?

**Comment by jnegara** [comment]
@DimaVS1991 It looks like you've configured a plaintext connection in Tableau.
Make sure you've checked "require SSL", provided a certificate, and that your host name begins with "https://".
