### ISSUE TITLE
Error connecting to endpoint.

### ISSUE THREAD

**Issue by GirlMeetsData** [tableau/TabPy#32]
Hello,

I commented on [this article](https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916#comment-56205) you posted but realized this is a better place to post this issue I'm facing.

I'm attempting to reproduce your ML code and breast cancer example in Tableau. I used your Jupyter notebook to run the code and deploy it to the TabPy client. I then created the parameters and calculation you used in Tableau. Once I tried to use it, I got this error:

Tableau Error: The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

I checked the Jupyter notebook again to ensure I didn't miss any error messages and each step ran properly (aside from warnings about deprecated things). In fact, I when running the code again I saw this error:

RuntimeError: An endpoint with that name ('DiagnosticsDemo') already exists. Use 'override = True' to force update an existing endpoint.

Do you have any recommendations on how to troubleshoot this or any suspicions as to why I wouldn't be able to to communicate with the endpoint? I am running TabPy successfully and verified I'm successfully connected. 

Thanks,
Brit

**Comment by BBeran** [comment]
Hi Brit,
Is this happening if you download the original Tableau workbook that's part of the blog post as well or only in the version you created? It is hard to tell by just the description. Maybe incorrect set of arguments were provided or they have different data types or...

If you'd like to see more detailed error messages in the console, you can update logging.ERROR you see in the source code of your local install to logging.INFO which would give you the stack trace.

https://github.com/tableau/TabPy/search?utf8=%E2%9C%93&q=logging&type=

Thanks,

Bora

**Comment by GirlMeetsData** [comment]
Thanks, Bora! I'll look into your suggestions today.

When I tried to open the workbook [via the URL](http://54.186.231.117/#/site/Python/views/TabPyPublishedModel/BreastCancer) in the article it returned a Tableau Server error so I wasn't able to download it thus I created the workbook from scratch. I'll look into your suggestions. 

Would you happen to have a shareable version of the workbook I can compare against?

Brit

**Comment by BBeran** [comment]
Should work now. It looks like somebody restarted the machine then closed TabPy window (it was set to autostart on boot).

**Comment by GirlMeetsData** [comment]
D'oh - I feel stupid now...when I wrote the calc I called DiagnosticDemo not Diagnostic**s**Demo. Oy, thanks for your suggestions though and the workbook!

**Comment by BBeran** [comment]
I am glad it worked out.
