### ISSUE TITLE
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

### ISSUE THREAD

**Issue by dive76** [tableau/TabPy#323]
Getting the following error when started:

AttributeError: module 'tornado.web' has no attribute 'asynchronous'

Looks like tornado no longer supports asynchronous.

**Comment by 0golovatyi** [comment]
@dive76 It is a known issue we have an open defect for. Try to install the previous version of Tornado with `pip install tornado==5.1.1` command, that should fix it.

**Comment by dive76** [comment]
solution to it is to start the script with sudo -H

**Comment by 0golovatyi** [comment]
@dive76 Is the issue resolved or you are still experiencing it?

**Comment by czr1803** [comment]
i had the same problem. however after pip install tornado==5.1.1, response was already satisfied. 

i then uninstalled Tornado and reinstalled  with:  conda install Tornado 
Port is listening now!
