### ISSUE TITLE
ReadTimeOut error on a tabpy query

### ISSUE THREAD

**Issue by sauravsy** [tableau/TabPy#326]
**Environment information:**
 - OS: Windows 7 
 - Python version: 3.6 
 - TabPy release: 0.2 (Running on an Ubuntu 18.01 VM)

**Describe the issue**
I'm trying to run a function that calls an API using requests.post. I have deployed the function on tabpy server and I am querying it from my Tableau Dashboard. Since I am passing 400 rows, it calls the API 400 times from the deployed function on tabpy server.
 The error message that I got after 2 mins 30 secs was:

Unable to complete action
An error occurred while communicating with the External Service.
Error processing script
ReadTimeout : HTTPConnectionPool(host='localhost', port=9004): Read timed out. (read timeout=30)

**Comment by 0golovatyi** [comment]
@sauravsy Just to clarify - you are calling a deployed model which then makes HTTP call for each value in input data?

There are 2 different places in TabPy code where timeout is used:
1. `TABPY_EVALUATE_TIMEOUT` parameter in config file specifies timeout for script evaluation.
2. For deployed models call has its own timeout (hardcoded for now) - see `evaluation_plane_handler.py`

Tableau Desktop also has its own timeout setting.

First, you need to confirm which piece of code is timing out. See if there's anything in TabPy logs can be useful.
