### ISSUE TITLE
Error - Python code

### ISSUE THREAD

**Issue by HenryBRA** [tableau/TabPy#33]
Hi, 

I was able to install and connect tableau with TabPy Server, but when I tried to create a calculated field with python code, it returned an error:
TypeError : unsupported operand type(s) for +: 'float' and 'NoneType'

Could you give me a help on what is wrong and how can I troubleshoot this kind of error?

Thanks in advance.
I'm sending the images of the calculated field and the error.

![image](https://cloud.githubusercontent.com/assets/28275561/25596512/dc02606e-2e9f-11e7-808d-514c93a12d98.png)

![image](https://cloud.githubusercontent.com/assets/28275561/25596528/f07075ae-2e9f-11e7-8c44-3657c119be88.png)

**Comment by BBeran** [comment]
First can you try removing NULLs if there are any in the view? Then can you right click on the Corr pill in the view, select edit table calculation and then in the dialog, select specific dimensions and make sure Customer Name box is checked and see if that fixes the problem?

**Comment by HenryBRA** [comment]
Hi BBeran,
Thanks for the quick answer
I changed the table calculation configurations and it worked, thank you
I'm studying and looking for examples about tableau and python
Is there any material that you recommend?

**Comment by BBeran** [comment]
You can find some here
https://github.com/tableau/TabPy/blob/master/TableauConfiguration.md
https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916

**Comment by HenryBRA** [comment]
Thanks for the links
The first one I use it to take some examples 
The second one, when I tried to open the workbooks, it give me an error, probably because I didn't had Tabpy running.

Thanks Again.
