### ISSUE TITLE
No Module Named 'tabpy_server.app' when using user_management

### ISSUE THREAD

**Issue by jtweeder** [tableau/TabPy#331]
**Environment information:**
 - OS: Windows Server 2016
 - Python version: 3.7.3
 - TabPy release: 0.6.1

**Describe the issue**
Install tabpy server and works as intended, but was looking to add authentication with user-name and passwords.  Upon running the user-management tool it errors that it cannot find 'tabpy_server.app' module.  Errors at line 10.

**To Reproduce**
From Tabpy 0.6.1 directory:
`python utils/user_management.py -h`

**Expected behavior**
User-management tool to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/31365056/63046865-dc30c180-be98-11e9-90ca-c9d3180add3e.png)

**Additional context**
Tried reinstall tapby-server and dependencies with no fix.

**Comment by 0golovatyi** [comment]
@jtweeder before running `utils/user_management.py` did you run `utils/set_env.cmd`?

**Comment by jtweeder** [comment]
I did not.  Sorry I was reading the Configuration instructions one step at a time and did not see that instruction come up yet.

Seems to work after running `utils/set_env.cmd`

Thank you for the quick response, and sorry I did not read two more lines down in the instructions.
