### ISSUE TITLE
TabPy Issue Report regards return value

### ISSUE THREAD

**Issue by nikomataa** [tableau/TabPy#333]
```
SCRIPT_REAL("
import pandas as pd
import numpy as np

y = np.array(_arg1)

return y.std()
",
SUM([Total Ticket]))
```

I want to try to show standard deviation value from the measure but got invalid JSON. Can someone explain me how does the tabpy or the script work ? thank you

**Comment by 0golovatyi** [comment]
@nikomataa Have you checked https://github.com/tableau/TabPy/blob/master/docs/TableauConfiguration.md?

**Comment by nmannheimer** [comment]
@nikomataa if your objective is just to calculate standard deviation, I would also advise using Tableau's native calculations: STDEV() and WINDOW_STDEV()

**Comment by 0golovatyi** [comment]
@nikomataa Do you still experiencing the issue?
