### ISSUE TITLE
Incorrect Documentation in Regards to Config File Location

### ISSUE THREAD

**Issue by jtweeder** [tableau/TabPy#334]
**Environment information:**
 - OS: Microsoft Server 2016
 - Python version: 3.7.1
 - TabPy release: 0.6.1

**Describe the issue**
Relative path for config file in [documentation](https://github.com/tableau/TabPy/blob/master/docs/server-startup.md#command-line-arguments-for-windows) appears incorrect.  

**To Reproduce**
Per documentation I placed a custom config file at: 
`%TABPY_ROOT%\tabpy-server\tabpy_server\myconfig.conf`

When starting tabpy with `startup.cmd myconfig.conf` i get an error that it cannot find the custom config file and is reverting to default.

**Additional context**
As troubleshooting I moved the location of the myconfig.conf file and moved it to the `%TABPY_ROOT%` folder.  When I run `startup.cmd myconfig.conf` with the custom file in `%TABPY_ROOT%` it finds the file and starts without problems, but this seems contrary to what is the current docs.

**Comment by 0golovatyi** [comment]
@jtweeder You are right - documentation seems to be incorrect :(

**Comment by jtweeder** [comment]
I can edit those docs, as that is a relatively easy fix I believe.  

Thanks for the reply, I was wanting to make sure I was reading the information correctly and it was truly incorrect before suggesting a change, as on a recent occasion my issue was caused by me and not the docs :)
