### ISSUE TITLE
How can one shutdown the tabpy server?

### ISSUE THREAD

**Issue by PyDataBlog** [tableau/TabPy#344]
**Environment information:**
 - OS: Windows 10
 - Python version: 3.7.4
 - TabPy release: 0.8.6

**Describe the issue**
Usually a 'Ctrl+C' command shuts down terminal applications but it doesn't seem to work with tabpy. How can one shut down the tabpy server?

**To Reproduce**
Launch tabpy server in the command line with `tabpy`

**Expected behavior**
Shutdown of the servier

**Comment by 0golovatyi** [comment]
@PyDataBlog Did you try Ctrl+Break?

**Comment by PyDataBlog** [comment]
> @PyDataBlog Did you try Ctrl+Break?

Ctrl+Break shuts down the server.

**Comment by ChrissCod** [comment]
One question in the same topic, how about closing the tabby server in Mac OS?

**Comment by 0golovatyi** [comment]
@ChrissCod You mean TabPy? You can use Ctrl+C.
