### ISSUE TITLE
RuntimeError: LoadFailed: 'Load failed: code() takes at most 14 arguments (15 given)

### ISSUE THREAD

**Issue by GirlMeetsData** [tableau/TabPy#35]
Hello -

I'm attempting to deploy a model but I am receiving the below error message. What I'm trying to do is call the model from Tableau, use a string parameter to pass new text, and return the spam prediction based on the string input. I tested my function within my notebook and it's working as expected so I'm trying to understand the error raised by the # of arguments.

My notebook is here: https://github.com/GirlMeetsData/data_analysis/blob/master/TabPy%20Example%20-%20Naive%20Bayes%20to%20Detect%20Spam.ipynb

Error Message:

/Users/brit.cava/anaconda/envs/snakes/lib/python3.5/site-packages/tabpy_client/client.py in deploy(self, name, obj, description, schema, override)
    330             self._service.set_endpoint(_Endpoint(**obj))
    331 
--> 332         self._wait_for_endpoint_deployment(obj['name'], obj['version'])
    333 
    334     def _gen_endpoint(self, name, obj, description, version=1, schema=[]):

/Users/brit.cava/anaconda/envs/snakes/lib/python3.5/site-packages/tabpy_client/client.py in _wait_for_endpoint_deployment(self, endpoint_name, version, interval)
    451                 if ep['status']  == 'LoadFailed':
    452                     raise RuntimeError("LoadFailed: %r" % (
--> 453                         ep['last_error'],
    454                     ))
    455 

**RuntimeError: LoadFailed: 'Load failed: code() takes at most 14 arguments (15 given)**'

Thanks!
Brit

**Comment by BBeran** [comment]
Hi Brit,
Can you make sure your TabPy server and IPython workbook you're using have the same version of Python? The piece of code that is triggered here takes different number of arguments in Python 2.x vs 3.x.  That is my first guess on why this might be happening. If that's not the issue, I will dig deeper.

Thanks,

Bora

**Comment by GirlMeetsData** [comment]
That was part of the issue - thank you!

When it comes to passing data from Tableau to the function it doesn't work and I'm wondering if it has to do with data types. The use case is simple - pass text via a parameter in Tableau to the model and return 0 or 1 (cast as a string).

In my [function](https://github.com/GirlMeetsData/data_analysis/blob/master/Spam%2BPredictor.ipynb), I originally returned a numpy array while in Tableau I was using SCRIPT_STR. I thought perhaps that since it could take multiple strings and return a list of results that I could simply return 1 since I'm passing one argument in Tableau. I tried so resolve that and tested it in my notebook to ensure the data I was returning to Tableau was a string.

<img width="924" alt="screen shot 2017-05-07 at 9 59 32 am" src="https://cloud.githubusercontent.com/assets/6933012/25783141/e697008c-330b-11e7-88d5-53e8ac8556a2.png">

In Tableau, my calculation is:

<img width="679" alt="screen shot 2017-05-07 at 10 03 07 am" src="https://cloud.githubusercontent.com/assets/6933012/25783166/69c07f60-330c-11e7-81fe-e768f84bbc9f.png">

The parameter:

<img width="570" alt="screen shot 2017-05-07 at 10 00 58 am" src="https://cloud.githubusercontent.com/assets/6933012/25783154/16c4b6b4-330c-11e7-8e7d-4b31d2d959ce.png">

The error it returns:

<img width="534" alt="screen shot 2017-05-07 at 9 58 43 am" src="https://cloud.githubusercontent.com/assets/6933012/25783137/d6eace84-330b-11e7-8890-c38dfc705145.png">

Is there something I am missing with how the data is passed in the string parameter in Tableau? Would it not be read as a string by the function?

I've verified that TabPy is running and the function endpoint exist. Any recommendations?

Workbook: [https://github.com/GirlMeetsData/data_analysis/blob/master/SpamPredictor.twbx](url)

**Comment by BBeran** [comment]
Hi Brit,
Tableau passes the objects as Python lists. Does it work when you delete the  [ ] around testing_data object in your predictSpam function?

Thanks,

Bora

**Comment by GirlMeetsData** [comment]
Yes!!! Bora, thanks for your patience 👍

**Comment by BBeran** [comment]
I am glad it worked.
