### ISSUE TITLE
Error when connecting in tableau desktop

### ISSUE THREAD

**Issue by jesspencer** [tableau/TabPy#351]
**Environment information:**
 - OS: Windows 10
 - Python version:: 3.6.5
 - TabPy release: latest one on github

**Describe the issue**
An error occurred while communicating with the external service. Tableau is unable to connect to the service. Verify that the service is running and that you have access privileges.

**To Reproduce**
Steps to reproduce the behavior: what commands to run, what files to modify, where to look for an error.

**Expected behavior**

**Screenshots**

**Additional context**
pip virtual env successfully setup, pip install tabpy, pip install tapby-server, closed tableau desktop and tested the connection when I get error message
![Capture](https://user-images.githubusercontent.com/39749248/66722419-3091e800-eddb-11e9-959f-7e712efda722.JPG)

**Comment by 0golovatyi** [comment]
@jesspencer You don't need to install tabpy-server anymore. The commands should be
```
pip install tabpy
tabpy
```
After TabPy started you should be able to connect to it with the machine name and port (by default port is 9004, you can find it in TabPy log file or console output). To confirm you can reach running instance try `http://<machine name>:9004/info` in a web browser.

**Comment by jesspencer** [comment]
Hi, 
Thanks for following up. I am still not able to run tabpy. 

So far, 
1) I have created a virtual environment and activated it  (using my anaconda prompt ) 
2) installed tabpy using pip install tabpy tabpy
3) check that the server is running in the browser gives me nothing 
4) testing the connection in tableau I get the error “error occurred while communicating ... verify that the service is running and that you have access privileges “

Best, 

Jess

**Comment by 0golovatyi** [comment]
So from what you mentioned for 3), I understand it either server was not started or it is running on some different port. When you start TabPy with `tabpy` command you should see some output for the server with the parameter information. There will be a line for the port number (usually the very first one). Something like this:
```bash
C:\Temp>tabpy
**2019-10-22,11:07:42 [DEBUG] (app.py:app:215): Parameter port set to "9004" from default value**
```

Confirm the port number first and try `http://localhost:<portnumber>/info` on the same machine.

**Comment by 0golovatyi** [comment]
@jesspencer 
You don't need to change folders, pip installs in its packages folder regardless of where you run it from. Just follow the steps at https://github.com/tableau/TabPy/blob/master/docs/server-install.md. Do you see any output when running `tabpy` command as explained on the page?

**Comment by jesspencer** [comment]
starting tabpy gives me a permissions error; screen shot attached

**Comment by 0golovatyi** [comment]
@jesspencer I can't see any screenshot with your last comment. However `tabpy` may fail on start if you running it from a folder where you don't have create/write access, like `c:\`. Try something like `cd %TEMP%` and then `tabpy`.

**Comment by jesspencer** [comment]
@0golovatyi 

Thanks for the advice of making a tmp folder because of permissions. I made a tmp folder and tried tabpy again and it seemed to start the sever listing on port 9004. I then ran into Windows Defender firewall blocks. So, I then opened a virtual machine and did the installation. The server installed without firewall blocks. I tried going to browser and doing the http://localhost plus port number 9004 /info and I am not able to get anywhere. I try checking the connection in tableau and I receive the error that I got in the very beginning.

**Comment by 0golovatyi** [comment]
What do you see in your browser when you open `http://localhost:9004/info` on the same machine where TabPy is running?

**Comment by jesspencer** [comment]
“This page can’t be displayed error”

**Comment by nmannheimer** [comment]
Hi @jesspencer thanks for sharing these details! Does the VM where you are running TabPy have network access to the machine where you are running the browser/Tableau? Are you running the browser in the VM? It could be that the TabPy server is running in an environment that Tableau can't access over the network.

If that isn't the issue, would you be open to reaching out to me at nmannheimer@tableau.com and we could look at setting up a call?

**Comment by jesspencer** [comment]
I was able to install tabpy on another machine in which I was able to set
my own windows firewall settings; the installation worked fine. On the
other machine, I successfully confirmed tabpy server was listening by going
to http://mycomputername:9004/info where I saw the json tableau server
information. Thanks for your help; thanks for being responsive.
