### ISSUE TITLE
Installing tabpy on PyCharm IDE

### ISSUE THREAD

**Issue by JoemerRamos** [tableau/TabPy#355]
**Environment information:**
 - OS: Windows 7
 - Python version: 3.8
 - TabPy release: 0.8.9

**Describe the issue**
So I'm new to using tabpy, but a lot of the tutorials and walkthroughs online are of older versions where we use anaconda. Now, it seems like the way to do this is to install tabpy through a pip package and then to run "tabpy." My issue is running this. I don't know how to use this in PyCharm. Where do I run the tabpy command? In the terminal? When I try to do this in my project file, it says that 'tabpy is not recognized as an internal or external command.' So i'm not sure how I'm supposed to run the command. Any help would be appreciated. Thank you! 

**To Reproduce**
Installed tabpy through pycharm's project interpreter.

**Expected behavior**
I assume whats supposed to happen is a tabpy server is supposed to initiate in the terminal with the server being a localhost with a port of 9004

**Additional context**
I also tried to run the tabpy.py file in the terminal and that called the file, but I ran into errors such as this. 

![image](https://user-images.githubusercontent.com/34356209/67866343-2ff99100-faff-11e9-8697-bbc91691a645.png)

**Comment by 0golovatyi** [comment]
Run `tabpy` from the same environment where you installed the package from. In your example above that would be the command line window.

**Comment by JoemerRamos** [comment]
In this case, I installed the package in my PyCharm IDE, and I get an error 
![image](https://user-images.githubusercontent.com/34356209/67880645-6cd08280-fb15-11e9-98c7-480603788c4b.png)

**Comment by 0golovatyi** [comment]
After you installed the package with `pip install tabpy` command confirm you see it in the list of installed packages with `pip list`.

**Comment by JoemerRamos** [comment]
Yeah it shows

**Comment by JoemerRamos** [comment]
So I was able to run the tabpy command in PyCharm but I got this error 
![image](https://user-images.githubusercontent.com/34356209/67950580-3d2a8480-fbc0-11e9-9106-a3a8ba6ef3bf.png)

**Comment by JoemerRamos** [comment]
I got PyCharm to run the command but I still have this issue 
![image](https://user-images.githubusercontent.com/34356209/67950756-a14d4880-fbc0-11e9-9bb5-bea4e28c4a93.png)
