### ISSUE TITLE
Error Running TabPy

### ISSUE THREAD

**Issue by JoemerRamos** [tableau/TabPy#356]
**Environment information:**
 - OS: Windows 7
 - Python version: 3.8
 - TabPy release: Most updated

**Describe the issue**
Not sure what's wrong. I get an error when trying to initialize a local server.

**To Reproduce**
I just used pip install tabpy 

**Expected behavior**
Server should run when I use command tabpy
**Screenshots**
![image](https://user-images.githubusercontent.com/34356209/67952799-461d5500-fbc4-11e9-9763-68058f8f6197.png)

![image](https://user-images.githubusercontent.com/34356209/67952633-f9397e80-fbc3-11e9-8ee8-3252c08439f2.png)

**Additional context**

**Comment by 0golovatyi** [comment]
I just noticed something on one of your screenshots - are you using Python 3.8? We never tested for it yet (Python 3.6 or 3.7 is recommended) and it is possible not all packages are fully functional for the latest Python yet. Would it be possible for you to try Python 3.7?

**Comment by 0golovatyi** [comment]
I was able to repro the same failure with Python 3.8. Just confirming TabPy is only working with Python 3.5, 3.6 or 3.7.

**Comment by 0golovatyi** [comment]
@JoemerRamos Were you able to resolve the issue?
