### ISSUE TITLE
Tabpy-Linux - The endpoint you're trying to query did not respond.

### ISSUE THREAD

**Issue by Santhoshsekar89** [tableau/TabPy#357]
Im getting the below error when trying to run my deployed model in the tableau server via tableau desktop.

The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

Model which was deployed:
import tabpy_client
client=tabpy_client.Client("http:localhost:9004/")
def add(X,Y):
	import numpy as np
	return np.add(X,Y).tolist()
client.deploy('add',add,"add two numbers x and y",override=True)

**Comment by 0golovatyi** [comment]
@Santhoshsekar89 Could you provide more details? 

1) When the model is deployed were able to see in TabPy logs it was actually deployed successfully? Also "http:localhost:9004/" doesn't seem like a valid URL, it should be `http://localhost:9004/` instead.

2) After you deployed the model `add` to TabPy how do you call it from Tableau?

3) What error are you getting trying to call the model from Tableau?

**Comment by Santhoshsekar89** [comment]
Hi Thanks for your reply, Please find my response for your queries.

When the model is deployed were able to see in TabPy logs it was actually deployed successfully? Also "http:localhost:9004/" doesn't seem like a valid URL, it should be http://localhost:9004/ instead.
       Yes it should be http://localhost:9004/ , i have missed to type correctly over here. Please find the log when the model has deployed.
![image](https://user-images.githubusercontent.com/43480943/68245586-d00e5900-ffdc-11e9-8a0b-fd991fd04f30.png)






After you deployed the model add to TabPy how do you call it from Tableau?

       Using the below function to call from Tableau desktop.
SCRIPT_REAL("
return tabpy.query('add',_arg1,_arg2) ['response']",-SUM([Profit]),SUM([Sales]))


What error are you getting trying to call the model from Tableau?
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

**Comment by 0golovatyi** [comment]
It seems like you don't have the model deployed. If you try `http://localhost:9004/endpoints` in a browser on the machine where the TabPy is running you'll see a list of deployed models. With that, you can confirm if the model was deployed successfully.

**Comment by Santhoshsekar89** [comment]
The model has been deployed successfully. I could see under query_objects folder too. See below after running the above URL
![image](https://user-images.githubusercontent.com/43480943/68247170-da7e2200-ffdf-11e9-89d4-e0938fe1c621.png)


![image](https://user-images.githubusercontent.com/43480943/68247210-ef5ab580-ffdf-11e9-9e00-c018a9d2ed54.png)

**Comment by Santhoshsekar89** [comment]
This is the log im receiving whenever I do run the tabpy from the tableau desktop.

![image](https://user-images.githubusercontent.com/43480943/68247790-254c6980-ffe1-11e9-9c6a-f44184f8ac97.png)

**Comment by Santhoshsekar89** [comment]
Hi Someone please help here.

**Comment by Santhoshsekar89** [comment]
This is what I see currently.

![image](https://user-images.githubusercontent.com/43480943/68269228-98280580-001e-11ea-8955-4d6a6ad4f698.png)


And, this is the error im getting when connecting from tableau desktop to the model created,

![image](https://user-images.githubusercontent.com/43480943/68269248-ae35c600-001e-11ea-9c01-87211046c7a0.png)


This how I call the model from desktop.
SCRIPT_REAL("
return tabpy.query('add',_arg1,_arg2) ['response']",-SUM([Profit]),SUM([Sales]))


Hope i shared all the information required. Please help me out here. Struggling a lot to identify the issue.

**Comment by Santhoshsekar89** [comment]
Anyone can help here???

**Comment by jnegara** [comment]
Which version of TabPy are you using?

**Comment by jnegara** [comment]
It looks like the error is `"AttributeError : 'ModuleNotFoundError' object has no attribute 'message'"` which happens when you use Python 2 exception syntax in a Python 3 environment.

**Comment by Santhoshsekar89** [comment]
ohh... how we can resolve this? can you please guide me?

**Comment by 0golovatyi** [comment]
To confirm the Python version run `python -V`. You need Python 3.5, 3.6 or 3.7 (3.8 is too new still). To check TabPy version run `pip list` - you looking for 0.8 or newer.

I tried your code and dataset you used and all worked for me. However, my method deployment code looks a bit different:
```Python
import tabpy.tabpy_tools.client

client = tabpy.tabpy_tools.client.Client('http://localhost:9004/')
client.deploy('add', add, "add x to y")
```

**Comment by 0golovatyi** [comment]
BTW `tabpy_client` and `tabp_server` are old versions of TabPy, you shouldn't use them. Instead, install the latest TabPy as described here - https://github.com/tableau/TabPy/blob/master/docs/server-install.md

**Comment by Santhoshsekar89** [comment]
Hi,

Im using python 3.6 only.. see below...

/usr/local/lib/python3.6/site-packages/tabpy/tabpy_server/query_objects

BTW, I followed this only initially.. Im not able to install tabpy later after i install tabpy_server, then I able to install the tabpy successfully.

**Comment by Santhoshsekar89** [comment]
"which happens when you use Python 2 exception syntax in a Python 3 environment."  --- Can you elaborate about this and give a suggestion to fix it.

**Comment by 0golovatyi** [comment]
You don't need `tabpy_server` and `tabpy_client` if you are using the latest TabPy. Actually you want to uninstall those (run `pip uninstall` for the old versions of TabPy).

Also, notice the difference in the deployment code I posted and the code you have in your original post.

**Comment by Santhoshsekar89** [comment]
This is what I see after executing pip list

![image](https://user-images.githubusercontent.com/43480943/68332670-d06e2900-009c-11ea-8cd7-7082cdf7f59a.png)


Any idea???

**Comment by 0golovatyi** [comment]
The idea is to uninstall old `tapby-client` package and when deploying model use `tabpy` instead.

**Comment by Santhoshsekar89** [comment]
Hi,

Uninstalled tabpy_client and changed my script like below. After that, when i run tabpy getting the below error.

Error when running the module
![image](https://user-images.githubusercontent.com/43480943/68335094-715ee300-00a1-11ea-81ae-caf0281b668d.png)


Error when running tabpy:

![image](https://user-images.githubusercontent.com/43480943/68335225-af5c0700-00a1-11ea-989d-9b244937c725.png)


Modified Model:
cat
![image](https://user-images.githubusercontent.com/43480943/68335411-03ff8200-00a2-11ea-8124-2c2334edca49.png)

**Comment by 0golovatyi** [comment]
It is `tabpy.tabpy_tools.client.Client`.

**Comment by Santhoshsekar89** [comment]
cool thanks much... now I able to deploy the model after the change..

![image](https://user-images.githubusercontent.com/43480943/68336219-994f4600-00a3-11ea-8098-e366eb052304.png)

But now, when I connect from tableau desktop, im getting different error saying no module named as numpy.

![image](https://user-images.githubusercontent.com/43480943/68336321-c69bf400-00a3-11ea-8abf-e465065bcf60.png)

**Comment by Santhoshsekar89** [comment]
Hi,
Thank you so much. Everything works now after I reinstalled the numpy and pandas.

Thank you for all your help here..

**Comment by mirekphd** [comment]
> It is [now] `[import] tabpy.tabpy_tools.client.Client`.
[not `import tabpy_client` - so no need to `pip install tabpy_client` either]

I think this information of client API change needs to be posted below the official YouTube video demonstrating the use of TabPy client (they are importing `tabpy_client` in the notebook 'Loan Classifier')
https://youtu.be/nRtOMTnBz_Y?t=2984

**Comment by chpavans84** [comment]
hello 0golovatyi,
Need your help on the same issue. After following all the above steps I am getting the error 'tabpy' is not defined. I could see tabpy instance is running in 9004 and also the deployed models. Not sure if I am missing basic steps here pls advice.
![1](https://user-images.githubusercontent.com/18391932/94885500-ec43a000-04a2-11eb-9c25-7f449e8f235b.jpg)
![3](https://user-images.githubusercontent.com/18391932/94885502-eea5fa00-04a2-11eb-9374-26835afd6627.JPG)
Thanks in advance.

Regards,
Pavan

**Comment by 0golovatyi** [comment]
@chpavans84 Please open an issue with the exact steps you are following.
