### ISSUE TITLE
needed support for initialising tabpy server

### ISSUE THREAD

**Issue by Namrata9443** [tableau/TabPy#369]
**Environment information:**
 - OS: [Windows]
 - Python version: [3.6.5]
 - TabPy release: [e.g. 0.4.1]

**Describe the issue**
I am facing this error 👍 

C:\Users\DELL>pip install tabpy-server
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000076c (most recent call first):

**Screenshots**
![image](https://user-images.githubusercontent.com/58390200/69913758-234fbc00-1462-11ea-8e1c-3b0d52a2acfb.png)

**Comment by 0golovatyi** [comment]
@Namrata9443 Installation instructions for TabPy are here - https://github.com/tableau/TabPy/blob/master/docs/server-install.md.
