### ISSUE TITLE
TableauException: An error occurred while communicating with the external service

### ISSUE THREAD

**Issue by venkataanumula** [tableau/TabPy#37]
Hi
I am able to use tabpy successfully through the tableau desktop. but when I am trying to use it as an external service for the server I am getting an error that the tableau could not connect to the external service. 
[tabpy2.txt](https://github.com/tableau/TabPy/files/1052216/tabpy2.txt)
![tabpy3 1](https://cloud.githubusercontent.com/assets/29203988/26787443/00dac0cc-49d8-11e7-8483-4904620adfd1.PNG)
![tabpy1 1](https://cloud.githubusercontent.com/assets/29203988/26787444/00db1126-49d8-11e7-86b5-70b3d801cc86.PNG)

your help is very much appreciated.

Thanks

**Comment by BBeran** [comment]
Did you try the following for the setup on Tableau server? 

tabadmin stop
tabadmin set vizqlserver.extsvc.host <ip address or host name of the machine hosting TabPy>
tabadmin set vizqlserver.extsvc.port <port for TabPy>
tabadmin configure
tabadmin start

**Comment by venkataanumula** [comment]
yes . I tried that again. but still the same error.

![image](https://cloud.githubusercontent.com/assets/29203988/26796136/55459fce-49f6-11e7-8c19-4c41e15ec67e.png)

**Comment by venkataanumula** [comment]
Yes, I tried that again but still the same error
![image](https://cloud.githubusercontent.com/assets/29203988/26796321/07aeab10-49f7-11e7-8a76-f3e0187a92e2.png)

**Comment by BBeran** [comment]
It might be having problem resolving the name localhost.

Have you tried http://localhost  OR 127.0.0.1 when configuring on the server and see if it solves the problem?

**Comment by venkataanumula** [comment]
I tired both http://localhost and 127.0.0.1 . It did not work . But, it works when i configure with the ip address of the box where the tableau server is installed.

**Comment by BBeran** [comment]
If those names aren't resolving but IP address of the server is working, it is likely an issue in the hosts file
https://en.wikipedia.org/wiki/Hosts_(file)

where mapping from localhost and 127.0.0.1 need to be defined. 

But it seems like you found a solution by using the full hostname for the server TabPy is on.

**Comment by andylam1989** [comment]
I have tried with the localhost (127.0.0.1) of coz it works well but I tried to config in Tableau server, it's not work. My flow is configured in server 
tabadmin stop
tabadmin set vizqlserver.allow_insecure_scripts true
tabadmin set vizqlserver.extsvc.host <host>
tabadmin set vizqlserver.extsvc.port <port>
tabadmin config
tabadmin start

Any idea for this problem. Thanks ;)

**Comment by venkataanumula** [comment]
@andylam1989  it would be helpful if you could mention the error you are getting.

**Comment by BBeran** [comment]
I have a server running without any issues with the following config

vizqlserver.extsvc.host http://127.0.0.1
vizqlserver.extsvc.port 9004
vizqlserver.script.disabled true

Last setting is backwards. It has to be set to true to enable scripts while the name implies otherwise. 
allow_insecure_scripts controls whether Tableau Server should accept string parameters which is a safety measure against injection attacks.

**Comment by andylam1989** [comment]
Thank you **venkataanumula** and **BBeran**. Of coz when I set 127.0.0.1, it means the IP of localhost and it works very well. Now I want to use another computer with IP to run Pytab and in Tableau, I set the IP of this computer? Is it possible? I saw some blog for Rserve and I have tried this way. Thanks again!

**Comment by s13varun** [comment]
I am trying to connect R and tableau server. In my case R and tableau desktop are on one machine and tableau server on another machine. I could publish workbook, but it returns error when opening workbook.
I had executed the following
C:\Program Files\Tableau\Tableau Server\10.4\bin>tabadmin stop
C:\Program Files\Tableau\Tableau Server\10.4\bin>tabadmin set vizqlserver.extsvc.host <ip address of the machine hosting Rserve>
C:\Program Files\Tableau\Tableau Server\10.4\bin>tabadmin set vizqlserver.extsvc.port 6311
C:\Program Files\Tableau\Tableau Server\10.4\bin>tabadmin set vizqlserver.script.disabled true
C:\Program Files\Tableau\Tableau Server\10.4\bin>tabadmin configure
C:\Program Files\Tableau\Tableau Server\10.4\bin>tabadmin start
![r](https://user-images.githubusercontent.com/36952745/44768211-3a786d80-ab7e-11e8-8ad1-4f0a79ab4c02.png)
![tab](https://user-images.githubusercontent.com/36952745/44768222-449a6c00-ab7e-11e8-9512-565b89e4d4d9.png)
![tabserverror](https://user-images.githubusercontent.com/36952745/44768229-4a904d00-ab7e-11e8-9157-405913b520b3.png)

Any idea to solve this ?
Thanks

**Comment by 0golovatyi** [comment]
@s13varun 

in your comment above I see you are missing hostname when configuring server with `tabadmin set vizqlserver.extsvc.host` command.

**Comment by 0golovatyi** [comment]
Try to start Rserve with `Rserve(debug=TRUE)` to confirm it can locate and load config file and parameters there are what you expect them to be.

**Comment by s13varun** [comment]
I have made the following changes. I could publish workbook, when I try to open dashboard it takes more than 30 minutes and returns error.
![r](https://user-images.githubusercontent.com/36952745/44832041-c950bd00-ac46-11e8-8ca1-213617b60d5d.png)
![tab](https://user-images.githubusercontent.com/36952745/44832047-cf469e00-ac46-11e8-945e-74e11633a0ed.png)
![cmd](https://user-images.githubusercontent.com/36952745/44832050-d372bb80-ac46-11e8-9fb2-65dd8ebec01d.png)
![tabserverror](https://user-images.githubusercontent.com/36952745/44832060-db326000-ac46-11e8-8377-c55d84a88ce7.png)

**Comment by nmannheimer** [comment]
In your cmd line printouts it looks like you're setting the extsvc.host to localhost, but earlier you mentioned you are running RServe on a different machine. 

Are you setting the extsvc.host to the ip address of the machine where Rserve is running? Additionally can you confirm that you can ping the machine where RServe is running from the box where Tableau Server is running?

**Comment by nmannheimer** [comment]
Also, @s13varun this github page is primarily for supporting TabPy Python integration. If the issue persists, please consider posting on Tableau's forums, so you can get input from community members who may have more experience with RServe as well as the Tableau team:

https://community.tableau.com/community/forums/externalservices

**Comment by s13varun** [comment]
Sorry for not updating that. Both are running on same machine now.
I didn't understand **"** Can you confirm that you can ping the machine where RServe is running from the box where Tableau Server is running? **"**

**Comment by nmannheimer** [comment]
So if I understand correctly, you are running RServe on the same machine as your Tableau Server? Are you also running an RServe instance on the same machine as your Tableau Desktop instance, or are all three on the same machine?

If you were running RServe on a different machine than your Tableau Server, pinging the computer that was running RServe from the computer running Tableau Server would confirm that you can send network traffic between the two.
http://www.steves-internet-guide.com/ping-command/

**Comment by nmannheimer** [comment]
And to confirm, you are able to render the visualization you are trying to make with R code in Desktop, but not in Server even when all three are on the same machine?

**Comment by s13varun** [comment]
Yes. It works on desktop but not in server

**Comment by 0golovatyi** [comment]
@s13varun,

With `debug=TRUE` on the screenshot, you provided it is unfortunately still not clear what config file and parameters running Rserve is using. Could you try `Rserve(debug=TRUE, args="--RS-conf C:\path\to\conf\file")`? I am not sure it works for Windows Rserve in the same way - on Linux\Mac debug output shows if config file was found and what parameters are used (host, port, etc.)

**Comment by s13varun** [comment]
Correct me if I am wrong. I had found many tutorial regarding config file of Rserve. I have not found any config file under Rserve yet. Is config file comes with Rserve installation or should we create one ?

**Comment by nmannheimer** [comment]
Hello @s13varun,

Since this issue is ongoing, I'm going to ask that you submit an issue on the Tableau forums in the external services section:
https://community.tableau.com/community/forums/externalservices
or file a ticket with Tableau technical support:
https://www.tableau.com/support

This github page is for Tableau's Python integration server TabPy.

**Comment by s13varun** [comment]
I want to integrate R and tableau server to make use of a function in R package. It is not working even on tableau desktop. 
To integrate python with tableau, I already had anaconda installed on my machine. When I ran startup.bat window closes immediately. How to solve this ?

startup.bat file location C:\Users\user4\AppData\Local\conda\conda\pkgs\tabpy-server-0.2-py36_0\Lib\site-packages\tabpy_server

![ap](https://user-images.githubusercontent.com/36952745/44983095-9f283380-af95-11e8-8058-d6ba8b43344b.png)

**Comment by slewt** [comment]
You’ll probably get faster answer on the Tableau forums. This repository is
for TabPy and not R. Some individuals will have knowledge of R here, but
it’s not the focus.
