### ISSUE TITLE
Use GitHub Actions for CI

### ISSUE THREAD

**Issue by WillAyd** [tableau/TabPy#371]
I've noticed that CI is currently configured for Travis with Python 3.6 and Linux. As a thought, you may want to consider moving to GitHub actions, where you can easily specify a matrix of Python versions to test on various platforms. 

For reference, here is what that looks like for pantab, which tests Python 3.6/3.7/3.8 on macOS, Windows and Ubuntu

https://github.com/innobi/pantab/blob/master/.github/workflows/pythonpackage.yml

**Comment by 0golovatyi** [comment]
Added github workflow here - https://github.com/tableau/TabPy/pull/384

**Comment by 0golovatyi** [comment]
The chance is in dev->master PR - https://github.com/tableau/TabPy/pull/388
