### ISSUE TITLE
PC Users can connect to the external service, but MAC users cannot.

### ISSUE THREAD

**Issue by mhollis5** [tableau/TabPy#372]
**Environment information:**
 - OS: Windows Server 2016 Datacenter
 - Python version: 3.7
 - TabPy release:0.7

**Describe the issue**
We have many users, PC and MAC.  PC users can connect to the external TabPy service without issue from their machines, while MAC users cannot - they receive this error: "Failed to connect to external service due to invalid protocol"

**To Reproduce**
We're all using the same internet connection; using Tableau Desktop Version 2019.2; connecting to TabPy on a remote Windows Server (listed above) which is running both Tableau Server and TabPy.

SSL is configured and the service is verified to be running on port 9044 

I haven't found anyone else with this issue, so far.  We've tested this with 8 people so far, all confirming that PC connections result in success, while MAC connections result in a failure.  These users can successfully connect to the TabPy service when it is run on their local machines, as well.  Only the external connection is broken.

**Comment by 0golovatyi** [comment]
@mhollis5 there's known issue for secure TabPy connection on Mac. Would it be possible for you to confirm if Mac users can connect to not a secure instance of TabPy?

**Comment by mhollis5** [comment]
> @mhollis5 there's known issue for secure TabPy connection on Mac. Would it be possible for you to confirm if Mac users can connect to not a secure instance of TabPy?
@0golovatyi It sure is - I can confirm that Mac users can connect to TabPy when it's insecure; only secure is not working.  Unfortunately non-secure isn't an option for us.

**Comment by nmannheimer** [comment]
@mhollis5 This is something that is fixed in the upcoming 20.1 release of tableau desktop and will also be in an upcoming maintenance release for 19.4
