### ISSUE TITLE
After upgrade Tableau from 2019.3 to 2019.4 python scripts not working on linux

### ISSUE THREAD

**Issue by rajug1** [tableau/TabPy#376]
After upgrade Tableau from 2019.3 to 2019.4 python scripts not working on linux

- we downgraded to 2019.3 for now.

Do Tabpy works with 2019.4 version on linux?

Thanks
Raj

**Comment by 0golovatyi** [comment]
@rajug1 What error on Tableau/TabPy side you see when scripts don't work?
How do you configure connections for 2019.3 and 2019.4?
TabPy itself is agnostic to Tableau version.

**Comment by rajug1** [comment]
hi 0golovatyi,

Python scripts not working in 2019.4 got fixed now

Issued got fixed by applying below commands in 2019.4
--------------------------------------
(a) tsm security vizql-extsvc-ssl enable  --connection-type "tabpy" --extsvc-host <ip> --extsvc-port 9004 --connect-timeout-ms "1500" --script-disabled "false"
(b) tsm configuration set -k vizqlserver.allow_insecure_scripts -v true
(c) tsm pending-changes apply

Till 2019.3 version below commands used to work, from 2019.4 below are no longer working
--------------------------------------------------------------------------------------------------------
tsm configuration set -k vizqlserver.extsvc.host -v <ip>
tsm configuration set -k vizqlserver.extsvc.port -v 9004

tsm configuration set -k vizqlserver.allow_insecure_scripts -v true
tsm configuration set -k vizqlserver.script.disabled -v true
tsm configuration set -k vizqlserver.extsvc.connect_timeout_ms -v 1500

Thanks
Raj

**Comment by rajug1** [comment]
Fixed see above cooments

**Comment by 0golovatyi** [comment]
Yes, setting `--script-disabled` to `false` is what is required in 2019.4 for the external services connection to work on Tableau Server.

**Comment by Sunny532** [comment]
Hi All,

I am getting the same issue on the windows server.

Can you please help?

Thanks

**Comment by rajug1** [comment]
Try below to solve, from 2019.4 we have to run below command to connect to tabpy
(a) tsm security vizql-extsvc-ssl enable --connection-type "tabpy" --extsvc-host --extsvc-port 9004 --connect-timeout-ms "1500" --script-disabled "false"
(b) tsm configuration set -k vizqlserver.allow_insecure_scripts -v true
(c) tsm pending-changes apply

**Comment by Sunny532** [comment]
same commands for windows machine as well?

**Comment by Sunny532** [comment]
Thanks Rajug1, I run these commands still the same issue.

Session ID: 0165D959E42F473A94BB1DB32DDB880F-1:2

TableauException: Failed to connect to external service (ext-svc-type-unknown 'http://xxxxx':9004): The connection type is unknown, please select a supported connection type.

**Comment by 0golovatyi** [comment]
@Sunny532 Could you open new issue with the information of what version of Tableau Server are you running, on what platform, exact steps and how your TabPy is configured?
