### ISSUE TITLE
ERROR : ERROR: Could not find a version that satisfies the requirement tabpy (from versions: none) ERROR: No matching distribution found for tabpy

### ISSUE THREAD

**Issue by ribisht** [tableau/TabPy#389]
**Environment information:**
 - Python version:Python 2.7
 - TabPy release: [e.g. 0.4.1]

**Describe the issue**
1)I could install tabpy-server and tabpy-client both

python -m pip install tabpy-server
Requirement already satisfied: tabpy-server in /Library/Python/2.7/site-packages (0.2)
Requirement already satisfied: Tornado-JSON in /Library/Python/2.7/site-packages (from tabpy-server) (1.3.3)

Riteshs-MacBook-Air:TabPy reyansh$ python -m pip install tabpy-client
Requirement already satisfied: requests in /Library/Python/2.7/site-packages (from tabpy-client) (2.21.0)
Requirement already satisfied: cloudpickle in /Library/Python/2.7/site-packages (from tabpy-client) (0.6.1)

But when I try to install TabPy or run the startup command I see the below error
Riteshs-MacBook-Air:TabPy reyansh$ python -m pip install tabpy
ERROR: Could not find a version that satisfies the requirement tabpy (from versions: none)
ERROR: No matching distribution found for tabpy

**To Reproduce**
Steps to reproduce the behavior: what commands to run, what files to modify, where to look for an error.

**Expected behavior**
I want to connect Tableau to Python
Configure Tableau to connect to this service by entering the service URL and port number under Help > Settings and Performance > Manage External Service Connection in Tableau Desktop. Then you can use Python scripts as part of your calculated fields in Tableau, just as you've been able to do with R since Tableau 8.1

**Comment by 0golovatyi** [comment]
@ribisht What instructions are you following? None of the steps you mentioned above is needed for installing and running TabPy.

Here is the document for how to install TabPy - https://github.com/tableau/TabPy/blob/master/docs/server-install.md.

Also, you may find this blog post useful - http://tabscifi.com/2019/12/python-packages-tabpy-tabpy_server-and-tabpy_tools.

**Comment by ribisht** [comment]
Thanks a lot for your response.

As per your instructions, I did perform the steps but could not find any
success

Riteshs-MacBook-Air:TabPy reyansh$ python -m pip install --upgrade pip

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7. More
details about Python 2 support in pip, can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Requirement already up-to-date: pip in
/Users/reyansh/Library/Python/2.7/lib/python/site-packages (19.3.1)


Riteshs-MacBook-Air:TabPy reyansh$ python -m pip install tabpy

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7. More
details about Python 2 support in pip, can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support

ERROR: Could not find a version that satisfies the requirement tabpy (from
versions: none)

ERROR: No matching distribution found for tabpy


Thanks,

Ritesh

**Comment by ribisht** [comment]
Thanks a lot for your response.

As per your instructions, I did perform the steps but could not find any success 

Riteshs-MacBook-Air:TabPy reyansh$ python -m pip install --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in /Users/reyansh/Library/Python/2.7/lib/python/site-packages (19.3.1)

Riteshs-MacBook-Air:TabPy reyansh$ python -m pip install tabpy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement tabpy (from versions: none)
ERROR: No matching distribution found for tabpy

Thanks,
Ritesh

**Comment by 0golovatyi** [comment]
Python 2.7 is the issue. First, it is not supported any more in just a few days and not secure. And, second, TabPy requires Python 3.6 or 3.7.

**Comment by ribisht** [comment]
Thank you for your response

It worked

Ritesh
