### ISSUE TITLE
Error adding endpoint to TabPy Server on Google Cloud VM Instance

### ISSUE THREAD

**Issue by adambooth1** [tableau/TabPy#39]
Hi,

We've been trying to get a TabPy server running on a Google Cloud VM so that we can deploy models from Datalab. I've installed TabPy and the server is running fine - navigating to the ip address in a browser brings up the Tableau logo, and I'm able to connect Tableau to the predictive service and execute python code using the SCRIPT_ functions - however I'm getting an error when using the client to deploy from Datalab. 

Using the code:

```
import tabpy_client
client = tabpy_client.Client('http://{0}:9004/').format(server_ip)

def add(x,y):
    import numpy as np
    return np.add(x, y).tolist()

client.deploy('add', add, 'Adds two numbers x and y')

```
Brings up the error:

![image](https://user-images.githubusercontent.com/29452084/27176390-39326346-51ba-11e7-83fc-e18d9a3980bd.png)

I may well have overlooked something in getting it set up as it is working fine locally, but can't work out what's causing it.

Thanks in advance,

Adam

**Comment by BBeran** [comment]
Currently TabPy only supports deploying to local file paths. So this is not a bug, it is a feature request :)

**Comment by Seiter02** [comment]
This makes deploying to TabPy server running in docker containers impossible as well.  Feature request +1

**Comment by afreeland** [comment]
Believe I am running into this with a docker image as well.  Does this mean that if we 
`pip install tabpy-client future` from an integrated terminal inside the tabpy server container that it should work?  Not quite sure in what context `local` needs to be (server or client)...

I tried, with the example from above directly in a file in the container
```
import tabpy_client
client = tabpy_client.Client('http://localhost:9004/')

def add(x,y):
    import numpy as np
    return np.add(x, y).tolist()

client.deploy('add', add, 'Adds two numbers x and y')
```

However, I get an error 
```
RuntimeError: LoadFailed: u"Load failed: 'int' object is not iterable"
```

**Comment by Seiter02** [comment]
Yeah, it will work inside the container if you mount the file from the host.

The error you are seeing with the number not being iterable is something else unrelated to docker or localhost clients, but more likely related to the versions of python/numpy you are using in your image.

**Comment by afreeland** [comment]
@Seiter02 I am new to TabPy, can you provide a sample of what file needs to be mounted in the host?  When I was looking the staging folder and such never existed.

**Comment by nmannheimer** [comment]
Hi @afreeland,

Are you still experiencing this issue?

**Comment by afreeland** [comment]
@nmannheimer I ended up not continuing with TabPy because we had a large datasets and Tableau executes the script calculated field requests synchronously which didnt allow us to scale the way we needed...sorry can't help much

**Comment by nmannheimer** [comment]
@afreeland thanks for the information, that's useful for us to know.
