### ISSUE TITLE
DLL Load Failed During loading of saved query endpoint

### ISSUE THREAD

**Issue by jtweeder** [tableau/TabPy#393]
**Environment information:**
 - OS: Windows Server 2016
 - Python version: 3.7.3
 - TabPy release: 0.6.1

**Describe the issue**
After server reboot Startup.cmd fails to load collected endpoints of previously working models, fails with DLL Load failed

**To Reproduce**
Save a model, close down tabpy, then start again with the startup.cmd

**Expected behavior**
Load previously saved models without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/31365056/72176770-b6a2d800-33a4-11ea-947d-712f24c95283.png)

**Additional context**
`startup.cmd` was failing with the same issue, but I was able to see what package it was failing on and `pip uninstall...` with a `pip install....` fixed those errors.  In this case I am not sure what package is causing it to error in the loading of the endpoint.

I am able to load the model via pickle manually into a python session without any errors so that makes me think it is not a package in the model, but something tabpy is doing during the model load.

**Comment by 0golovatyi** [comment]
@jtweeder Does the same error repro for you with the updated TabPy? Also, you don't need to run `startup.cmd` with the newer TabPy  - just install the package and start TabPy as shown at https://github.com/tableau/TabPy/blob/master/docs/server-install.md.

**Comment by jtweeder** [comment]
YES!  Upgrading, moving over the models and running with the new commands made it work without a problem.

Thank you!
