### ISSUE TITLE
TabPy in AWS

### ISSUE THREAD

**Issue by arunyadav19** [tableau/TabPy#395]
**Environment information:**
 - OS: Windows and 2016 Server
 - Python version: 3.7.5
 - TabPy release: Latest

**Describe the issue**
How to connect to TabPY running on a AWS machine from my tableau desktop on my local machine.
Also I want to understand how TabPY will work in case of workbooks published on Tableau server and trying to connect to TabPy. How it will work in case of embedded data sources v/s published data sources ?

**Expected behavior**
Should be able to connect to TabPY running on my aws instance from my tableau desktop on local machine.

**Additional context**
I want to enable TabPy for all my users. So I installed it on a separate aws instance and opened the ports for everyone. I'm able to connect to this TabPY from tableau desktop running on one of my tableau server instance but unable to connect from my local machine.

**Comment by 0golovatyi** [comment]
@arunyadav19 What error message you see in Tableau Desktop when trying to connect to AWS TabPy instance?
