### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by phantomcosmonaut** [tableau/TabPy#397]
I’d like to try and develop an interactive UI for tabpy but I was wondering if I should create a new web app with Flask or something and have users connect over http or mount a UI directly to your tornado web app and create a docker compose to bundle everything?

**Comment by 0golovatyi** [comment]
@phantomcosmonaut What functionality for the UI are envisioning? 
There are Postman and Swagger files in the repo which could be used as some sort of UI. Here's the blog post for how to call TabPy API with Postman - http://tabscifi.com/2020/01/invoking-tabpy-api-with-postman/

**Comment by phantomcosmonaut** [comment]
Postman is a great idea, what I had in mind was a dashboard that could aggregate and display endpoint information and allow for simple input of scripts while handling the api request information behind the scenes along with authentication. I can come up with an example at some point and share it

**Comment by 0golovatyi** [comment]
Sounds interesting. The latest beta TabPy package has some improvements for index.html page, that would be the place to try and test work in progress. Unless you want to create a standalone repo for the UI.

**Comment by phantomcosmonaut** [comment]
I think the index page would be the best place to start. Quick question though, I get `[DEBUG] (app.py:app:292): Static pages folder set to "C:\Users\bugbe"` which is just my current directory when running the app, where is this being set? app:292 is a blank line in my text editor... For now I've just copied and pasted the static files to the cwdir

**Comment by 0golovatyi** [comment]
The path is set with parameter `TABPY_STATIC_PATH` (either env variable or setting in config file).

**Comment by phantomcosmonaut** [comment]
I added some handlers and made modifications to other files but its functional. I'll avoid messing with your api handlers, but I'm still working on how to tie in your authentication methods with the new handlers

![index](https://user-images.githubusercontent.com/11512646/73624123-9b2a9600-460d-11ea-88b4-f97f853e4c20.PNG)
![login](https://user-images.githubusercontent.com/11512646/73624122-9b2a9600-460d-11ea-98cc-2196a6cac18e.PNG)

**Comment by 0golovatyi** [comment]
@phantomcosmonaut Are you still working on this? I am closing the issue as it really is an improvement. When you have it ready just create a merge request.

**Comment by phantomcosmonaut** [comment]
I gave up because the amount of code reconfiguration to have it support web pages was overwhelming. I would have had to change the endpoint naming scheme because the server was originally designed to be an api only and also all the integration tests, and then the user authentication service would have been a ground-up re-write. If you want to scavenge anything I've written its in my forked repo
