### ISSUE TITLE
NotImplentedError After Running Tabpy in CMD

### ISSUE THREAD

**Issue by mslw210** [tableau/TabPy#399]
![image](https://user-images.githubusercontent.com/60494474/73506709-053c0480-439c-11ea-8607-fd954f76149d.png)

![image](https://user-images.githubusercontent.com/60494474/73506777-52b87180-439c-11ea-961a-fb94ca4fd2d5.png)

I am trying to get tabpy installed however I'm receiving a NotImplementedError error. (See screenshots.)

I was originally getting the error described in https://github.com/tableau/TabPy/issues/323. However after a new search I tried the solution described here: https://community.tableau.com/thread/320958?start=0&tstart=0 which has led me to the error shown and described above. Any help is greatly appreciated. Thank you.

I've also attached screenshots of my pip list and python version. I am running all commands in Windows CMD.

![image](https://user-images.githubusercontent.com/60494474/73507272-184fd400-439e-11ea-90c8-9da23177fa3a.png)

![image](https://user-images.githubusercontent.com/60494474/73507302-3289b200-439e-11ea-9944-fb4f111fecf4.png)

![image](https://user-images.githubusercontent.com/60494474/73507430-88f6f080-439e-11ea-964c-8cef9ede7bb3.png)

**Comment by phantomcosmonaut** [comment]
Seems to be an issue between Tornado and asyncio on Windows (https://github.com/tornadoweb/tornado/issues/2608), I'd say run the server in a virtual environment with python version 3.7 as such `virtualenv --python=/<path to interpreter>/python-3.7 venv_name`.

**Comment by 0golovatyi** [comment]
@mslw210 This is a known issue caused by incompatibility for some Python packages with Python 3.8. There are 2 workarounds:
1. Update tabpy to the latest beta version with `pip install --upgrade -i https://test.pypi.org/simple/ tabpy` command. What the command does is explained at http://tabscifi.com/2020/01/tabpy-how-to-install-pre-release-package/.
2. Use Python 3.6 or 3.7.

**Comment by mslw210** [comment]
@phantomcosmonaut  @0golovatyi  Thank you for your suggestions above. I've replaced Python 3.8 with 3.7

![image](https://user-images.githubusercontent.com/60494474/73547851-5f24e480-4405-11ea-889b-1a3e226e6dab.png)

I ran pip install tabpy, tabpy-server and tabpy-client which all were successful. 

![image](https://user-images.githubusercontent.com/60494474/73547984-a57a4380-4405-11ea-93bc-8dfdd66a4723.png)

Following the instructions from this post https://community.tableau.com/thread/320958?start=0&tstart=0 I tried to run tabpy and now the cmd is stuck on this screen:

![image](https://user-images.githubusercontent.com/60494474/73548080-c93d8980-4405-11ea-82cd-763b9be1e893.png)

I let it sit for 10 minutes and nothing happened. I also ran it multiple times all ending on the same screen. Any further suggestions?

**Comment by mslw210** [comment]
After reviewing https://community.tableau.com/thread/322265 it seems that the "web service listening on port 9004" means that it can connect to the external server. Using localhost and 9004 https://community.tableau.com/thread/322265

![image](https://user-images.githubusercontent.com/60494474/73550914-12440c80-440b-11ea-95ef-bc2b2c4a9bd3.png)

![image](https://user-images.githubusercontent.com/60494474/73550865-f9d3f200-440a-11ea-98c7-756e06481ded.png)


Thank you @0golovatyi  and @phantomcosmonaut  for your help. Installing 3.7 did the trick. Thank you very much!

**Comment by 0golovatyi** [comment]
@mslw210 you don't need `tabpy-server` and `tabpy-client` and it is highly recommended to uninstall those. More details here - http://tabscifi.com/2019/12/python-packages-tabpy-tabpy_server-and-tabpy_tools/

**Comment by mslw210** [comment]
@mslw210 Uninstalled both. Thank you for the warning!
