### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by samuelleach** [tableau/TabPy#4]
Thanks so much for posting this integration!

I'm working on a fork for python3 compatibility https://github.com/samuelleach/TabPy

I'm not an expert on migrating code from 2.7 to 3.5 but the changes in the above fork seem to start the server (I need to test it soon).

@BBeran Do you foresee any real roadblocks migrating to 3.5?

**Comment by BBeran** [comment]
Hi Samuel,
Unfortunately I am not exactly sure about the work required for this. I am looking forward to seeing your results.

Thanks,

Bora
