### ISSUE TITLE
"Invalid Jason" when running Python code on Tableau to decompose a time serial data

### ISSUE THREAD

**Issue by tansongbob** [tableau/TabPy#40]
I Wrote a Python code trying to decompose a time serial data. 

Here is my code
![issue1](https://user-images.githubusercontent.com/29605223/27390187-a45c7a2c-566e-11e7-886f-f56a06db2577.PNG)

However, I get errors message "Invalid JASON". I am not sure if this is because of my python code issue or TabPy issue. 
![issue2](https://user-images.githubusercontent.com/29605223/27390041-2a73a0be-566e-11e7-8874-c3fe76fbdb2e.PNG)

Have anyone has any thoughts?  
Greatly appreciated!
Tan

**Comment by BBeran** [comment]
JSON doesn't support NaN which your code returns so it fails to serialize.

The workaround would be to replace NaN with None.

You can do so by replacing the line of code where you convert to list with the following

y=list(np.where(np.isnan(x.resid), None, x.resid))

If you'd like to see intermediate results in your code (e.g. you could see NaNs in the result set this way), you can put print statements in your SCRIPT calculation. It will print to your console window from which you started TabPy.

I hope this helps.

Bora

**Comment by tansongbob** [comment]
Thank you so much, Bora. It is very helpful!
