### ISSUE TITLE
 where to find the config file

### ISSUE THREAD

**Issue by somebody621** [tableau/TabPy#404]
**Environment information:**
 - OS: Windows
 - Python version: 3.8
 - TabPy release: 1.0.0

I want to increase the TABPY_MAX_REQUEST_SIZE_MB,
please tell me where to find the config file or other solution

**Comment by johng42** [comment]
It's in <<wherever you installed tabpy> tabpy\tabpy_server\common\default.conf

You have to uncomment that line (remove the # sign) and then you can change the value.  Restart tabpy to use the new value.

Hope this helps!

**Comment by 0golovatyi** [comment]
@somebody621 Read this blog post for how to modify individual parameters or use your own config file - http://tabscifi.com/2020/01/tabpy-modifying-default-configuration/
