### ISSUE TITLE
How to Run Tabadmin for TabPy Server

### ISSUE THREAD

**Issue by cameronwtaylor** [tableau/TabPy#41]
I have the TabPy server running in Python 3.6 on the same machine as Tableau desktop. Connecting to it in Tableau 10.2 and clicking "Test Connection" results in this error: `External Service: The external server is busy or not responding. Failed to create socket to it. ExtSvc: Timeout was reached`. 

Based on this error, I think I need to extend the timeout threshold with `tabadmin set vizqlserver.extsvc.connect_timeout_ms ####`. I tried running this command in the folder where the TabPy files live (`/lib/site-packages/tabpy_server`). This results in `'tabadmin' is not recognized as an internal or external command, operable program or batch file`. Where should I run `tabadmin`? The examples for `tabadmin` say to run it in the Tableau Server location in Program Files. However, I don't have this location, and I'm not attempting to connect to Tableau Server.

I do not have administrator rights on my laptop, and I realize it may be a firewall issue. However, I got through the `mprtia` error by using `127.0.0.1` instead of `localhost` in the Tableau connection to the TabPy server.

Thank you for any insight!

**Comment by BBeran** [comment]
Hi Cameron,
Timeout setting is for Tableau Server. You shouldn't need this if you're running TabPy and Tableau desktop on the same machine in the first place.

This might be happening most likely because of one of the two reasons:

1. TabPy is installed but not running. When you try to connect to http://localhost:9004 using your browser, do you see a Tableau logo? If not, TabPy is not running.
2. Your firewall doesn't allow Tableau to access TabPy through that particular port. On some operating system when TabPy starts for the first time, OS launches a dialog and ask for permissions.

I hope this helps find the root cause of the issue.

Bora

**Comment by cameronwtaylor** [comment]
Bora,

Thank you very much for the explanation. TabPy is running, so it must be a firewall issue through that port. However, I tried other ports (i.e. 8000, 80, 403, etc.), and I'm faced with the same issue. I use port 8000 to run `python -m http.server` and it works fine, so it's confusing why it would be blocked for Tableau. Is there a way to determine which ports might be available for TabPy?

Thank you, again.

Cameron

**Comment by BBeran** [comment]
Do you see any output in the command line from which you initiated TabPy? Errors output to the console which might help understand the issue.

**Comment by cameronwtaylor** [comment]
No output is appearing in the command line. I'm just setting up the connection in Tableau and clicking "Test Connection", and the timeout error is occurring. The command line says `Web service listening on port 8000`

**Comment by BBeran** [comment]
Thanks Cameron.

I am assuming that external services dialog is set to use 127.0.0.1 on port 8000 with "sign in with username and password" box unchecked.  

Would you be able to share the Tableau version number you're using? One that appears on About screen.

**Comment by cameronwtaylor** [comment]
You are correct about the external services dialog. The Tableau version is 10.2.1 64-bit.

**Comment by BBeran** [comment]
I installed 10.2.1, 10.2.2 and 10.2.3 but was unable to reproduce the issue.

**Comment by cameronwtaylor** [comment]
Thank you for trying! I'll go ahead and close the issue.
