### ISSUE TITLE
TabPy Running Indefinitely Question

### ISSUE THREAD

**Issue by ascherer587** [tableau/TabPy#410]
Is there any way to get TabPy to run indefinitely as a background process, such as daemon mode? I found some old information (circa 2017/18) when I did some research on in the internet, but I noticed the recommendations involved methods prior to the newest release.  I am wanting to bring this service to an enterprise level with my company's analytics reporting, so any insight is appreciated.

**Comment by 0golovatyi** [comment]
@ascherer587 TabPy runs until the application is either killed by a user or by a system (e.g. when shutting down or restarting). 

You can either open multiple terminals and run TabPy with one of those or use something like `screen` command to run TabPy on a different virtual screen (kind of).

For autostarting TabPy when your system starts you may add `tabpy` command to your shell startup file. 

With both of those suggestions, you may need to change logging settings for TabPy. Here's some information for how to do that - http://tabscifi.com/2020/02/how-to-configure-logging-in-tabpy/.

**Comment by ascherer587** [comment]
Thanks for providing a detailed response so quickly. I will be checking out these methods today.
