### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by DianaGgithub** [tableau/TabPy#42]
Hi, in trying to run TabPy server using the startup.bat command but I get an error message (WindowsError 5) regarding access to temp folders. Is there a way to run TabPy without creating temporary folders?
Or are there other solutions to this error?

![image](https://user-images.githubusercontent.com/29761209/27656394-cf1405ac-5c16-11e7-89f9-d7d43ae8f1bf.png)

**Comment by BBeran** [comment]
Hi Diana,
Did you try running the installer as an admin by launching CMD as admin then going through these steps?

Thanks,

Bora

**Comment by DianaGgithub** [comment]
Ah I haven't been able to do this yet, but would this need to be done every time it is run?

**Comment by BBeran** [comment]
Only the first successful run. Every time you start it up, it checks if a particular folder exists under tmp and if it is there, won't create it.
