### ISSUE TITLE
TabPy setup windows batch file missing

### ISSUE THREAD

**Issue by subash28kumar** [tableau/TabPy#426]
**Environment information:**
 - OS: [Windows, Linux, Mac] and version
 - Python version: [e.g. 3.6.5]
 - TabPy release: [e.g. 0.4.1]

TabPy setup windows batch file missing, Unable to start the TabPy server without the setup windows batch file

**Comment by nmannheimer** [comment]
Hello @subash28kumar 

It looks like you are following an out of date set of startup instructions. Please refer to the documentation here for how to install and start TabPy: https://github.com/tableau/TabPy/blob/master/docs/server-install.md

**Comment by 0golovatyi** [comment]
@subash28kumar There is no batch file.

**Comment by subash28kumar** [comment]
Thanks for the immediate response, I mean the setup batch file, that starts the TabPy server

**Comment by subash28kumar** [comment]
setup.bat , this particular file is missing

**Comment by subash28kumar** [comment]
> Hello @subash28kumar
> 
> It looks like you are following an out of date set of startup instructions. Please refer to the documentation here for how to install and start TabPy: https://github.com/tableau/TabPy/blob/master/docs/server-install.md



> Hello @subash28kumar
> 
> It looks like you are following an out of date set of startup instructions. Please refer to the documentation here for how to install and start TabPy: https://github.com/tableau/TabPy/blob/master/docs/server-install.md

Hi nmannheimer
Thanks for the response, I have followed the new documentation, it looks like web service listening port 9004, but tabpy service not started with the tableau , I am using tableau public application

**Comment by 0golovatyi** [comment]
@subash28kumar There is no startup batch file, this is why it is missing. To install TabPy follow the instructions at https://github.com/tableau/TabPy/blob/master/docs/server-install.md.

TabPy is not a part of Tableau Desktop or Server and need to be installed and started separately.

Tableau Public can not be connected to any analytics extension - the functionality is not supported there.

**Comment by 0golovatyi** [comment]
@subash28kumar Were you able to resolve the issue?

**Comment by subash28kumar** [comment]
Oh yes, I was able to do that, I will close the issue, thank you

Apologize for not updating

Regards
