### ISSUE TITLE
Receiving error for invalid key file when using SSL

### ISSUE THREAD

**Issue by mhollis5** [tableau/TabPy#427]
**Environment information:**
 - OS: Windows Server 2016 Datacenter
 - Python version: 3.7 64 bit
 - TabPy release: 1.1

**Describe the issue**
When using SSL, I am receiving this error: "Error using HTTPS: The parameter(s) TABPY_KEY_FILE must point to an existing file."
I have ensured the file in the config file is appended with '.key'.  I have also tested this without '.key' at the end, in addition to tyring '.key.key', just in case.

I do not receive this error when using TabPy version 0.7.  I made no changes to the file or its path, so the only change is the version of TabPy.

**Comment by 0golovatyi** [comment]
@mhollis5 Is the path for the key file relative? If it is could you try the absolute path for it?

**Comment by mhollis5** [comment]
It isn't - I'm using the absolute path

**Comment by 0golovatyi** [comment]
@mhollis5 If the path is absolute and points to an existing file the only other reason I can think of right now is if access rights are allowing TabPy to see/read the file.

Do you mind to show how the parameter is set in your config file?

**Comment by mhollis5** [comment]
I thought of that as well, and tried moving the Cert/Key to a file that I know TabPy should be able to access.  Oddly enough, the cert file is fine, and I'm only receiving the error for the key file.

The parameter for the key file is: "TABPY_KEY_FILE = C:\TabPy-1.1\SSL\keyfile.key"

This is the same config file I used for TabPy 0.7

**Comment by 0golovatyi** [comment]
@mhollis5  When you run `dir C:\TabPy-1.1\SSL` do you see `keyfile.key` in the output?

**Comment by mhollis5** [comment]
@0golovatyi I do in fact see it in the output when running that command

**Comment by nmannheimer** [comment]
@mhollis5 would you be interested in setting up a call for us to dig into this further? If so, drop me a line at nmannheimer@tableau.com

**Comment by mhollis5** [comment]
I would actually love that!  Email sent

**Comment by nmannheimer** [comment]
Issue turned out to be with a malformed config file.
