### ISSUE TITLE
Docker container for Tabpy

### ISSUE THREAD

**Issue by biswabandhu21** [tableau/TabPy#430]
How can I containerize Tabpy with docker ?

**Comment by 0golovatyi** [comment]
@biswabandhu21 There are a few solutions people implemented you can find on https://hub.docker.com/search?q=tabpy.

**Comment by 0golovatyi** [comment]
@biswabandhu21 Were you able to find/use a docker container for TabPy?

**Comment by biswabandhu21** [comment]
Yes, the following works for me
https://github.com/starschema/k8s-tabpy
