### ISSUE TITLE
No option to allow only TLS v1.2

### ISSUE THREAD

**Issue by kholis** [tableau/TabPy#432]
**Environment information:**
 - OS: Windows Server 2016 
 - Python version: 3.7.7
 - TabPy release: 1.1.0

**Describe the issue**
By default https allow all version of TLS (1.0, 1.1 and 1.2). How to accept only TLSv1.2 connection?

**To Reproduce**
$ sslscan tabpy-server.example.com 9004
  Supported Server Cipher(s):
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Preferred TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Preferred TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256

**Expected behavior**
Should provide option to restrict/allow TLS version

**Screenshots**

**Additional context**

**Comment by 0golovatyi** [comment]
@kholis we would love to learn your case and how are you using or planning to use TabPy. If you are interested to talk with the team works on TabPy please contact Nathan with nmannheimer@tableau.com.

**Comment by 0golovatyi** [comment]
@kholis any updates?

**Comment by 0golovatyi** [comment]
Closing this as there were not follow up.
