### ISSUE TITLE
Unable to deploy script via REST

### ISSUE THREAD

**Issue by will-mueller** [tableau/TabPy#434]
To the best of my knowledge, it's not possible to deploy a script via REST - you must use the Python client. Please correct me if I'm wrong here.

For example, I would expect to be able to POST to "/endpoints" with all of the data necessary (including the logic) to deploy a new script. Similarly, I would also expect to have the ability to update the logic of a deployed script with a PUT to "/endpoints".

I don't see why this functionality wouldn't be possible, so wanted to reach out to the community to see if this idea had already been considered and to gauge interest. I think it'd be great for integrating with non-Python applications.

**Comment by 0golovatyi** [comment]
@will-mueller The challenge with that is deployed functions are Tornado query object and to modify them you need to operate with the storage.
But yes, it would be awesome if someone makes the improvement :)

**Comment by nmannheimer** [comment]
@will-mueller this is something we've thought about for a while, but hasn't reached the top of our list to implement. If there's strong demand though it's some we could consider, and of course, as @0golovatyi says, we'd welcome code from the community.

**Comment by will-mueller** [comment]
Thanks for the response here. I've gotten side-tracked with a few other projects since first posting, but looking to make some headway on this item soon. Will update once I have something meaningful to share!

**Comment by nmannheimer** [comment]
@will-mueller any update here? Otherwise I'm going to close this issue out.
