### ISSUE TITLE
Unable to complete action An error occurred while communicating with the Analytics Extension. Error Code: 6116DD27 

### ISSUE THREAD

**Issue by KelvinAduobey** [tableau/TabPy#438]
**_Issue with Tableau/tabpy-server-0.2-py27_1_**

**_Im trying to do an arima forecast but receive this error;_**

Unable to complete action
An error occurred while communicating with the Analytics Extension.
Error Code: 6116DD27
Error processing script
LinAlgError : SVD did not converge

**_This is my python script in the calculated field;_**

SCRIPT_REAL("
import statsmodels.api as sm

import pandas as pd
import numpy as np
import scipy.stats as scs
from datetime import datetime
df = pd.DataFrame({'Date':_arg1, 'NetRevenue':_arg2})
df['NetRevenue'] = df['NetRevenue'].astype('float64')
df['Date'] = pd.to_datetime(_arg2)
df = df[['Date','NetRevenue']].set_index('Date')
df = df.fillna(0)

model=sm.tsa.ARIMA(endog = df['NetRevenue'], order=(min(_arg4),min(_arg5),min(_arg6)))
results=model.fit()
fitted_vals = list(results.fittedvalues.values)

return(fitted_vals)
"
,ATTR([Date]),
ATTR([NetRevenue]),
MIN([Daysforecast]), 
MIN([AR (Time Lag)]), 
MIN([I (Seasonal Difference)]), 
MIN([MA (Moving Average)])
)

**_Please assist_**

![image](https://user-images.githubusercontent.com/69090930/90175966-c994e500-dd97-11ea-8119-bcc650addce7.png)

**Comment by 0golovatyi** [comment]
It seems like `statsmodel` failure. I found similar failure reported and resolved - https://github.com/statsmodels/statsmodels/issues/6360.

**Comment by KelvinAduobey** [comment]
> It seems like `statsmodel` failure. I found similar failure reported and resolved - [statsmodels/statsmodels#6360](https://github.com/statsmodels/statsmodels/issues/6360).

Tried that and got this error too;

 ERROR: Could not find a version that satisfies the requirement statsmodels==0.11.0rc1 (from versions: none)
ERROR: No matching distribution found for statsmodels==0.11.0rc1

**Comment by 0golovatyi** [comment]
@KelvinAduobey https://github.com/statsmodels/statsmodels/issues is probably the best place to ask about that specific package issues.
