### ISSUE TITLE
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

### ISSUE THREAD

**Issue by sathyaanurag** [tableau/TabPy#44]
Hi,

I have installed tabpy according to the user manual and I have implemented the example breast cancer problem mentioned in the tutorial. The python script on the jupyter notebook runs fine without errors and I checked the connection of tableau to the server which is present. But still I am unable to run the code in tableau.

This is the python script:
import math 
import numpy as np
import pandas as pd
from sklearn.grid_search import GridSearchCV
from sklearn.linear_model import LogisticRegressionCV
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing, metrics, svm, ensemble
from sklearn.metrics import accuracy_score, classification_report
import tabpy_client

connection =tabpy_client.Client('http://localhost:9004/')

def SuggestDiagnosis(Cl_thickness, Cell_size, Cell_shape, Marg_adhesion, Epith_c_size, 
                     Bare_nuclei, Bl_cromatin, Normal_nucleoli, Mitosis):
    x = np.column_stack([Cl_thickness, Cell_size, Cell_shape, Marg_adhesion, Epith_c_size, 
                     Bare_nuclei, Bl_cromatin, Normal_nucleoli, Mitosis])
    x = scalar.transform(x)
    return encoder.inverse_transform(gbclf.predict(x)).tolist()
connection.deploy('DiagnosticsDemo',SuggestDiagnosis,
                 'Returns diagnosis suggestion based on ensemble model trained using Wisconisn Breast Cancer dataset')

This is the calculation I have put in Tableau:
SCRIPT_STR("return tabpy.query('DiagnosticsDemo',_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9)['response']",
[Cell Thickness], [Cell Size], [Cell Shape], [Marginal Adhesion], [Epithelial Cell Size], 
                     [Bare Nuclei], [Bland Cromatin], [Normal Nucleoli], [Mitosis])

These are the errors I get when I try to change values in tableau to predict:
An error occurred while communicating with the Predictive Service.
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

Can you please help me out in resolving this issue. If you want any additional information, please let me know.

Thank you

**Comment by BBeran** [comment]
When you go to http://localhost:9004/endpoints do you see an entry named DiagnosticsDemo ?

**Comment by sathyaanurag** [comment]
Hi, thank you for your quick reply. I see DiagnosticDemo in /endpoints

**Comment by BBeran** [comment]
Do you see any errors being printed in the console window from which you started TabPy?

That might give an idea why it is failing.  If not my next question would be whether you're using the demo workbook or a different dataset. What are the values you're passing when you got this error message?

**Comment by sathyaanurag** [comment]
Hi, I downloaded the demo work book and I am using that itself. I think the dataset comes along with the example. Yes, there are error messages generated in the console.

The error says: 
NameError : global name scalar in suggestDiagnosis is not defined.

Can you suggest me what if there is any step to counter this error. 

Thank you.

**Comment by BBeran** [comment]
It looks like the model wasn't successfully trained. When model training fails, you can still publish a function to TabPy server but the error will surface when you try to run the model. 

On some Windows machines, this could happen due to a bug in Python when you try to run model fitting by using all the CPU cores you have. This is controlled by the "n_jobs=-1" setting in the Jupyter workbook. I suspect this might be the issue.

The solution is to set n_jobs=1 which will run the training using only a single core. After making this, if you add the argument override=True to your deploy function then run the entire Jupyter workbook (Cell > Run All) I suspect it might fix it.

**Comment by peeyush1009** [comment]
hi,
i am trying to implement a project from github https://github.com/nmannheimer/Machine-Learning-in-TabPy in  my tableau desktop,i have installed tabpy according to the instructions.
when i run the jupyter notebook Pima Diabetes Load to Server.ipynb i get the error 
ResponseError: (404) UnknownURI "Endpoint 'diabetesclassifier' does not exist"

the other ipynb file Train Pima Diabetes Random Forest Classification.ipynb gives no error when i run it.
the complete script is given below:
# import needed libraries
from sklearn.externals import joblib
import tabpy_client
loadmodel = joblib.load( r'C:\Users\Administrator\Downloads\Machine-Learning-in-TabPy-master\JupyterPimaForest.pkl')
# Define a funtion that will take the loaded model and run predictions on new data
# The server will take the loaded model and pickle it to the server so we do not have to call the location again
def diabetesclassifier(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8):
    from pandas import DataFrame
    
    # Load data from tableau (brought in as lists) into a dictionary
    d = {'Number of times pregnant': _arg1, 'glucose tolerance test': _arg2, 'Diastolic blood pressure mm Hg': _arg3, 'Triceps skin fold thickness': _arg4,
         '2-Hour serum insulin mu U/ml': _arg5, 'BMI': _arg6, 'Diabetes pedigree function': _arg7, 'Age': _arg8}
    # Convert the dictionary to a Pandas Dataframe
    df = DataFrame(data=d)

    # Use the loaded model to develop predictions for the new data from Tableau
    predictions = loadmodel.predict(df[['Number of times pregnant',
                      'glucose tolerance test',
                      'Diastolic blood pressure mm Hg',
                      'Triceps skin fold thickness',
                      '2-Hour serum insulin mu U/ml',
                      'BMI',
                      'Diabetes pedigree function',
                      'Age']])
    return [prediction for prediction in predictions]
# Locate TabPy Server client (you may need to change the address of the server depending on its location)
client = tabpy_client.Client('http://localhost:9004')
# Identify and deploy the loan classifier function defined above
client.deploy('Diabetes Classifier', diabetesclassifier, 'Return a 1 if a patient is predicted to get diabetes within 5 years or a 0 if they are not', override = True)
# Define some dummy data for a quick diagnostic test
_arg1 = [1,2,3,4,6,7,8]
_arg2 = [1,2,3,4,6,7,8]
_arg3 = [1,2,3,4,6,7,8]
_arg4 = [1,2,3,4,6,7,8]
_arg5 = [1,2,3,4,6,7,8]
_arg6 = [1,2,3,4,6,7,8]
_arg7 = [1,2,3,4,6,7,8]
_arg8 = [1,2,3,4,6,7,8]
# Test the deployed function to determine it is properly deployed
client.query('diabetesclassifier', _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8)

ResponseError                             Traceback (most recent call last)
<ipython-input-8-0d16d1b11a21> in <module>()
      1 # Test the deployed function to determine it is properly deployed
----> 2 client.query('diabetesclassifier', _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8)

D:\Anaconda3\lib\site-packages\tabpy_client\client.py in query(self, name, *args, **kwargs)
    184                 uuid : a unique id for the request.
    185         """
--> 186         return self._service.query(name, *args, **kwargs)
    187 
    188     #

D:\Anaconda3\lib\site-packages\tabpy_client\rest_client.py in query(self, name, *args, **kwargs)
    151         return self.service_client.POST('query/'+name,
    152             data={'data':args or kwargs},
--> 153             timeout=self.query_timeout)
    154 
    155 

D:\Anaconda3\lib\site-packages\tabpy_client\rest.py in POST(self, url, data, timeout)
    170     def POST(self, url, data=None, timeout=None):
    171         """Prepends self.endpoint to the url and issues a POST request."""
--> 172         return self.network_wrapper.POST(self.endpoint + url, data, timeout)
    173 
    174     def PUT(self, url, data=None, timeout=None):

D:\Anaconda3\lib\site-packages\tabpy_client\rest.py in POST(self, url, data, timeout)
    106                 timeout=timeout)
    107         if response.status_code not in (200, 201):
--> 108             self.raise_error(response)
    109 
    110         return response.json()

D:\Anaconda3\lib\site-packages\tabpy_client\rest.py in raise_error(self, response)
     61             response.text)
     62 
---> 63         raise ResponseError(response)
     64 
     65     def _remove_nones(self, data):

ResponseError: (404) UnknownURI "Endpoint 'diabetesclassifier' does not exist"

i am getting the error message specified below when i am trying to setup to external service connection. 
"An error occurred while communicating with the Predictive Service.
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided."

And When i go to http://localhost:9004/endpoints i dont see an entry named DiagnosticsDemo ?


please help me resolving this issue.

**Comment by Santhoshsekar89** [comment]
> Hi, I downloaded the demo work book and I am using that itself. I think the dataset comes along with the example. Yes, there are error messages generated in the console.
> 
> The error says:
> NameError : global name scalar in suggestDiagnosis is not defined.
> 
> Can you suggest me what if there is any step to counter this error.
> 
> Thank you.
> ![error-tabpy](https://user-images.githubusercontent.com/8370643/28215712-ea6eaf88-687c-11e7-95f4-569fc175f96b.png)


Hi Sathya,

Did your issue resolved? Im facing the same problem now.

Thanks

**Comment by Azzu17** [comment]
Hi Sathya, Santosh,

I am also having the same problem. did you guys solved the same? please guide me how to solve this.

I am already using n_jobs = -1 in my model but still I am facing the same error

**Comment by sahil0094** [comment]
> Hi Sathya, Santosh,
> 
> I am also having the same problem. did you guys solved the same? please guide me how to solve this.
> 
> I am already using n_jobs = -1 in my model but still I am facing the same error

Use n_jobs=1 instead of "-1"
