### ISSUE TITLE
How to update to 2.2 version

### ISSUE THREAD

**Issue by Icare2000** [tableau/TabPy#446]
Hello

i have authentication issues and i see that it could be fixed in 2.2

my issue is 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-96d406035241> in <module>
----> 1 client.set_credentials('models', 'models2020')

AttributeError: 'Client' object has no attribute 'set_credentials'

how can i force pip to update to that specific version

**Comment by 0golovatyi** [comment]
@Icare2000 TabPy 2.2.0 is not released yet, but you can try pre-release package. To install it run `pip install --upgrade -i https://test.pypi.org/simple/ tabpy`. More details about pre-release TabPy packages are at http://tabscifi.com/2020/01/tabpy-how-to-install-pre-release-package/

**Comment by Icare2000** [comment]
Hello

thanks it worked well

Best Regards

**Comment by 0golovatyi** [comment]
@Icare2000 FYI TabPy 2.2.0 was just published.

Glad to hear your issue was resolved!

Closing for now.
