### ISSUE TITLE
Error during tabpy install

### ISSUE THREAD

**Issue by kenburgos** [tableau/TabPy#447]
**Environment information:**
 - OS: Microsoft Windows [Version 10.0.18363.1016]
 - Python version: 3.8
- TabPy release: Using cached tabpy-2.2.0-py2.py3-none-any.whl (108 kB)

**Describe the issue**
Error during tabpy install

ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\<<my name>>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\sklearn\\datasets\\tests\\data\\openml\\292\\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz

The file isn't in the directory so I imagine that's whats causing the error. How do I get the file though?

**Comment by 0golovatyi** [comment]
@kenburgos I just tried with Python 3.8.1 and it fails for me too, but for different package (simplejson in my case). I was able to solve it with installing the package with Anaconda.

You can try a few options:
1. Install older TabPy with `pip install tabpy==1.1.0`, or
2. Use Python 3.6 or 3.7, or
3. Run `pip install --upgrade tabpy` in elevated console.

**Comment by kenburgos** [comment]
thank you - install worked though anaconda
