### ISSUE TITLE
The result returned by the SCRIPT function is of an unexpected type - Error while fetching results from Rest API Endpoint

### ISSUE THREAD

**Issue by vipuln89** [tableau/TabPy#448]
**Environment information:**
 - OS: [Windows 7 64 Bit] 
 - Python version: [3.8.5]
 - TabPy release: [2.2]

**Describe the issue**
I have a user case where i have a Rest API endpoint. The goal is to ask the user to enter latitude and longitude through tableau and then fetch the result from the API endpoint which are a bunch of scores. I created the script in python and it is working when i run it in Jupyter. But when i run it through a calculated field in tableau (after connecting to tabpy/external API), it gives me an error saying "The result returned by the SCRIPT function is of an unexpected type"

In the command window it says - 

2020-09-03,11:03:06 [INFO] (web.py:web:2246): 200 POST /evaluate (127.0.0.1) 5.00ms

What am doing wrong here? is there another way i can fetch the results from the Rest API endpoint directly?

**To Reproduce**
Python code in Calculated field - 

SCRIPT_REAL(
"
import pandas as pd
import json
import glob
import requests
import urllib3
import time
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def getscoreList(_arg1,_arg2) :

    url = 'https://<private>.com:34443/<private>/api/v1/score/all-hazards/multi'

    
    filename = pd.DataFrame(columns = ['latitude','longitude'])
    filename['latitude'] = [_arg1]
    filename['longitude'] = [_arg2]
    headers = {'Content-type': 'application/json'}
    master_df = pd.DataFrame()
    scores_df = pd.DataFrame()
    for i in range (len(filename)) :
        
            testfile = filename.iloc[i:i+1] 
            testjson = testfile.to_json(orient = 'records')
            testjson = json.loads(testjson)
            r = requests.post(url,json = testjson, headers = headers, verify=False)
            output = json.loads(r.content)
            a = output.get('riskScores')
            b = a[0].get('scores')
            scores_list = []
        
            for j in range(len(b)) :
            
                c = b[j].get('scenarios')
                hazard = b[j].get('hazard')
    
                for k in range(len(c)) :
            
                    scores_df[str(hazard) + str(c[k].get('scenarioName')) + str(c[k].get('year'))] = c[k].get('score')
                    scores_list.append(c[k].get('score'))
    First = scores_list[0]
    return First

",
[latitude],[longitude])

**Expected behavior**
Ideally, the calculated field should return a list of scores (15 scores). But since it was giving the same error when was doing a "return scores_list", i tried returning the first item in the "scores_list".

**Screenshots**

**Additional context**
i have tried achieving the same using a client.Deploy and then querying it from the calculate field but that seems to give a completely different error so i will open a different issue item for that.

**Comment by 0golovatyi** [comment]
@vipuln89 The error message you see tells that the script returns not the type which is expected by Tableau. In this case, Tableau expects real and this is what each element of `First` in the script should be cast or converted to.

**Comment by vipuln89** [comment]
Found a way around using Script_Real calling the python script using tabpy
