### ISSUE TITLE
Error received when trying to access the file on the tableau server - TableauException: Failed to connect to analytics extension 

### ISSUE THREAD

**Issue by vipuln89** [tableau/TabPy#455]
**Environment information:**
 - OS: [Windows]
 - Python version: 3+
 - TabPy release: Latest

**Describe the issue**
So I have a user case in which I am connecting my dashboard to fetch the data from a REST API endpoint. I have tested the following setup on my local machine and it is working as expected.

1. User enters latitude and longitude into a parameter box
2. The parameter values are passed as argument through the SCRIPT_REAL script calculated field
3. The tabpy server uses this arguments to execute a function deployed on the machine which is the python scripts that passes the parameters received from the _arg1 and _arg2 to the Rest API.
4. The results are returned by the python function (.pkl file deployed) and passed on to the dashboard where it is displayed as a text box

Now, I have installed anaconda on the tableau server. It has python 3 and i have deployed the same function on the server as well. The tabpy server has been installed and it is running and listening on 9004.

But when i upload the dashboard i created on the tableau server, and click on the dashboard, it gives me an error saying - 

**An unexpected error occurred. If you continue to receive this error please contact your Tableau Server Administrator.

Session ID: 1556A60ABC7E416BB78712AA4906635E-1:3

TableauException: Failed to connect to analytics extension (ext-svc-type-unknown :6311): No analytics extension configured. Specify a server name and port and then try again.

2020-09-15 09:11:54.516

(X2CFWq9KsJMtu4Dh9BBLOgAAAKg,1:3)

Would you like to reset the view?**

What am I missing here?

**To Reproduce**
The steps are the same as described above

**Expected behavior**
The dashboard should work the same way on the server as on the laptop. User passes the values for lat and long and the text is updated using the framework described above

**Screenshots**
Screenshot of the error attached.
![Tableau Server Error](https://user-images.githubusercontent.com/54536451/93194403-ab8b1d80-f765-11ea-9ddd-54844af8e89e.PNG)

**Additional context**

**Comment by vipuln89** [comment]
I got it configured as localhost by the server admin on the server again and this time it is giving the following error - 


**An unexpected error occurred. If you continue to receive this error please contact your Tableau Server Administrator.

Session ID: 82FF5822C4284A1D84400F3D6A7D58BE-1:3

TableauException: An error occurred while communicating with the Analytics Extension.

2020-09-15 13:04:02.098

(X2C7wW5uKqyjK98d64w7gwAAA9Q,1:3)

Would you like to reset the view?**

**Comment by 0golovatyi** [comment]
@vipuln89  what is your Tableau Server version and what steps did you follow to configure the connection?

**Comment by vipuln89** [comment]
Tableau Server version is - 2020.1.7 (20201.20.0721.1350) 64-bit Windows

Used the steps mentioned in the following link - https://help.tableau.com/current/server/en-gb/config_r_tabpy.htm

Also, instead of setting up the tabpy server on the localhost, we are running the tabpy server on a different server withing the environment. I tested it with my laptop and the connection is working but now it is giving the following error on the server - 

An unexpected error occurred. If you continue to receive this error please contact your Tableau Server Administrator.

Session ID: 9887F3FE4D504E318BA31AF4EBB154F5-1:1

TableauException: Failed to connect to analytics extension (ext-svc-type-tabpy <private>:35443): An error occurred while communicating with the analytics extension. Tableau is unable to connect to the extension. Verify that the extension is running and that you have access privileges.

2020-09-18 13:33:39.199

(X2S3MtcC4ksR7xoFHl-c2AAAAwY,1:1)

Would you like to reset the view?

**Comment by 0golovatyi** [comment]
@vipuln89 Do you see the request reaching TabPy with the logs? There could be a few reasons for the issue like a firewall on Tableau Server or TabPy side, the name of the host for TabPy is not discoverable by the Tableau Server host, etc.

**Comment by vipuln89** [comment]
@0golovatyi you were right. The SSL certificate wasn't there on the Tableau Server and the server where tabpy server is running needed SSL. I fixed it, tested it and it was working. But now, 1 day later, i am getting this error - "Analytics extension script is invalid"
Can you provide any insights on why this error would be coming up? thanks.

**Comment by 0golovatyi** [comment]
@vipuln89 That error message means something was wrong with the script execution. You need to check TabPy logs for more details for the failure.

**Comment by nmannheimer** [comment]
@vipuln89 From Tableau Server, can you write a script the does something simple like "return 1" and see it succeed?

**Comment by vipuln89** [comment]
The error is now fixed. thanks for your support. there was an error in the way the function was deployed on the tabpy server.

**Comment by akthardy** [comment]
vipuln89,  can you elaborate on what the error was - what do you mean there was an error in the way the function was deployed. I am also getting this error when testing tabpy.
