### ISSUE TITLE
Tableau Prep Builder TabPY ModuleNotFoundError

### ISSUE THREAD

**Issue by krisk360media** [tableau/TabPy#460]
**Environment information:**
 - OS: MacOS Version 10.15.6
 - Python version: 3.8.2
 - TabPy release: 2.2.20

**Attachments:**

1. Screenshot of Basic script I'm trying to import.  (I can't attach the csv file that's being read in my python script because it has sensitive information). Also, I tried attached the .py file but GitHub doesn't support that file being attached?!
<img width="1440" alt="Screen Shot 2020-10-09 at 1 50 39 PM" src="https://user-images.githubusercontent.com/72623854/95615915-f9c6d000-0a36-11eb-97c1-a30e3a7375d6.png">

2. Screenshot showing the error I'm getting. The error:
**'Something went wrong when running the script. Verify that there are no errors in the script, then try again. ModuleNotFoundError: No module named lifetimes.'**

<img width="1440" alt="Screen Shot 2020-10-08 at 6 04 02 PM" src="https://user-images.githubusercontent.com/72623854/95615928-03503800-0a37-11eb-8318-d60ac1ebc163.png">

**To Reproduce**
Connect to the tabpy, using localhost and port 9004 in Tableau Prep
Try to import lifetimes module in a python script.
P.S. I have this running in a virtual environment, and have installed lifetimes package in my environment.

**Expected behavior**
I should be able to see the new columns created: Count_Emails, OrderDate, Email_ID. I've added empty columns in Tableau Prep so the results should just populate in Tableau Prep

**Additional context**
I've tried with importing lifetimes as: **from lifetimes.utils import *** and **import lifetime** with both I get an import error.

**Comment by 0golovatyi** [comment]
@krisk360media You can check what Python modules are installed with running `pip list` command. And with `pip install <module-name>` you can install pypi module.

**Comment by krisk360media** [comment]
Hi! @0golovatyi , Thanks for responding!  I've added a screenshot of my installed libraries and have pypi 
<img width="452" alt="Screen Shot 2020-10-13 at 8 47 30 AM" src="https://user-images.githubusercontent.com/72623854/95862571-1877e000-0d31-11eb-8b1d-cd09478670e2.png">

**Comment by 0golovatyi** [comment]
@krisk360media Since you have an issue with a specific Python package it may worth asking the question on its homepage. I would guess https://github.com/CamDavidsonPilon/lifetimes/issues is a good place to start.

**Comment by nmannheimer** [comment]
@krisk360media are you sure that the TabPy instance you are calling is running in the same virtual environment where lifetime is installed?

Also just to check, the package in the image you sent with the list is "lifetime" but in your code your are importing "lifetime**s**" is that correct?

**Comment by nmannheimer** [comment]
@krisk360media are you still experiencing this issue?
