### ISSUE TITLE
TabPy Working as Expected in one Worksheet but not another

### ISSUE THREAD

**Issue by andy-agap** [tableau/TabPy#466]
**Environment information:**
 - OS: Windows 10
 - Python version: 3.8
 - TabPy release: 1.0.0

I've successfully downloaded and run TabPy using pip and typing "taby" in command prompt.
I have also successfully tested the connection to localhost port 9004 on my local Tableau Desktop.

When using the example workbook for interpolation and line smoothing [here](https://community.tableau.com/s/question/0D54T00000G54nZSAR/how-to-create-a-smoothed-line-chart-with-tableau-python-detailed-guide), I am able to load the curved graph in the "Curved" worksheet. If I add a print(result), I can see the interpolated list with many values in the command prompt.

However, when I try to recreate the same worksheet, when I check the prompt, it is only printing the original 12 values. As such, my line graph is not smoothened.
Does anyone know what I am doing wrong? Perhaps I am missing out on some worksheet setting?

Both worksheets old and new are using the same calculated field.
I have also tried using my own data source in a new workbook, but to no avail.

Thanks and much appreciated.

**Comment by 0golovatyi** [comment]
@andy-agap For Tableau specific questions I recommend asking those at Tableau Community Forum - https://www.tableau.com/community.

**Comment by nmannheimer** [comment]
Without seeing the sheets, I believe that issue here is that you need to create marks between your original values. You can do that by going to a lower level of time IE months to days (assuming a date field here) and the selecting "Show missing values"

**Comment by nmannheimer** [comment]
For more details on how to use analytics extensions look here: https://www.youtube.com/watch?v=nRtOMTnBz_Y

https://www.youtube.com/watch?v=0BN_Y2CxdYY
