### ISSUE TITLE
RuntimeError: LoadFailed: 'Load failed: range() integer end argument expected, got list.'

### ISSUE THREAD

**Issue by Proteusiq** [tableau/TabPy#47]
I get this error when I deploy this Gradient Boosting Regressor model in our server. 

This is my function:

```
def gBRModel(f, i, p, r):
    X = np.transpose([f, i, p, r]).astype(np.float64)
    X = scaler.transform(X)
    return gBR.predict(X).tolist()

```
When I run it on my local server Jupyter Notebook on Python 3.6 Windows. It works:

![image](https://user-images.githubusercontent.com/14926709/28663640-3ccf8040-72be-11e7-80a2-373aa449d8ef.png)

I rewrote the script in our server ipython running Python 2.7 because of the common bug ([Cross OS client.deploy()](https://github.com/tableau/TabPy/issues/8)) and the fact that our remote TabPy is on 2.7 . 

But when I try to deploy it  in our remote linux server with Python 2.7, it does not work. 

client.deploy('gBoost',
              gBRModel,
                'Returns the predicted GTI score given fatalities, injuries, properties and rank', override = True)

![image](https://user-images.githubusercontent.com/14926709/28665460-01513102-72c4-11e7-88d4-4402387e3afe.png)

I get this error. Any thoughts?

**Comment by BBeran** [comment]
I have been trying to reproduce this but no luck so far. Is there anything you can tell me about your particular setup? You're on a Linux machine with Python 2.7 where you completed the model training etc. and TabPy you're trying to publish is on a different Linux machine with also Python 2.7. 

Is that correct? 

Does it work when you deploy on TabPy on the same machine e.g. if you remote desktop to the machine with TabPy and run deploy to localhost there?

**Comment by Proteusiq** [comment]
Yes. Localhost works(Windows 7). I will attempt to do this again that we have updated both Python updated to 3.6. Else we will move our tabpy to docker.
