### ISSUE TITLE
PyPI sdist doesnt contain resources

### ISSUE THREAD

**Issue by jayvdb** [tableau/TabPy#472]
**Environment information:**
 - TabPy release: 2.3.1.tar.gz 

**Describe the issue**
The sdist on PyPI includes tests, however the resources are not present, which means many tests fail trying to open `tests/integration/resources/pwdfile.txt` and similar

**Comment by 0golovatyi** [comment]
@jayvdb what are repro steps for tests to fail?

**Comment by jayvdb** [comment]
1. Fetch https://files.pythonhosted.org/packages/5d/9e/c653c26ea1d852bd4d17aca77702543edbae438a61d290c4a871080b8e0b/tabpy-2.3.1.tar.gz
2. Unpack into a temp dir
3. Activate new venv
3. Install into new venv
4. run tests from the temp dir

**Comment by 0golovatyi** [comment]
@jayvdb Thank you for the steps, now I got it. Using tar.gz is not something we see people do - usually, they just fork the repo, make changes and create merge request.

Approving you merge reques.
