### ISSUE TITLE
Unable to deploy functions from local machine to Tabpy on a remote server 

### ISSUE THREAD

**Issue by siddanthk** [tableau/TabPy#479]
**Environment information:**
 - OS: Windows 10 to windows server
 - Python version: 3.7.1
 - TabPy release: 2.3.1

**Describe the issue**
Trying to deploy a python function to remote Tabpy server from my local machine. But the system throws error - The system cannot find the path specified: 'E:\\'. If i try to deploy the same function on local machine Tabpy running instance. It gets deployed without any error.

**To Reproduce**
Install Tabpy on any remote server (My case - Windows server). Use Python Tabpy_tools.client.deploy() to deploy a function from your local machine to remote server. Throws error - cannot find the path specified xxxx. Where xxxx is the location of "/configurations/endpoint_upload_destination" on Tabpy server. In my case it was "E:\\Program Files\\Python38\\xxxx\\xxxx\\Stage"

Here is the code i used:

from tabpy.tabpy_tools.client import Client
conn = Client(f'https://SERVER_HOST_ADDRESS:9004/')  

> Here SERVER_HOST_ADDRESS is not localhost. 

conn.set_credentials("User", "Pass")
conn.deploy(function_name, function,  description, override=True)

**Expected behavior**
Should be able to deploy a function on to remote Tabpy server after being connected using Client() and set_credentials() functions.

**Additional context**
I see the error is coming while system is trying to save the function on remote server (per tabpy/tabpy_tools/query_object.py - "save" function line 49).

**Comment by 0golovatyi** [comment]
@siddanthk Due to deployed functions currently are implemented as Tornado stored objects it is only possible to deploy those from the same machine TabPy is running on.
