### ISSUE TITLE
Tabpy Installation failed 

### ISSUE THREAD

**Issue by amarupak** [tableau/TabPy#48]
Any help please. Getting the following error when installing from windows

![image](https://user-images.githubusercontent.com/13070517/28793232-fb64d366-75f7-11e7-9bbb-11925aaff34c.png)

C:\Users\yyy1k64\Documents\TabPy-master>setup.bat
Server will be initialized using port: 9004

~~~~~~~~~~~~~~~~  Looking for existing Anaconda installation  ~~~~~~~~~~~~~~~~~

Existing Anaconda installation found.

~~~~~~~~~~~~~~~~~~~~~~~~  Activating the environment  ~~~~~~~~~~~~~~~~~~~~~~~~~

Found existing Tableau-Python-Server environment.
C:\Users\yyy1k64\Anaconda\envs\Tableau-Python-Server
Activating environment "Tableau-Python-Server"...

~~~~~~~~~~~~~~~~~~~~~~~~~~  Installing dependencies  ~~~~~~~~~~~~~~~~~~~~~~~~~~

Processing c:\users\yyy1k64\documents\tabpy-master\tabpy-client
Collecting cloudpickle (from tabpy-client==0.2)
  Could not find a version that satisfies the requirement cloudpickle (from tabp
y-client==0.2) (from versions: )
No matching distribution found for cloudpickle (from tabpy-client==0.2)
Processing c:\users\yyy1k64\documents\tabpy-master\tabpy-server
Collecting future (from tabpy-server==0.2)
  Could not find a version that satisfies the requirement future (from tabpy-ser
ver==0.2) (from versions: )
No matching distribution found for future (from tabpy-server==0.2)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~  Installation failed  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by BBeran** [comment]
It looks like you had already installed TabPy once and it installed Anaconda and  this is the second time. Can you try the instructions here and let me know if it solves the problem? I also copy-pasted below for convenience.

https://github.com/tableau/TabPy/blob/master/server.md#manual-installation

On Linux/MacOS:

```bash

source activate Tableau-Python-Server

```

On Windows:

```Batchfile

activate Tableau-Python-Server

```
### Installing TabPy

Since TabPy is available on [PyPI](https://pypi.python.org/pypi/tabpy-server) you can install by simply running the following command.


```Batchfile

pip install tabpy-server

```
This will install TabPy into your active Python environment.

**Comment by amarupak** [comment]
![image](https://user-images.githubusercontent.com/13070517/28839909-ce8e9e4e-76ba-11e7-8b02-76cf37e493dc.png)

Thanks for the reply :)

I tried running the command  activate Tableau-Python-Server and looks like nothing happened and also

I cannot see the /python2.7/Tapy-server folders inside  Anaconda/envs/tableau-Python-Server/ directory. 

If i run pip install tabpy-server   i get the following error:
![image](https://user-images.githubusercontent.com/13070517/28840069-636ee88e-76bb-11e7-9260-a6bee8de9b64.png)


Could you please help I have no idea where I am going wrong.
Thanks.

**Comment by BBeran** [comment]
What version of Python do you have? It looks like it is complaining that pip can't find a matching version of tabpy-server. 

This could also happen if it is failing to connect to PyPI. 

Are you able to do a pip install any other package in your Python environments? Or are they all failing with the same message? 

e.g. what do you see when you do

pip install titlecase

when you typed "activate Tableau-Python-Server", you can see that it got added to your command prompt so it is there for sure.

**Comment by Protesuiq** [comment]
Since you have conda, why not try, after activating the env.

`conda install tabpy-server`

Conda ought to fix the dependence issue

**Comment by amarupak** [comment]
I have python 2.7

When i do ` pip install titlecase`  

I am getting the same error like before

![image](https://user-images.githubusercontent.com/13070517/28882107-da95c9fa-776f-11e7-8405-be488e19872e.png)


Protesuiq - thanks for the suggestion

When I run `condainstall tabpy-server`

I get the following error
![image](https://user-images.githubusercontent.com/13070517/28882195-2bc7eb50-7770-11e7-9ac9-aeb202e4e1f2.png)

The reason I think is may be because of the firewall and other internet permissions that are restricting my access as I am installing it on my work laptop.

When I tried the septup.bat on my personal laptop, it ran fine and I was able to start the server.

I should contact my network administrators to allow access.

Thanks BBeran for the help and Protesuiq for the suggestions. I will update once I resolve the access issues and try the installation.

**Comment by BBeran** [comment]
Since you can't install any Python package (not just tabpy), I believe this is not related to TabPy but rather a network/firewall issue.

**Comment by Protesuiq** [comment]
BTW: I was able to reproduce your problem. When I install Anaconda for 'All Users', which requires admin authentication, and have VPN on, I get similar errors.

Installing Anaconda 'Just For Me', which does not require admin authentication, appears to work fine, even with VPN on.

Tested Tool:
Windows 7
Cisco VPN
Anaconda 3
