### ISSUE TITLE
 Can't find startup.cmd. at zip from  https://github.com/tableau/TabPy/releases.

### ISSUE THREAD

**Issue by yamakak** [tableau/TabPy#481]
**Environment information:**
 - OS: Windows 10
 - Python version: 3.7.3
 - TabPy release:  TabPy-2.3.1

**Describe the issue**
 Can't find startup.cmd. at zip from https://github.com/tableau/TabPy/releases .  I am trying follow : https://tableaumagic.com/tableau-and-python-an-introduction/

**To Reproduce**
Steps to reproduce the behavior: what commands to run, what files to modify, where to look for an error.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 0golovatyi** [comment]
@yamakak there is no startup.cmd. The link you are following is for an obsolete version of TabPy which is not supported for some time now. For how to start TabPy read this documentation - https://github.com/tableau/TabPy/blob/master/docs/server-install.md#starting-tabpy
