### ISSUE TITLE
Can't Enable Analytics Extension on Tableau Server 2020.1.6 

### ISSUE THREAD

**Issue by msacs09** [tableau/TabPy#482]
**Environment information:**
 - OS: WINDOWS 2016 64-bit
 - Python version: 3.7
 - TabPy release: 2.3.1
 - Tableau server: 2020.1.6

**Describe the issue**
We are following this article to Configure Connection with Analytics Extensions https://help.tableau.com/current/server/en-gb/config_r_tabpy.htm, as per the article **2020.1.6** is a supported version, but it appears that we cant find that option to enable the extension. Please see attached what we see when we login as a site admin under settings --extension 

**To Reproduce**
try to enable Analytics Extension in Tableau server 2020.1.6 

**Expected behavior**
Unable to locate an option to configure/enable the Analytics Extension

**Screenshots**
See attached

![TabPy-cant find extension](https://user-images.githubusercontent.com/43424222/107428744-53700180-6ae0-11eb-9535-e6cb945a4429.JPG)
![Server publish issue](https://user-images.githubusercontent.com/43424222/107428755-566af200-6ae0-11eb-9f52-389a7c3a7626.JPG)

**Comment by 0golovatyi** [comment]
@msacs09 Connections can be configured with Web UI starting from Tableau Server 2020.2. For 2020.1 you need to use TSM - https://help.tableau.com/v2020.1/server-linux/en-us/cli_security_tsm.htm#tsm_security_vizql-extsvc-ssl-enable.

**Comment by msacs09** [comment]
Thank you for quick turnaround. Sorry to ask what is TSM ? also we did not enable SSL with Tabpy install on Anaconda? **can you kindly provide the steps to Enable analytics extension in 2020.1 Tableau server** ? with desktop I don't have issues, just when i publish it expects enabling and configuring analytics extension in the Tableau server.

**Comment by 0golovatyi** [comment]
@msacs09 TSM is a command line tool to configure Tableau Server - https://help.tableau.com/current/server-linux/en-us/tsm.htm.

I am not sure what you mean by "we did not enable SSL with Tabpy install on Anaconda". Secure connection on TabPy side configured with parameters as explained at https://github.com/tableau/TabPy/blob/master/docs/server-config.md#configuring-http-vs-https.

For configuring analytics extensions on Tableau Server 2020.1 you need to use `tsm security vizql-extsvc-ssl` command.

**Comment by msacs09** [comment]
@0golovatyi THANK YOU.

```
Open TSM command line/shell.
Enter the following command to configure the connection to Tabpy: 
tsm security vizql-extsvc-ssl enable --connection-type tabpy --extsvc-host test123 --extsvc-port 9004
Apply Pending Changes (Tableau Server will restart) 
tsm pending-changes apply
```

Question, is the restart mandatory after tsm command ? also our Tabpy is a remote server where we enabled the firewall b/w Tableau and Anaconda server, this should still work isn't it?

**Comment by 0golovatyi** [comment]
@msacs09 Yes, restart is needed for any TSM pending changes to be applied.

With firewall you may need to open/enable the port TabPy is listening to, but other than that there should not be any issues specific to the firewall scenario.

**Comment by msacs09** [comment]
one last question on this,  the **host** here is it the server where tabpy is running correct? we have a AWS Conda environment and the hostname of that server is example "test123"  that's the one we need to specify isn't it?


c:\user\admin>tsm security vizql-extsvc-ssl enable --connection-type tabpy --extsvc-host **my_tabpy_server** --extsvc-port 9004

**Comment by 0golovatyi** [comment]
@msacs09 correct, the hostname `test123` should be the value to use for `--extsvc-host` parameter. Just make sure the host is reachable from the machine where Tableau Server is running (`ping test123` should be enough to confirm).

**Comment by msacs09** [comment]
Thank you. lastly do you have any examples to call these API's https://github.com/tableau/TabPy/issues/482, within jupyter notebook please ? for example this one tabpy.query('Sentiment Analysis', _arg1)[‘response’]

**Comment by nmannheimer** [comment]
Looks like this issue is resolved, if not, feel free to re-open.
