### ISSUE TITLE
No module named 'tabpy'

### ISSUE THREAD

**Issue by msacs09** [tableau/TabPy#483]
**Environment information:**
OS: Red Hat Enterprise Linux Server 7.9 (Maipo)
Python version: 3.7
TabPy release: 2.3.1
Tableau server: 2020.1.6

**Describe the issue**
(base) [ec2-user@ip-10-122-20-222 tabpy]$ cd /home/ec2-user/miniconda3/envs/tabpy-env/lib/python3.7/site-packages/tabpy/
(base) [ec2-user@ip-10-122-20-222 tabpy]$ ll
total 8
-rw-r-----. 1 ec2-user ec2-user   0 Feb 10 16:55 __init__.py
drwxr-x---. 5 ec2-user ec2-user  96 Feb 10 16:55 models
drwxr-x---. 2 ec2-user ec2-user  65 Feb 10 16:55 __pycache__
-rw-r-----. 1 ec2-user ec2-user 889 Feb 10 16:55 tabpy.py
drwxr-x---. 9 ec2-user ec2-user 172 Feb 10 17:10 tabpy_server
drwxr-x---. 3 ec2-user ec2-user 168 Feb 10 16:55 tabpy_tools
drwxr-x---. 3 ec2-user ec2-user  27 Feb 10 17:10 tmp
drwxr-x---. 3 ec2-user ec2-user  65 Feb 10 16:55 utils
-rw-r-----. 1 ec2-user ec2-user   5 Feb 10 16:55 VERSION
(base) [ec2-user@ip-10-122-20-222 tabpy]$ tabpy
Traceback (most recent call last):
  File "/usr/local/bin/tabpy", line 7, in <module>
    from tabpy.tabpy import main
**ModuleNotFoundError: No module named 'tabpy'**

/home/ec2-user/miniconda3/envs/tabpy-env/lib/python3.7/site-packages/tabpy
(base) [ec2-user@ip-10-122-20-222 tabpy]$ ll
total 8
-rw-r-----. 1 ec2-user ec2-user   0 Feb 10 16:55 __init__.py
drwxr-x---. 5 ec2-user ec2-user  96 Feb 10 16:55 models
drwxr-x---. 2 ec2-user ec2-user  65 Feb 10 16:55 __pycache__
-rw-r-----. 1 ec2-user ec2-user 889 Feb 10 16:55 tabpy.py
drwxr-x---. 9 ec2-user ec2-user 172 Feb 10 17:10 tabpy_server
drwxr-x---. 3 ec2-user ec2-user 168 Feb 10 16:55 tabpy_tools
drwxr-x---. 3 ec2-user ec2-user  27 Feb 10 17:10 tmp
drwxr-x---. 3 ec2-user ec2-user  65 Feb 10 16:55 utils
-rw-r-----. 1 ec2-user ec2-user   5 Feb 10 16:55 VERSION

(base) [ec2-user@ip-10-122-20-222 tabpy]$ tabpy
Traceback (most recent call last):
  File "/usr/local/bin/tabpy", line 7, in <module>
    from tabpy.tabpy import main
ModuleNotFoundError: No module named 'tabpy'

**Comment by msacs09** [comment]
Also, the old one on python2.7 works fine ? what is wrong in tabpy on the new one??

(base) [ec2-user@ip-10-122-20-222 lib]$ cd /home/ec2-user/miniconda3/lib/python2.7/site-packages/tabpy_server
(base) [ec2-user@ip-10-122-20-222 tabpy_server]$ ll
total 84
drwxr-x---. 2 ec2-user ec2-user   256 Nov 18 19:00 common
-rw-rw-r--. 2 ec2-user ec2-user     0 Sep 25  2018 __init__.py
-rw-rw-r--. 2 ec2-user ec2-user   139 Sep 25  2018 __init__.pyc
drwxr-x---. 2 ec2-user ec2-user   109 Nov 18 19:00 management
-rw-------. 1 ec2-user ec2-user     0 Feb  8 22:01 nohup.out
drwxr-x---. 2 ec2-user ec2-user   137 Nov 18 19:00 psws
-rwxrwxr-x. 2 ec2-user ec2-user   445 Sep 25  2018 startup.bat
-rw-rw-r--. 2 ec2-user ec2-user   511 Sep 25  2018 startup.py
-rw-rw-r--. 2 ec2-user ec2-user   691 Sep 25  2018 startup.pyc
-rwxrwxr-x. 2 ec2-user ec2-user   664 Sep 25  2018 startup.sh
-rwxr-x---. 1 ec2-user ec2-user   169 Feb  8 21:51 state.ini
-rwxrwxr-x. 2 ec2-user ec2-user   169 Sep 25  2018 state.ini.template
drwxr-x---. 2 ec2-user ec2-user    43 Nov 18 19:00 static
-rw-rw-r--. 2 ec2-user ec2-user 27969 Sep 25  2018 tabpy.py
-rw-rw-r--. 2 ec2-user ec2-user 26638 Sep 25  2018 tabpy.pyc
(base) [ec2-user@ip-10-122-20-222 tabpy_server]$ ./startup.sh
Could not find conda environment: Tableau-Python-Server
You can list all discoverable environments with `conda info --envs`.

Found existing state.ini
Initializing TabPy...
Done initializing TabPy.
Web service listening on port 9004

**Comment by 0golovatyi** [comment]
@msacs09 TabPy only supported for Python 3.6, 3.7 or 3.8 as mentioned in documentation - https://github.com/tableau/TabPy/blob/master/CONTRIBUTING.md#prerequisites.

What you have for Python 2.7 is an obsolete and not supported version of `tabpy_server` which is not recommended for use. Some additional details here - http://tabscifi.com/2019/12/python-packages-tabpy-tabpy_server-and-tabpy_tools/.


To run TabPy you don't need to go to the package folder. It is actually better not to do so as TabPy will use the current folder for its own purposes like logging, storing models, etc. How to install and run TabPy is explained in the documentation here - https://github.com/tableau/TabPy/blob/master/docs/server-install.md.

**Comment by msacs09** [comment]
so followed all these steps installed a new conda environment and i cant find module tabpy. Can u please advise what i'm doing wrong here?

base) [ec2-user@ip-10-122-20-222 ~]$ cd /home/ec2-user/miniconda3/envs/tabpy-env/lib/python3.7/site-packages/tabpy/
(base) [ec2-user@ip-10-122-20-222 tabpy]$ tabpy
Traceback (most recent call last):
  File "/usr/local/bin/tabpy", line 7, in <module>
    from tabpy.tabpy import main
**ModuleNotFoundError: No module named 'tabpy'**

**Comment by 0golovatyi** [comment]
@msacs09 To install TabPy as documentation at https://github.com/tableau/TabPy/blob/master/docs/server-install.md suggest run `pip install tabpy`.

**Comment by msacs09** [comment]
you r swift response is awesome and you r a STAR:-)
