### ISSUE TITLE
SyntaxError in Tableau for a simple python add program 

### ISSUE THREAD

**Issue by msacs09** [tableau/TabPy#484]
```
import tabpy_client
client = tabpy_client.Client("http://localhost:9004/")
def add(x,y):
    import numpy as np
    return np.add(x, y).tolist()

client.deploy('add', add, 'Adds two numbers x and y', override = True)
```

```
client.query('add', 10,2)
{'response': 12,
 'version': 2,
 'model': 'add',
 'uuid': '0fea33e0-410b-4401-a096-a800440ea9bf'}
```

```
SCRIPT_INT("
return tabpy.query('add', x, y)['response']",
SUM([Profit]),SUM([Quantity]))

```
Unable to complete action
An error occurred while communicating with the External Service.
Error Code: 6116DD27
Error processing script
SyntaxError : invalid syntax (<string>, line 3)

**Comment by msacs09** [comment]
@0golovatyi  when you get a chance can you please look into this ?

**Comment by nmannheimer** [comment]
Hey @msacs09 you have a typo in this line:
retrun tabpy.query('add', x, y)['response']",

**Comment by msacs09** [comment]
@nmannheimer  sorry for the overlook now i get the following. Surprisingly Tableau shows the syntax is valid with that typo:-)

```
Unable to complete action
An error occurred while communicating with the External Service.
Error Code: 6116DD27
Error processing script
NameError : name 'x' is not defined
```

**Comment by nmannheimer** [comment]
You need to replace x and y with _arg1 and _arg2 per the documentation for the feature, otherwise Tableau is not passing your variables SUM(profit) and SUM (quantity into your code).

**Comment by 0golovatyi** [comment]
@msacs09 were you able to resolve the issue?
