### ISSUE TITLE
RuntimeError: LoadFailed: "Load failed: No module named 'tabpy_client'"

### ISSUE THREAD

**Issue by msacs09** [tableau/TabPy#488]
today  nothing changes from our end, but started getting this error. Tried re-install and still continue to get this error for all previously working models, any thoughts ??

`RuntimeError: LoadFailed: "Load failed: No module named 'tabpy_client'"`

**Comment by cwright98** [comment]
Hi! 
So I'm not a contributor or anything, but I have a suggestion that you could try:
use <from tabpy.tabpy_tools.client import Client> instead of what you have. I think I ran into a similar issue as you. Hope this helps!

**Comment by nmannheimer** [comment]
@msacs09 the suggestion @cwright98 is making here makes sense. You'll want to make sure you're following the latest instructions for using the tabpy_tools (formerly tabpy_client) feature which are described in the documentation of the project here under TabPy Tools.

**Comment by msacs09** [comment]
@nmannheimer @cwright98  Thank you for your input. Actually I completely un-installed and re-installed tabpy and now everything seem to work as earlier. However, should i get the same issue back i will try your suggestion and report back to you.  On the other note could you please help me on what's wrong with this issue please? https://github.com/tableau/TabPy/issues/485. I don't see any issues with the code, but it doesn't work??

**Comment by nmannheimer** [comment]
@msacs09 please see my response in that thread.
