### ISSUE TITLE
Issues with Enabling Extension on Tableau Server 2020.3.1

### ISSUE THREAD

**Issue by ascherer587** [tableau/TabPy#489]
Hi all,

We are trying to get TabPy integrated with Tableau on a company-wide scale.  We are trying to establish the connection when publishing workbooks made remotely with TabPy calculations to the Tableau Server. The following is an error message received when attempting to publish a test workbook:

![Post-PublishingError](https://user-images.githubusercontent.com/63651835/108116850-07c5d680-7051-11eb-933d-bbd9619de152.jpg)
  

The following image is the information that is provided from the instance on the Tableau Server's system: 
![image](https://user-images.githubusercontent.com/63651835/108116697-d2b98400-7050-11eb-811d-38909d335ffc.png)

Let me know if additional information is needed. I appreciate the help!

**Comment by 0golovatyi** [comment]
@ascherer587 Can you use the same TabPy with Tableau Desktop just to confirm on what side the issue is (Tableau Server or TabPy)?

**Comment by ascherer587** [comment]
Yes it works when I just use the same TabPy and Tableau Desktop.  We get this error only with Tableau Server.

**Comment by 0golovatyi** [comment]
@ascherer587 Is the screenshot above for when Tableau Server connects to TabPy or is it for Desktop?

**Comment by ascherer587** [comment]
The screenshot is from when a Desktop is connecting to the TabPy instance on the Tableau Server's system.

**Comment by 0golovatyi** [comment]
@ascherer587 What do you see in TabPy logs when Tableau Server is trying to connect?

**Comment by ascherer587** [comment]
I appreciate your help with this.  Is there a specific file that the TabPy log will be typically outputted to?  Not familiar with the TabPy folder structure and if there is some other log stored under the TabPy installation folder?

The following image shows the TabPy screen log on the Tableau Server side.  I am able to connect successfully to its extension but reach some error prior to publishing. 

![TabPy Screen Log ](https://user-images.githubusercontent.com/63651835/109041863-5b08dc00-7684-11eb-9713-3350fcd5e668.png)

**Comment by 0golovatyi** [comment]
@ascherer587 TabPy log file location specified in config file. If default config is used check for tabpy*.log in the folder where TabPy is started from.

**Comment by ascherer587** [comment]
I have attached the log files for TabPy. 

[tabpy_1_log.log](https://github.com/tableau/TabPy/files/6050137/tabpy_1_log.log)
[tabpy_2__log.log](https://github.com/tableau/TabPy/files/6050138/tabpy_2__log.log)

**Comment by 0golovatyi** [comment]
@ascherer587 From the first log file I see TabPy was never called. And second log shows TabPy calculation happened successfully once after which TabPy was restarted and never called again.

Can you even reach TabPy machine from you Tableau Server? You can check with `ping` command.

**Comment by ascherer587** [comment]
I plan to follow-up with this later this week.  Our developer thinks it might have something to do with the excessive memory usage we are currently using right now. She is getting the infrastructure team to double the memory to on the Server side this week.  As soon as this is accomplished, I will use the ping command that you suggested and report the results.

**Comment by ascherer587** [comment]
@0golovatyi In response to your question, TabPy is locally installed on the same system as Tableau Server.  It is being reached by the Tableau Server as the following image is coming from the TabPy instance on that machine: 
![2021-03-04_9-32-58](https://user-images.githubusercontent.com/63651835/110006017-f70e9500-7ccd-11eb-9f06-da8d14baaf51.jpg)

**Comment by 0golovatyi** [comment]
@ascherer587 from the log above I can tell there is no request received by TabPy. Did you try specify the host as `localhost` for the Server?

**Comment by xyang-axosbank** [comment]
@0golovatyi 
This is Xin, the tableau admin for @ascherer587 . This is the screen output of Tabpy server when we tried to connect to Tabpy using some dummy username/password suggested by Tableau customer support:

![tabpy screen log 03042021](https://user-images.githubusercontent.com/80069283/110026318-588e2e00-7ce5-11eb-8a66-648fb377e105.png)

**Comment by 0golovatyi** [comment]
@xyang-axosbank Is the log above for when you connecting to TabPy with Tableau Desktop or Tableau Server?

**Comment by xyang-axosbank** [comment]
when we connecting to TabPy with desktop

**Comment by xyang-axosbank** [comment]
I don't know how to connect to TabPy using Tableau server, as both are sitting on the same server (same IP)

**Comment by 0golovatyi** [comment]
@0golovatyi It means Tableau Server simply can't reach TabPy. Since you running TabPy on the same machine as Tableau Server you can try:
- ping the hostname used for TabPy by Tableau Server to see if Tableau Server can reach it at all
- use `localhost` when configuring connection on Tableau Server.

**Comment by xyang-axosbank** [comment]
![image](https://user-images.githubusercontent.com/80069283/110027969-82e0eb00-7ce7-11eb-80bf-04de73cc94da.png)

This is the configuration on Tableau server for TabPy: I'm using localhost

**Comment by 0golovatyi** [comment]
@xyang-axosbank screenshot at the very first comment shows a different hostname.

**Comment by xyang-axosbank** [comment]
Sorry, which hostname did you see in the "first comment"?

**Comment by 0golovatyi** [comment]
@xyang-axosbank this one:
https://user-images.githubusercontent.com/63651835/108116850-07c5d680-7051-11eb-933d-bbd9619de152.jpg

**Comment by xyang-axosbank** [comment]
it's the tableau server name. This is the only server we've been talking about. The TabPy is running on that sever.

**Comment by 0golovatyi** [comment]
This is getting confusing and to avoid misreading and misinterpreting I would like to reiterate what I got and how I understand so far:
- Tableau Desktop can reach TabPy running on `hostname`, Tableau Desktop uses `hostname` for connection.
- Tableau Server can't reach TabPy running on `hostname`, Tableau Server uses the same `hostname` for connection as Tableau Desktop.

If what is said above is correct the issue is in Tableau Server not being able to reach `hostname` where TabPy is running. Why is that happening - either `hostname` can't be resolved on the Tableau Server machine, or `hostname` is in a different network is something to confirm.

As I see it the issue is in the Tableau Server machine not being able to discover TabPy machine and not in Tableau Server or TabPy.

**Comment by xyang-axosbank** [comment]
Both TabPy (port 9004) and Tableau server (as a service) are running on hostname = bofi-TableauProd, internal IP = 10.50.55.88

I found the following output when using netstate:
![image](https://user-images.githubusercontent.com/80069283/110041995-e6741400-7cf9-11eb-9ae4-e976ee9bf86f.png)

It looks like TabPy is actively listening on port 9004

**Comment by ascherer587** [comment]
@0golovatyi, @xyang-axosbank was able to figure it out to get it to successfully connect.  She removed SSL as a requirement, and that did the trick for us.  We are excited to use this now, and I appreciate your help!
