### ISSUE TITLE
How to use the function after function deployment?

### ISSUE THREAD

**Issue by alamhanz** [tableau/TabPy#49]
I have successfully deploy the function.

`client.deploy('add_test', add_test, 'Adds test for two numbers x and y',override=True)`

but I can't import or use it in tableau. How do I use it exactly??

```
An error occurred while communicating with the Predictive Service.
Error processing script
NameError : global name 'add_test' is not defined
```

**Comment by BBeran** [comment]
You can find an example in the documentation here

https://github.com/tableau/TabPy/blob/master/TableauConfiguration.md#using-deployed-functions

```
SCRIPT_REAL("
return tabpy.query('add',_arg1,_arg2)['response']",
-SUM([Discount]),SUM([Price]))
```
You can find a detailed working example with a downloadable sample Tableau workbook showing how to publish models and use the published models in calculated fields on [our blog](https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916).

**Comment by alamhanz** [comment]
Alright thank you @BBeran but there is another problem,, the tableau can't find the endname

```
An error occurred while communicating with the Predictive Service.
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.
```

even though I've add the function to server..
```
u'add': {u'last_error': None,
  u'status': u'LoadSuccessful',
  u'type': u'model',
  u'version': 1}
```

**Comment by BBeran** [comment]
This is a generic error. So it could be failing because the code fails to run e.g. because incorrect arguments were passed. If you could share the add function definition and how you're calling it from Tableau (most importantly type of data being passed, aggregations used and what does the visualization look like?), we should be able to get to the bottom of this quickly.
