### ISSUE TITLE
Tabpy on Anaconda Enterprise running on kubernetes/Docker Container

### ISSUE THREAD

**Issue by msacs09** [tableau/TabPy#490]
Trying to run Tabpy on Anaconda Enterprise running on Containers.  We have installed Tabpy on a specific node, but the issue is how do we configure the hostname here on Tableau server, since the hostname of the session/container is not static and changes as the session restarts. Any advice on how to get this working on a container architecture ?

**Comment by 0golovatyi** [comment]
@msacs09 For each new TabPy instance you need to configure it again with host, port, SSL settings and credentials.

**Comment by msacs09** [comment]
@0golovatyi 

In Jupyter notebook I can type the command !tabpy to start a service manually

![image](https://user-images.githubusercontent.com/43424222/108552080-10ffaf00-72ae-11eb-88c7-15c9da748f9f.png)

How do i write this in the python.py script file, so that the script runs after environment is built? 

Below is what i have, which results in error

```
#!/usr/bin/env python
# coding: utf-8
get_ipython().system('tabpy')

2021-02-19T18:12:05.940946708Z Traceback (most recent call last):
2021-02-19T18:12:05.940961808Z   File "Tabpy_startup.py", line 8, in <module>
2021-02-19T18:12:05.941006819Z     get_ipython().system('tabpy')
**2021-02-19T18:12:05.941018769Z NameError: name 'get_ipython' is not defined**
```

**Comment by 0golovatyi** [comment]
@msacs09 I don't know what `get_ipython()` supposed to do and why it fails. It is not part of TabPy package.

**Comment by ChairmanMa0** [comment]
@msacs09 I think there are a few ways you can solve this at a system architecture level.
If you can add a self-hosted proxy, like nginx, in front of your container, you can use the proxy to hold a static IP or URL.
You could also route through AWS - Route53 for a custom URL, or just API Gateway (cheaper).
