### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by RandellK02** [tableau/TabPy#496]
Could TabPy be used with Python 3.9?
I am getting some errors and deprecation warnings

src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7614): error C2039: 'tp_print': is not a member of '_typeobject'
src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6146): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6164): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6182): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6509): warning C4996: 'PyObject_AsReadBuffer': deprecated in 3.0
...

**Comment by 0golovatyi** [comment]
@RandellK02 We never tested TabPy with Python 3.9 yet. It should be possible with minimal changes.

**Comment by tirkarthi** [comment]
This was removed in 3.10 : https://github.com/python/cpython/blob/e4f1fe6edb216e04da03ae80b462ca273f00255b/Doc/whatsnew/3.10.rst#removed-1

**Comment by nmannheimer** [comment]
Python 3.9 is now supported.
