### ISSUE TITLE
TableauException

### ISSUE THREAD

**Issue by henriquesglima** [tableau/TabPy#498]
Hi all.

Could someone help with this issue, please?

**Environment information:**
 - OS: Windows Server 2016
 - Python version: 3.8.5
 - TabPy release:  2.3.1
 - Tableau Server Version: 2020.2.10 (20202.21.0108.1605) 64-bit Windows
 - Tableau Desktop Version: 2020.2.10 (20202.21.0108.1605) 64-bit Windows

I have Tabpy running on the same machine as Tableau Server.
So I have setup the server as localhost, port 9004, no SSL yet but I have authentication.

![image](https://user-images.githubusercontent.com/1007319/110200678-baa17d00-7e24-11eb-88d4-d1c32561c48e.png)

It works and I'm able to run Tableau reports using Tabpy.
In Tabpy logs I see the requests received normally. And everything seems great!!

But often, really sporadically, I get 2 different errors:

- **- 1**

_Unexpected Server Error

TableauException: FAILED: RPC message=''. More details: monolith_grpc/getConnections reported Service encountered an unidentified internal error

2021-03-04 16:17:30.701

(YEEIGSWhOaU8oe0QblO9SwAAARA,1:0)_

![image](https://user-images.githubusercontent.com/1007319/110200371-37335c00-7e23-11eb-8bff-013e3468586a.png)

**- 2**

_Unexpected Server Error

TableauException: Failed to connect to analytics extension (ext-svc-type-tabpy localhost:9004): An error occurred while communicating with the analytics extension. Tableau is unable to connect to the extension. Verify that the extension is running and that you have access privileges.

2021-03-04 17:14:20.621

(YEEVaiWhOaU8oe0QblPeSgAAAQ8,1:0)_

**********************************

Those errors happen in some reports when applying some filters or changing dashboard views.
Sometimes, I just try again, either by refreshing the page, or selecting the filter or dashboard again, and then it works.

When I check Tabpy logs, it is like no requests were received at all. It does not show any error message or anything.

In Tableau logs, I have checked the log on folder 

E:\Tableau Server\data\tabsvc\logs\analyticsextensions\analyticsextensions_node1-0.log

And found this:

```
_2021-03-04 10:27:53.043 -0600 (1,henrique.lima,93335DE548994911BF87B3BF15090FF2-1:0,0:7d7e912:177fe05e45d:-53ad,0:7d7e912:177fe05e45d:-53ae) grpc-default-executor-931 analyticsextensions: INFO com.tableau.grpc.clientbuilder.RequestExecutor - Request for public com.tableau.analyticsextensionsdaogrpcservice.v1.ConnectionListMonolith com.tableau.analyticsextensionsdaogrpcservice.v1.AnalyticsExtensionsDaoGrpcServiceGrpc$AnalyticsExtensionsDaoGrpcServiceBlockingStub.getConnectionsMonolith(com.tableau.analyticsextensionsdaogrpcservice.v1.Empty) on localhost:8662 threw exception io.grpc.StatusRuntimeException: UNKNOWN

2021-03-04 11:08:02.481 -0600 (1,henrique.lima,56F168D158E241129AE8503D6B3E3E82-1:0,0:7d7e912:177fe05e45d:-2da,0:7d7e912:177fe05e45d:-2db) grpc-default-executor-971 analyticsextensions: ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7997d8bc

java.lang.NullPointerException

2021-03-04 11:14:19.180 -0600 (1,henrique.lima,56F168D158E241129AE8503D6B3E3E82-1:0,0:7d7e912:177fe05e45d:901,0:7d7e912:177fe05e45d:900) grpc-default-executor-982 analyticsextensions: ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@1714bf37

java.lang.NullPointerException_

```

I'm not really sure why this happens.
It should not be a communication problem because from Tableau server, I'm able to ping localhost and run telnet localhost 9004 normally.

When run in my own machine using Tableau Desktop and Tabpy, I dont have this issue at all. Everything works just fine.

Could someone help me on this?

**Comment by nmannheimer** [comment]
Hello @henriquesglima while we can look at this here, please also file a Tableau support ticket. This looks likely to be an issue with Tableau Server itself given the error, and we want to make sure we're tracking it. Thanks.

**Comment by henriquesglima** [comment]
> Hello @henriquesglima while we can look at this here, please also file a Tableau support ticket. This looks likely to be an issue with Tableau Server itself given the error, and we want to make sure we're tracking it. Thanks.

Hi nmannheimer .

Sure, I have raised a ticket to Tableau Support as well... I will inform here when I have any update from them.

**Comment by rxing-tableau** [comment]
It would be helpful if you can attach logs to the support ticket as well.
If you are running Tableau Server on Windows, you can find the logs at 
C:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs
If Linux, you can find them at
/var/opt/tableau/tableau_server/data/tabsvc/logs/

**Comment by nmannheimer** [comment]
@henriquesglima any update on this?

**Comment by henriquesglima** [comment]
HI @nmannheimer 
I have this ticket opened to Tableau support since I have postes this thread (about 3 weeks now) . No response from them yet.
I had a meeting with the sales representative last Friday and he said he would follow up with this issue with the support team.

Im hoping to have an update later this week.

**Comment by henriquesglima** [comment]
Hi all.

Looks like this is really a Tableau issue. Tableau standard support takes really long to address anything.

The response I got is below.

I think we can safely close this as the issues relies on Tableau side, not tabpy.

"
Thank you for reaching out to the Global Escalations team and providing the exception for these two cases. 


I have marked both cases for escalation and they will be assigned to engineers in their respective queues. There are currently several other escalations ahead of this one in the queue so assignment may be delayed. 


I will also message the other email for tracking purposes. Please let us know if you have any questions or concerns!"

**Comment by henriquesglima** [comment]
An updated from Tableau Support after analyzing the logs I have sent to them.


> I wanted to follow up with some of my findings from your logs. I noticed from your logs that you have large spikes in your CPU from Tableau Server. From the screenshot of your Tableau Analytics extension configuration settings, it appears that you are also running the analytics extension locally on localhost port 9004. Given that Tableau Server and Tableau analytics extension for TabPY are running on the same machine, it is possible that this is a resource contention issue that may be causing the connections to the analytics extension  to fail.
> 
> I am attaching a Tableau Workbook that shows the CPU usage of Tableau Server from the logs that you had generated. CPU usage frequently reaches to near 100% capacity, which could be an issue if the Analytics extension also needs computer resources to run.
> 
> One suggestion for how to test this would be to host the Tableau Analytics extension on a different server from Tableau Server (being sure to adjust the configuration accordingly). Does separating the analytics extension to a different machine help mitigate this intermittent issue?


So I will try having a separate server to run Tabpy and see if that fixes the issue.
Will update here once done, but It might take some time as I have requested the infra team from my company to build the server.
