### ISSUE TITLE
SSL Authentication Issue with Tableau Online

### ISSUE THREAD

**Issue by DuttSahil** [tableau/TabPy#503]
**Environment information:**
 - OS: Windows Server 2016
 - Python version: 3.9.4
 - TabPy release: 2.3.2

Issue when trying to integrate with Tableau online and our own instance of Tabpy, we are trying to accomplish this on our end with authentication and getting the following issue below:

> An` error occurred while communicating with the Analytics Extension.
> {"message":"javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}}

We have done the following:
- ingested the chain cert into the OS on the machine hosting tabpy.
- we've specified the cert and key through TabPy configuration and that Desktop instances can connect while forcing SSL
- Confirmed Basic Access Authentication working through Desktop as well (e.g. user/pass)
- essentially validated with all required features through Desktop

Additional note:
- We are using GoDaddy cert.
- Can confirm that machine hosting tabpy has access to the internet and is configured for traffic on the IPs used by Online
- ports 443, 9004 are externally available on host machine

**Comment by scallybrian** [comment]
I am having the exact same issue - would appreciate an update!

**Comment by dleskosky** [comment]
Hi @DuttSahil and @scallybrian.  I believe that the issue  is that you ingested the chain cert into the OS for the machine that is hosting TabPy.  You need to put the [cert into a directory](https://github.com/tableau/TabPy/blob/master/docs/server-config.md#configuring-http-vs-https) and then specify the absolute path to the cert and key file in your TabPy config file.

Please also note that TabPy requires a full cert chain in the cert file that is located at the path specified in the TABPY_CERTIFICATE_FILE config setting.

Please let me know if this works for you.

**Comment by nmannheimer** [comment]
@DuttSahil and @scallybrian I'm going to close this issue for now, feel free to re-open if needed.

**Comment by corngk** [comment]
@dleskosky I am having same issue now. I have followed your instruction with no luck. 
I can access the tabpy server from my Tableau Desktop. I can also open it from browser without problems. Somehow the Tableau online server have difficulties finding the certificate file.

**Comment by corngk** [comment]
Hi @dleskosky thanks for your reply!

I mean I can open the tabpy server (https://tabpyserver.xxx:9004) from a browser and I can see the tabpy page with no problem. I can login from the page successfully. I see no error in the log screen.

The error I got is exactly same with @DuttSahil :
An error occurred while communicating with the Analytics Extension.
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by dleskosky** [comment]
Hey @corngk!  Try doing what they describe [here](https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find) and see if that helps at all.
