### ISSUE TITLE
Query related TabPy

### ISSUE THREAD

**Issue by amit-mittal-ds** [tableau/TabPy#504]
Hi,

I have few queries related use of TabPy

**Tableau Server**
1. If the workbook lives on Tableau Server then is it necessary to have Python and other dependencies installed on the system for everyone who wants to see those viz via server?

2. Do we need to install python libraries on Tableau Server also to run those scripts?

**General**
If I integrated Python with Tableau on Desktop app and created a calculated field based on python script and send that file to another person. Is it necessary for other person also to have those dependences installed on his system to view those viz?
Like - TabPy, Libraries used in Script, and TabPy server running

Thanks

**Comment by cgore1** [comment]
TabPy is used to remotely run python code, so the dependencies have to be installed on TabPy server side.

For tableau server, the recommended way is to have a separate machine for TabPy, so dependencies will be installed only on TabPy machine and not the tableau server.

In case of Tableau desktop though, you most likely have TabPy on local machine. Then the dependencies will have to installed on local machine.
