### ISSUE TITLE
Measure from previous month shown in this month

### ISSUE THREAD

**Issue by Jeromevb** [tableau/TabPy#505]
I am looking to write a script or function that takes a measure and shows the sum of this measure from month-1 in month0.

For example: I want to create a calculated field that returns the sum of sales from December 2020 to be shown in January 2021. From January 2021 to be shown in February 2021, etc. etc. etc.

I am using latest version of Tableau and TabPy. I am new to using TabPy.

**Comment by nmannheimer** [comment]
Hello, I think what you’ll want is actually the LOOKUP() function in tableau:

https://help.tableau.com/current/pro/desktop/en-us/functions_functions_tablecalculation.htm#lookupexpression-offset

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jeromevb ***@***.***>
Sent: Tuesday, May 25, 2021 8:47:46 AM
To: tableau/TabPy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tableau/TabPy] Measure from previous month shown in this month (#505)


I am looking to write a script or function that takes a measure and shows the sum of this measure from month-1 in month0.

For example: I want to create a calculated field that returns the sum of sales from December 2020 to be shown in January 2021. From January 2021 to be shown in February 2021, etc. etc. etc.

I am using latest version of Tableau and TabPy. I am new to using TabPy.

**Comment by Jeromevb** [comment]
Hi nmannheimer, thanks for your reply.

I am indeed looking for the outcome represented by the LOOKUP()/PREVIOUS_VALUE function. The only problem I am running into is that I don't want to show or hide the last month in the table. For example I want to show values in January, February, March. Based on Sales in December, January, February, but I don't want to show/hide the month December in the view. Is there a solution for this?

**Comment by nmannheimer** [comment]
This is out of scope for the TabPy github and a better question for Tableau support so I'm going to close.
