### ISSUE TITLE
Tabpy installed but is not launching using the tabpy command

### ISSUE THREAD

**Issue by Mauliklm10** [tableau/TabPy#506]
Just as the description states, I did pip install tabpy and all the requirements were satisfied but htne in the next line I try running tabpy and I get the following error: "'tabpy' is not recognized as an internal or external command, operable program or batch file." So then I downlaoded this folder and then in the prompt I typed "cd pathname_to_tabpy-master" I press enter and then type in startup.cmd and I get the same error:"'tabpy' is not recognized as an internal or external command, operable program or batch file." Any help will be greatly appreciated! Thank you

**Comment by MaxwellLi-Umich** [comment]
I would make sure that your pip is up to date! I have a co-worker that had a similar problem and that seemed to solve it. 

python -m pip install --upgrade pip     

you can also check what version with pip --version (should be 21.1.3 I believe, anaconda came installed with 20. something)

**Comment by 0golovatyi** [comment]
@Mauliklm10 Another reason could be your pip and python are from 2 different installations. To confirm that you can run something like `where pip` and `where python` to confirm if both are from the same folder.
