### ISSUE TITLE
tabpy limits documentation 

### ISSUE THREAD

**Issue by yair4Data** [tableau/TabPy#509]
i am wondering what is the limitation that tabpy has for size of data itself (number of rows/actual memory size) , and number of arguments (columns) it can pass (i think there is a limit to up to 99 arguments)
i see no documentation of that.

**Comment by chaz-clark** [comment]
Here is some documentation on what you can control, it might not have variables listed but it's what is available, I have used it to expand some resources for large processing files that take hours to process.

https://github.com/tableau/TabPy/blob/master/docs/server-config.md

**Comment by nmannheimer** [comment]
@yair4Data as @chaz-clark notes, changing the max request size and timeout limits can control how TabPy handles larger data. There is not a hard limit enforced on the TabPy side.
