### ISSUE TITLE
TabPy is slow

### ISSUE THREAD

**Issue by cdorignac** [tableau/TabPy#51]
When I pass data to TabPy, I wait 10s before to start to excute the python function. This time increases when I pass more data from Tableau to TabPy. It is normal ? What do I do to reduce this time?

**Comment by BBeran** [comment]
Hi,
Most likely problem is that too many requests are being sent to the server. Please update table calculation settings by right clicking on the pill (in the sheet) containing the SCRIPT_ calculation, selecting "Edit Table Calculation", picking the "Specific Dimensions" option and making sure all the boxes in the specific dimensions list is checked. If none of the items are checked, this means Tableau will make a separate request for each data point which may mean hundreds of thousands of requests if you have a decent size dataset. By checking all the boxes, you will be sending all data in a single request as a column of data.

You can find a longer description of how data is exchanged between Tableau and TabPy here on TabWiki.

https://community.tableau.com/docs/DOC-10856

especially in the section titled "Exactly what is sent to Python"

Please give it a shot and let us know if it solves the problem.

Thanks,

Bora
