### ISSUE TITLE
Tableau Prep not connecting to Docker

### ISSUE THREAD

**Issue by morganandsam** [tableau/TabPy#511]
**Environment information:**
 - OS: Mac BigSur 11.4
 - Python version: [e.g. 3.6.5]
 - TabPy release: [e.g. 0.4.1]

**Describe the issue**
Tableau Prep throwing this error on the script: Unable to connect to the Tableau Python (TabPy) server local on port 80. Check your connection details and credentials, then try again.

**To Reproduce**
Input sales data, concatenate address to single field, aggregate the address column, geo-code script (throws error), re-append sales data and then output the file. 

**Expected behavior**
Expect script to run to produce the output file. 

**Screenshots**
![Tableau Screenshot](https://user-images.githubusercontent.com/87539630/125978591-5f2fb12e-6336-471e-b75b-d82bb1653cc1.png)

**Additional context**
Docker is running and is up to date. Seems to be working but when we open a flow in Tableau Prep, we get errors that it's not connecting.

**Comment by nmannheimer** [comment]
Hello @morganandsam what port is your TabPy instance running on? The default port for TabPy is 9004 which may explain the issue if Prep is trying to use port 80.

**Comment by nmannheimer** [comment]
@morganandsam I'm going to close this issue, feel free to re-open if needed.
