### ISSUE TITLE
deploy models from tabpy on Heroku

### ISSUE THREAD

**Issue by Quoctran1985** [tableau/TabPy#513]
**Environment information:**
 - OS: [Windows, Linux, Mac] and version
 - Python version: [e.g. 3.6.5]
 - TabPy release: [e.g. 0.4.1]

**Describe the issue**
I try to use this command "tabpy-deploy-models" on heroku but I got this error: 

"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9004): Max retries exceeded with url: /endpoints (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fde39e7ddf0>: Failed to establish a new connection: [Errno 61] Connection refused'))

I wonder how could we deploy the model here.
**To Reproduce**
Steps to reproduce the behavior: what commands to run, what files to modify, where to look for an error.
1. Login to Heroku
2. Open the Heroku command
3. Type "tabpy-deploy-models"
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nmannheimer** [comment]
Hello @Quoctran1985, currently TabPy does not support the remote deployment of models which means this is not possible with Heroku. This is something we are actively exploring improving and we may have a solution in the future.

**Comment by dleskosky** [comment]
A feature request has been filed for this on [a separate occasion](https://github.com/tableau/TabPy/issues/64), so this issue will be closed.
