### ISSUE TITLE
Calculation trigger for tabpy script

### ISSUE THREAD

**Issue by klar-C** [tableau/TabPy#519]
Hi,

This might go into the realm of Tableau itself but the issue is directly related to TabPy.

I'm using TabPy to run a rather long calculation to get some coordinates. Additionally (once the graph is drawn) I have some parameters that toggle the color of edges and set tooltip details.

The problem is that every time I change the parameter (even though the graph itself is not supposed to change) it redraws the entire graph (which causes a lag due to the calculation time). I tried the table calculation settings but had no luck there.

Has someone come across this issue and was able to fix/work around it?

I'm using 2021.2.1 and TabPy 2.4.0.

Regards

**Comment by nmannheimer** [comment]
Hi @klar-C, you might be able to solve this by create an on/off parameter tied to a calculation with and if/else logic in it. If the parameter is set to off, the calculation returns a constant value. If it is set to on, the calculation evaluates as the script calc. That way you could set the parameter to off, make any changes, then set it to on and have your code evaluate.

Longer term, we are working on a feature to materialize who tables of data from TabPy that should resolve this issue with a caching layer.
