### ISSUE TITLE
Python calls the Java code, and then calls the Python program using TabPy. The first calculation succeeds, and when it is recalculated, the table is computed, and then the Python will hang up.

### ISSUE THREAD

**Issue by zhanju** [tableau/TabPy#52]
Python calls the Java code, and then calls the Python program using TabPy. The first calculation succeeds, and when it is recalculated, the table is computed, and then the Python will hang up.

SCRIPT_STR("import jpype
import os.path
jarpath = os.path.join(os.path.abspath('.'), 'E:/resource/test.jar')
if not jpype.isJVMStarted():
    jpype.startJVM(jpype.getDefaultJVMPath(),'-ea', '-Djava.class.path=%s' % jarpath)

jprint = jpype.java.lang.System.out.println
JDClass = jpype.JClass('com.Utils')
a = JDClass()

text = a.encryptData_ECB(_arg[0])

return text",ATTR([细分]))

**Comment by nmannheimer** [comment]
Hi @zhanju,

Are you still having this issue with your code?
