### ISSUE TITLE
how to publish the workbook from jupyter and see the endpoint 

### ISSUE THREAD

**Issue by rgupta2017** [tableau/TabPy#54]
hi 

I am working on the demo sample of the post of Beran 
https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916

i am able to see the python book in jupter but how do i deploy it to tabpy server . When i run i dont see any errors but when i see the endpoints it is not there 
http://localhost:9004/endpoints
when i run the endpoint command it asks me to open a json file .
Can you help me what steps i am doing wrong to publish the python workbook 

thanks
Rakesh

**Comment by BBeran** [comment]
When model training fails, you can still publish a function to TabPy server but the error will surface when you try to run the model.

On some Windows machines, this could happen due to a bug in Python when you try to run model fitting by using all the CPU cores you have. This is controlled by the "n_jobs=-1" setting in the Jupyter workbook. I suspect this might be the issue.

The solution would be to set n_jobs=1 which will run the training using only a single core. After making this, if you add the argument override=True to your deploy function then run the entire Jupyter workbook (Cell > Run All) I suspect it might fix it.

Can you give this a shot and see if this addresses it and reactivate this issue if it doesn't?

**Comment by rgupta2017** [comment]
beran ,

i am able to publish and can see the endpoint now . but i see the following errors when i am tryng to run it from tableau. my code is a copy of correlation coeeficient example .

below is the code 👍 

import numpy as np
import tabpy_client
sales = 4100000
profit = 14350
#print ("coeereltion component")
#print np.corrcoef([sales,profit]).tolist()
#print("Aucroc: %0.3f" % np.corrcoef({sales},{profit}))
connection = tabpy_client.Client('http://localhost:9004/')
def coffcor(X,Y): 
 Z = np.corrcorf([X],[Y])
 return Z.astype(np.float64).tolist() 
connection.deploy('coffcor',
              coffcor,
              'returns correlated coefficient .',override = True)

**Comment by BBeran** [comment]
Would you be able to share the error message?

**Comment by rgupta2017** [comment]
This is the error I get : I do see the endpoint in staging folder …

•  An error occurred while communicating with the Predictive Service.
•  Error processing script
•  The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

Thanks
Rakesh

**Comment by BBeran** [comment]
I would recommend taking a look at this https://github.com/tableau/TabPy/issues/33
When your correlation coefficient code follows this example and addressing/partitioning settings are correct and NULLs are either filtered out or handled as part of Python code, are you still getting an error?

**Comment by rgupta2017** [comment]
Beran ,

i still see that error . i am using the same partitioning which is in sample for inline example of customer id .
the code works for inline sample but fails for endpoint .

Rakesh

**Comment by BBeran** [comment]
There seems to be issues in the Python code. For example, there is missing indentation in function definition which would break the code. Secondly numpy has no function named `corrcorf`, the correct function name is `corrcoef`

With these corrections following code works without any errors.

```python
import numpy as np
import tabpy_client
connection = tabpy_client.Client('http://localhost:9004/')
def coffcor(X,Y):
    return np.corrcoef([X],[Y])[0,1]
connection.deploy('coffcor',coffcor,'returns correlated coefficient.',override = True)
```
You can call it in the following form from Tableau

```
SCRIPT_REAL('return tabpy.query("coffcor",_arg1,_arg2)["response"]', SUM([Sales]),SUM([Profit]))
```

**Comment by rgupta2017** [comment]
Thanks Beran ,

This code works perfectly .. This was our sample before we try the next endpoint . our actual requirement is to decrypt an encrypted  field in postgress DB and show it in tableau .

We have following code which works as a batch and I am trying to create an endpoint for it :
This code works up to point where we are creating a session . it fails at that point . at a high level do you see any issue at this line and in the code :
SESSION = AWS_FED.get_boto3_session(idp_url=IDP_URL, username=USERNAME, password=USER_PASSWORD, assume_role=ROLE)

-----------------------
from test.aws import Federation
from subprocess import PIPE,Popen
#from datetime import datetime,timezone
import os
import os.path
import gzip
import sys
import io
import pdb
import argparse
from pprint import pprint as pp
from botocore.client import Config
import base64
import configparser
import aws_encryption_sdk
import botocore.session
import psycopg2
import base64
import logging
logging.basicConfig(filename='d:\decryptaws.log',level=logging.DEBUG)
import tabpy_client
client = tabpy_client.Client('http://localhost:9004/')
#config = configparser.RawConfigParser()
#config.read('c:\temp\config.properties')
def decrypt_aws(enc_str):
 IDP_URL = 'https://sts.test.com/adfs/ls/idpinitiatedsignon.aspx?loginToRp=urn:amazon:webservices'
USERNAME = 'test\\test123'
USER_PASSWORD = 'ttttttt'
PROXY_HOST = 'zsproxy.test.com'
PROXY_PORT = '11111'
PROXY_USERNAME = USERNAME.split('\\')[1]
ROLE = 'DEVL--DATA-TEST'
 #print("IDP_URL "+ IDP_URL)
#print("USERNAME : "+USERNAME)
#print("PASSWORD : " + USER_PASSWORD)
#print("PROXY HOST" + PROXY_HOST)
#print("ROLE : " +ROLE)
#print("Proxy User Name: "+PROXY_USERNAME)
PROXY_URL = 'http://' + PROXY_USERNAME + ':' + USER_PASSWORD + '@' + PROXY_HOST + ':' + PROXY_PORT + '/'
logging.debug("Proxy URL 123" + PROXY_URL)
AWS_FED = Federation(proxy_url=PROXY_URL)
SESSION = AWS_FED.get_boto3_session(idp_url=IDP_URL, username=USERNAME, password=USER_PASSWORD, assume_role=ROLE)
account_id = SESSION.client('sts').get_caller_identity()['Account']
credentials = SESSION.get_credentials()
current_credentials = credentials.get_frozen_credentials()
access_key = current_credentials.access_key
secret_key = current_credentials.secret_key
token = current_credentials.token
existing_botocore_session = botocore.session.Session()
existing_botocore_session.set_credentials(access_key=access_key, secret_key=secret_key,token=token)
master_key_provider = aws_encryption_sdk.KMSMasterKeyProvider(botocore_session=existing_botocore_session)
master_key_provider2 = aws_encryption_sdk.KMSMasterKeyProvider(botocore_session=existing_botocore_session)
decrypted_plaintext = aws_encryption_sdk.decrypt(source=enc_str,key_provider=master_key_provider2)
 return decrypted_plaintext
client.deploy('decryptedaws',decrypt_aws,'Returns a decrypted string', override=True)


thanks
Rakesh
