### ISSUE TITLE
Can't install tabpy-tools

### ISSUE THREAD

**Issue by AndreySivyakov** [tableau/TabPy#544]
- OS: Windows 10
 - Python version: 3.7.9
 - TabPy release: 2.5.0

I can't install tabpy-tools. I cloned the repo locally and ran `pip install -e tabpy-tools`, but got the following error
![image](https://user-images.githubusercontent.com/35407339/155456399-ac5ddf92-ccc3-4208-9150-82d668a75f10.png)

**Comment by 0golovatyi** [comment]
`tabpy-tools` is part of `tabpy` package, here are installation instructions - https://github.com/tableau/TabPy/blob/master/docs/server-install.md. For how to use `tabpy-tools` read https://github.com/tableau/TabPy/blob/master/docs/tabpy-tools.md

**Comment by AndreySivyakov** [comment]
Thank you @0golovatyi for the quick response! I just realized I was incorrectly importing the package in jupyter notebook. Thanks again!!!!
