### ISSUE TITLE
Broken Link on https://tableau.github.io/TabPy/

### ISSUE THREAD

**Issue by CaptCorpMURICA** [tableau/TabPy#545]
The hyperlink for [Tableau Sci-Fi Blog](http://tabscifi.com/) on the **Other Useful Resources:** section is broken. The original website no longer exists. A personal copy of the original blog can be found at this link: http://tabscifi.golovatyi.info/.

**Comment by nmannheimer** [comment]
fixed with a temporary solution while we consider next steps, thanks for raising.
