### ISSUE TITLE
TabPy - Dimension Index

### ISSUE THREAD

**Issue by robi7484** [tableau/TabPy#55]
Hi,

I'm trying to convert a tableau dimension (string) e.g. Small, Medium, Large etc... into a measure (int) 
e.g. 10, 20, 30 etc...depending on some background code, however I keep getting the error : "The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided". I have only one input argument Attr(Dimension) the size but not sure how to convert this and return it to tableau in the correct format. Can you please clarify how the dimension arrives in python (what format etc?) and what needs to be done to: 

1) convert categories to numbers
2) convert the format from string to int/float; and 
3) put this output into the correct format so python can read it.

Apologies if this sounds like a simple problem, I'm still new to this TabPy stuff!

Great work by the way!!!

Cheers,
Robi

**Comment by BBeran** [comment]
Hi Robi,
Quick question, what do you see if you drag ATTR(Dimension) into the view by itself?
The issue could be that you are passing a column of Nulls to Python because ATTR() returns *. The solution would be to include Dimension itself in the view as a dimension and select Edit Table Calculation in the context menu for the pill containing the Python calculation and make sure you have selected that Dimension in the specific dimensions list in the Table Calculation dialog.

Could you please give this a try and let me know if it solves the problem?

~ Bora

**Comment by robi7484** [comment]
Hi Bora,

Cheers for getting back to me...

Your solution above has worked! However, the only problem with this is the calculation time when solving the issue this way... Even for only 55 rows of data running through an extract it takes over 15s to perform the calculation! And I am hoping to use 10,000's of data!!!

Is there no way of returning a measure array back to tableau when sending an attr(dimension) and performing the conversion mentioned above???

I have published a function to the server which does this indexing of the variables and called it within python - giving the output required. However, I can't use this as a measure in tableau. Is there no way of returning a non attr(dimension) variable when sending an attr(dimension)?

This would solve my problem!!!

Thanks,
Robi

**Comment by BBeran** [comment]
The most likely reason is the table calculation's addressing settings.

If you select Edit Table Calculation in the context menu for the pill containing the Python calculation and make sure everything in the specific dimensions list in the Table Calculation dialog is checked it will probably run faster.

Tableau makes a separate call to Python for each partition in the visualization. E.g. if you have a dimension like State and it is not checked in the Table Calculation's  specific dimension list, Tableau will make a separate call to Python per state. That would be data sliced into 50 separate calls to Python. If you check State it will send all States in taller table in a single call.

Could you give this a shot and see if it solves the problem?

**Comment by robi7484** [comment]
Hi Bora,

Sorry about the late response, have not had a chance to look at his until now...

Thanks for this, have got the processing time down to just a few seconds for 34,000 rows of data!

My visualisations are still quite simple so not sure if they will slow down when they become more complex, but I guess we'll see.

Cheers for taking the time to look at this, much appreciated.

Robi

**Comment by BBeran** [comment]
I am glad it worked.
