### ISSUE TITLE
support customize  total 

### ISSUE THREAD

**Issue by kemistep** [tableau/TabPy#552]
i have more index ,i want to summary Compound growth rate 

i can summary  index  Compound growth rate  one by one ,but this is ineffective 

so i want to help 

[计算复合年增长率 | Tableau Software](https://kb.tableau.com/articles/howto/calculating-compounded-annual-growth-rate?lang=zh-cn)

**Comment by nmannheimer** [comment]
Unfortunately we can't help support code directly here, but this link may help: https://interworks.com/blog/mbingham/2018/10/05/how-to-calculate-xirr-in-tableau-with-python/
