### ISSUE TITLE
Could not find a version that satisfies the requirement tabpy (from versions: none)

### ISSUE THREAD

**Issue by sudaymadhav** [tableau/TabPy#554]
**Environment information:**
 - Windows 2008
 - Python version: 3.10.0
 - TabPy release: [e.g. 0.4.1]

**Describe the issue**
ERROR: Could not find a version that satisfies the requirement tabpy (from version : none)

**To Reproduce**
run tabpy command
Could not fetch URL https://pypi.org/simple/tabpy/: There was a problem confirmi
ng the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retr
ies exceeded with url: /simple/tabpy/ (Caused by SSLError(SSLError(1, '[SSL: WRO
NG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))) - skipping
ERROR: Could not find a version that satisfies the requirement tabpy (from versi
ons: none)
ERROR: No matching distribution found for tabpy

**Expected behavior**
tably failed to install on top of python 3.10.0

**Screenshots**

**Additional context**

**Comment by nmannheimer** [comment]
TabPy currently does not support Python 3.10. 

This is something we're interested in doing shortly.

**Comment by nmannheimer** [comment]
To mitigate in the short term, I'd recommend using Python 3.9
