### ISSUE TITLE
 TabPy. null error in prep flow

### ISSUE THREAD

**Issue by tb582** [tableau/TabPy#556]
I get this error in tableau prep 2022.1.2
System error: Unknown Error when setting up request to TabPy. null

tabpy logs running locally
```
2022-06-14,16:02:19 [INFO] (base_handler.py:base_handler:115): function to evaluate=def _user_script(tabpy, _arg1):
<my py file>
execution_result = cuecompare(pd.DataFrame(_arg1))
 return execution_result.to_dict(orient='list') if isinstance(execution_result, pd.DataFrame) else execution_result
, <<call ID: 38505919-ca65-48a3-aa1c-e9d2efb40704>>
2022-06-14,16:02:19 [INFO] (web.py:web:2239): 200 POST /evaluate (127.0.0.1) 81.94ms
```

then it just hangs at the last line.

**Comment by nmannheimer** [comment]
How large is the dataset you're passing? 

I'd also suggest filing a support ticket with Tableau.

**Comment by tb582** [comment]
not sure how to tell but in theory fairly large 100K rows

**Comment by nmannheimer** [comment]
The first thing I'd try is setting the timeout parameter much higher in TabPy, it may be timing out.

**Comment by nmannheimer** [comment]
Is Prep crashing or just hanging?

**Comment by tb582** [comment]
> Is Prep crashing or just hanging?

Just hung with the error - I can still do things in prep it’s just not getting a good response from tabpy

**Comment by nmannheimer** [comment]
Can you try filtering the dataset to something small like 5k rows and see if that works?

**Comment by tb582** [comment]
> Can you try filtering the dataset to something small like 5k rows and see if that works?

good idea - I tried 5K, 500, and 5 - all resulted in the same error 

`System error: Unknown Error when setting up request to TabPy. null`

yet I have no issue when calling the same function tabpy calls outside of prep

**Comment by tb582** [comment]
> Can you confirm even a basic call to TabPy works from your Prep setup, like running a function to add 2 columns together?

yes as I have another script in the same flow that works fine.

**Comment by nmannheimer** [comment]
This seems like there may be an error running with this code specifically then, which is hard to comment on.
