### ISSUE TITLE
run tabpy in debug

### ISSUE THREAD

**Issue by tb582** [tableau/TabPy#558]
When running tabpy locally from terminal is there a way to run it in an enhanced debug mode? Some sort of startup flag or option?

**Comment by tb582** [comment]
I've read the docs here: 
https://tableau.github.io/TabPy/docs/server-config.html#logging

but it seems like prep when it calls my script the tabpy log/console just sits on `/evaluate method` is there a way to see more details with what exactly prep and or tabpy is doing during this /evaluate call ?

**Comment by nmannheimer** [comment]
There is an option in the config to increase the verbosity of the logging, but that will only log what TabPy is doing, not Prep.
