### ISSUE TITLE
Can't connect Tableau Online to tabpy

### ISSUE THREAD

**Issue by fernandogc1** [tableau/TabPy#559]
**Environment information:**
 - OS: Windows Server 2016
 - Python version: 3.9
 - TabPy release: 2.5

I am trying to publish a workbook which is using TabPy server running on localhost and working fine localy. The calculation/result returning from python script is correct as expected.

While publishing this dashboard to tableau online its throwing error

**"this worksheet contains scripts for an external service which are not allowed on target platform until administrator configures as External Service Connection."**

I followed the steps presented here: https://tableau.github.io/TabPy/
Any lead or help is appreciated.

![tabpy](https://user-images.githubusercontent.com/60721525/182444825-ed0f4be9-7487-4098-b04f-0ec425819802.png)

The workbook (on tableau online) has the tabpy conection:
![image](https://user-images.githubusercontent.com/60721525/182448532-f1a707cb-673f-4eae-9e82-9cd091ebd4d7.png)

Successful connection on Desktop. Return a value (175.0 as expected)

![image](https://user-images.githubusercontent.com/60721525/182448226-ea02310f-bd3d-471b-af69-b4780f85cfc9.png)

**Comment by 0golovatyi** [comment]
@fernandogc1 You need to configure you Tableau Server you are publishing to enable scripting and with connection to TabPy, e.g. http://tabscifi.golovatyi.info/2020/05/multiple-analytics-extensions-connections-with-tableau-server-2020-2/

**Comment by fernandogc1** [comment]
@0golovatyi 
I already done the configuration. 
I tried with my local ip and writting "localhost" at hostname
![image](https://user-images.githubusercontent.com/60721525/182923728-95ff4d09-bdbd-4ace-a73e-db0df99ecc94.png)

**Comment by nmannheimer** [comment]
Your connection needs to be accessible over the open internet for Tableau Online, Using localhost won't work. If you can go to your IP on your port (9004) over a browser in another computer, that should be working.
