### ISSUE TITLE
Startup.bat: (Path) Not expected at this time

### ISSUE THREAD

**Issue by mattb112885** [tableau/TabPy#56]
Greetings,

I'm running Windows 7 Professional SP1 with Python 2.7.10. I had Python installed already (and am using it with other programs) so used the pip install method to install the latest version of tabpy.

My pre-existing PYTHONPATH variable is as follows:

C:\Program Files (x86)\ArcGIS\Desktop10.0\arcpy\arcpy;C:\Program Files (x86)\ArcGIS\Desktop10.0\arcpy;C:\Program Files (x86)\ArcGIS\Desktop10.0

When trying to run the startup.bat I got the following error:

\ArcGIS\Desktop10.0\arcpy\arcpy was unexpected at this time

I was able to fix by adding quotes around the existing %PYTHONPATH% variable in the batch script. 

@SET PYTHONPATH="%PYTHONPATH%";%CD%

Does this look like a reasonable fix? \ should I submit a PR? I don't know why (or if) it works correctly without putting quotes around %CD% or the other variables, so I'm a bit hesitant.

Thanks and best,

Matt

**Comment by 0golovatyi** [comment]
@mattb112885 if I understand your question correctly it looks like the fix you have solves the problem with spaces in path. Quotes are telling space characters in the string are part of the string and not separators for different strings.

**Comment by nmannheimer** [comment]
Closing this issue since it appears to be resolved.
