### ISSUE TITLE
Linux Deployed Model Get JSONDecodeError

### ISSUE THREAD

**Issue by Proteusiq** [tableau/TabPy#57]
Problem:

I have deployed a function via Jupyter Notebook that takes in texts and returns  1 for positive and 0 for negative sentiment both on localhost and a remote server. This endpoint works when I connect Tableau to my localhost server but return JSONDecodeError when connected to the remote server.

It works well when I call it within remote server but not when I call it from Tableau.

![image](https://user-images.githubusercontent.com/14926709/30260702-39b1b9b2-96c9-11e7-84e1-c915d63a3bda.png)

**Test Environments: TabPy Running on Python 3.6**
**Success:**
Windows 7 
Tableau 10.2 calling the query on LocalHost server
Jupyter Notebook running on Red Hat Enterprise Linux Server 6.8 calling the query

**Failure:**
Tableau 10.2 calling the query deployed on Red Hat Enterprise Linux Server 6.8

![image](https://user-images.githubusercontent.com/14926709/30260374-47d62552-96c7-11e7-922b-f445063a2b38.png)

**Comment by BBeran** [comment]
Hi,
What do you see when you drag ATTR([EffortComment_]) by itself into the same sheet without the SCRIPT calculation. 

If you're seeing * that's the problem. * will be sent as NULL to Python.

To work around this drag EffortComment itself as a dimension into the same viz. Right click on SCRIPT calculation in the visualization, Edit Table Calculation -> Specific Dimensions then check all the boxes in the box.

Please let me know if this doesn't address the problem.

Thanks,

Bora

**Comment by Proteusiq** [comment]
Hi Bora. It is not attribute issue, if you meant ATTR behavior IIF(MAX([X])=MIN([X]), MIN([X]), '*'), when there multiple entries.

The query runs when I change from remote server to localhost server. My guess is the encoding issue: https://docs.python.org/2/library/json.html

**Comment by nmannheimer** [comment]
Hello @Proteusiq,

Are you still experiencing this issue with the current version of TabPy?
