### ISSUE TITLE
SCRIPT_REAL unsupported function

### ISSUE THREAD

**Issue by ayyboddu** [tableau/TabPy#572]
I'm trying to deploy a python model using tabpy.query. Below is the code i'm using but it keeps throwing this error. Not sure how to fix this. I've tried to add the script directly to tableau desktop but that's also throwing an EOL syntax error. please help, i'm new to this. Thank you very much!

<img width="1365" alt="Screen Shot 2022-12-03 at 1 13 37 AM" src="https://user-images.githubusercontent.com/67741733/205462730-5e56bc3b-0404-4813-b717-35741958613b.png">

**Comment by nmannheimer** [comment]
Script functions are not supported in Prep, you need to use a special Script node on your flow.

This is currently only supported in on-premise Tableau Prep.
________________________________
From: Anulekha Boddu ***@***.***>
Sent: Saturday, December 3, 2022 1:26:14 PM
To: tableau/TabPy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tableau/TabPy] SCRIPT_REAL unsupported function (Issue #572)


I'm trying to deploy a python model using tabpy.query. Below is the code i'm using but it keeps throwing this error. Not sure how to fix this. I've tried to add the script directly to tableau desktop but that's also throwing an EOL syntax error. please help, i'm new to this. Thank you very much!

[Screen Shot 2022-12-03 at 1 13 37 AM]<https://user-images.githubusercontent.com/67741733/205462730-5e56bc3b-0404-4813-b717-35741958613b.png>

**Comment by ayyboddu** [comment]
Is it also not supported on Tableau Desktop? How can I go about deploying the model otherwise?

**Comment by nmannheimer** [comment]
It is supported in desktop, hard to say without seeing your error, but at least return should be on the same line as the rest of the code.
________________________________

**Comment by ayyboddu** [comment]
this is the error that i'm getting

<img width="1512" alt="Screen Shot 2022-12-03 at 4 34 40 PM" src="https://user-images.githubusercontent.com/67741733/205463073-844ac3ee-12a6-4d6b-afc6-2e3188c781b7.png">

**Comment by nmannheimer** [comment]
Ah sorry, script functions are not supported in table extensions, you don’t need them. Your data are passed as a dictionary called _arg1 and you can return a full dictionary back.

Your calculation would work in a normal tableau calculation though.
________________________________

**Comment by ayyboddu** [comment]
Oh, okay. Where can i find the syntax/documentation for tableau extensions? I need to use the tabpy.query to deploy my model from jupyter notebook, so I have to use tableau extensions if I'm not mistaken?

**Comment by nmannheimer** [comment]
You can find the docs here: https://help.tableau.com/current/online/en-us/tc_table_extensions.htm

They should also be updated and expanded soon
