### ISSUE TITLE
An error occurred while communicating with the Analytics Extension data source ‘Analytics Extension’

### ISSUE THREAD

**Issue by TamBTX** [tableau/TabPy#573]
**Environment information:**
 - Windows 10 Pro
 - Python version: 3.9
 - TabPy release: 2.5.0
 
**Describe the issue**
I built a dashboard using different functions. I had no problems in my tableu desktop, I connected properly to a host using a notebook on  amazonaws (not local), The issue is when i publish the dashboard to tableau server. When I try to see my workbook i got the message that i put in the screenshot

**To Reproduce**

**Expected behavior**
What i need is to see on tableau server the same dashboard that i have on desktop. I repeat here, i didn´t have issues connecting the extension and with the calculated fields.

**Screenshots**
This is what i see when i try to see my dashboard in the server
![Captura](https://user-images.githubusercontent.com/13418473/205961676-d400bdc0-b857-42ee-9f1e-6d3a3095ba76.PNG)

Thanks in advance

**Comment by lriggs** [comment]
I think that means you haven't configured an analytics extension connection for that particular workbook. After you publish the workbook you can edit it and then setup the connection in the table extension dialog.
https://help.tableau.com/current/server/en-us/ts_table_extensions.htm
