### ISSUE TITLE
TabPy on Heroku Quickstart runs on port 443

### ISSUE THREAD

**Issue by stephenlprice** [tableau/TabPy#574]
**Environment information:**
 - TabPy release: 3.9
 
**Describe the issue**
The Heroku quickstart deployment option for Tabpy is the easiest way to get started however, it is not thoroughly documented and leaves out useful details. One of the items it fails to mention is that this deployment will already support `https` by default and therefore runs on port 443. This can cause confusion to people looking to configure their Tableau products with Tabpy.

**Comment by 0golovatyi** [comment]
http://tabscifi.golovatyi.info/category/heroku/

**Comment by AbdullahHasan42** [comment]
@0golovatyi 
This needs to be included in the deployment steps. I've been troubleshooting this issue for 2 days until now. 

@stephenlprice
Thank you.

**Comment by nmannheimer** [comment]
Fixing with docs update!
