### ISSUE TITLE
Can we use tabpy function even if TABPY_EVALUATE_ENABLE is set to false

### ISSUE THREAD

**Issue by abhishekzgithub** [tableau/TabPy#589]
**Environment information:**
 - OS: [ Linux, Mac] 
 - Python version: [3.9]
 - TabPy release: [latest]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Disable the TABPY_EVALUATE_ENABLE by setting it to false

**Expected behavior**
TABPY_EVALUATE_ENABLE if false, there should be a workaround to access the server's deployed function
**Screenshots**

**Additional context**

**Comment by nmannheimer** [comment]
Yes you can call them, but currently only in Tableau calculated fields using MODEL_EXTENSION_X

https://help.tableau.com/current/pro/desktop/en-us/r_connection_manage.htm#directly-query-external-analytics-models

**Comment by abhishekzgithub** [comment]
Hi @nmannheimer , is there a documentation to check for examples to use and deploy 'MODEL_EXTENSION_X'. I searched but couldn't find anywhere over the internet.

**Comment by nmannheimer** [comment]
Did you follow the link I shared for documentation on how to use the fields in Tableau? In this case, the X stands for one of the 4 calculation types, IE MODEL_EXTENSION_INT for returning an integer type from your model.
