### ISSUE TITLE
2 Different Errors When Calling Deployed Functions

### ISSUE THREAD

**Issue by boonec6** [tableau/TabPy#59]
I'm trying to implement 2 very basic functions, just to get my feet wet and have a basic understanding before diving deeper.  However, I'm running into 2 errors.

First, I created a simple "TitleCase" function using the titlecase Python package, defined as:

```python
import tabpy_client

client = tabpy_client.Client('http://localhost:9004/')

def TitleCase(string):
    from titlecase import titlecase
    return titlecase(string)

client.deploy('TitleCase',TitleCase,'Changes all words to Title Caps, and attempts to be clever about SMALL words like a/an/the in the input.')
```

Then called the function in Tableau with:

> SCRIPT_STR("return tabpy.query('TitleCase',_arg1)['response']",ATTR([ticker]))

Where ticker is a string field.  This gives me the following error:
>An error occurred while communicating with the Predictive Service.
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

Second, I created a "Double" function:
```python
import tabpy_client

client = tabpy_client.Client('http://localhost:9004/')

def double(numb):
    res = numb*2
    return res


client.deploy('Double',double,'Doubles the input number', override=True)
```
Then called it via:
>SCRIPT_REAL("return tabpy.query('Double',_arg1)['response']",SUM([adjustedclose]))

Where [adjustedclose ]is a decimal.  This gave me an error of:
>Unexpected number of results returned by SCRIPT function. Function expected 1 values; 2 values were returned.

I'm sure I've just got a minor syntax error or something, but I've been tinkering for a while and get figure out what I'm doing wrong.  Thanks in advance!

**Comment by BBeran** [comment]
Hi,
You can find a working example of titlecase in our documentation here.
https://github.com/tableau/TabPy/blob/master/TableauConfiguration.md
Tableau passes the data as a list and expects a list back. So often you'll need to use one of tolist or a list comprehension, map function etc.

You can find general examples of this as part of "Getting into Arguments" section of this article
https://community.tableau.com/docs/DOC-10856

I hope this helps.

Bora

**Comment by boonec6** [comment]
I'm able to get the TitleCase function to work when writing the function in the calculation as the example shows, but I'm still not understanding why it errors when I try to call it as a deployed function.  

I tried changing the return of the function to
```python
return map(list, titlecase(string))
```
and
```python
return list(titlecast(string))
```
both neither of those worked either.  And when running the query in the Python console, the original function returned what I expected, but the 2 new attempts each returned a list of individual characters.

**Comment by boonec6** [comment]
I figured it out.  Clearly I need to brush up on my Python basics - I needed to use
```python
return titlecase(string).tolist()
```
which you did mention, I just totally overlooked it. Thanks

**Comment by BBeran** [comment]
I was just about to respond with the working version. I am glad it was resolved.
