### ISSUE TITLE
Feature Request: Ability to whitelist importing of Python modules - REST API evaluate method

### ISSUE THREAD

**Issue by slewt** [tableau/TabPy#61]
This would give the TabPy admin the ability to reduce the potential impact of arbitrary code running on the server.

Possible code set: https://github.com/slewt/TabPy/tree/whitelist_package_import

**Comment by 0golovatyi** [comment]
The module mentioned above is not available anymore. And in general checking scripts for what they import give a false sense of security. IMO we should close this request.

**Comment by slewt** [comment]
agreed.
