### ISSUE TITLE
Feature Request: Provide ability to configure TLS

### ISSUE THREAD

**Issue by slewt** [tableau/TabPy#62]
This would mostly be a pre-cursor to potential authentication/authorization of publishing, but will also be needed by some businesses for security requirements.

Potential patch: https://github.com/slewt/TabPy/tree/TLS

**Comment by BBeran** [comment]
This is really easy to add to TabPy but we need to add support on Tableau desktop and Tableau server first for it to work end to end.

**Comment by slewt** [comment]
We can close this for now.

**Comment by BBeran** [comment]
Thanks for all your contributions on this and other work items you created. We will code review and test it and merge the changes.  Much appreciated.
