### ISSUE TITLE
Feature Request: Ability to remotely publish code

### ISSUE THREAD

**Issue by ghost** [tableau/TabPy#64]
The ability to publish code should include:

* Authentication to the application for publishing method(s)
  * My primary use will be Windows Integrated Authentication or Kerberos with a tie in to AD groups.
  * Should probably ensure modularity so someone can write own code (e.g. could provide a fairly simple username/password module reading from a config file and customers provide their own authentication/authorization module)
* TLS should probably be a requirement for the authentication
* Logging (probably info level) of who published what from where and when
* Hopefully include #61 for published code
  * In practice, this may be a different list than what is allowed for non-authenticated individuals - these publishers will be more trusted

For longer term in large environments, may need to support the ability to only overwrite your own methods or provide different roles with some kind of naming convention (e.g. user or group endpoints will all start with XX). That is not a current requirement, just a consideration point if it affects implementation.

**Comment by slewt** [comment]
I'll be able to provide code for some of these feature requests. I really like the thought of the app, and expect that some of these are table stakes for even to start testing in larger organizations (this ticket) and/or getting into organizations that have governance requirements like PCI, HIPAA, FISMA, etc.

**Comment by kavyapc01** [comment]
"Closed with [#9"](https://github.com/tableau/TabPy/issues/64)

**Comment by kavyapc01** [comment]
"[(https://github.com/tableau/TabPy/issues/64)](url)

**Comment by kavyapc01** [comment]
[(https://github.com/tableau/TabPy/issues/64)](url)
