### ISSUE TITLE
Feature Request: Metrics logging

### ISSUE THREAD

**Issue by slewt** [tableau/TabPy#65]
For me this will be most useful for published code. Would be extraordinarily useful if it could be tied into TabMon which I could use to grab / include OS level stats for correlation.
May be interesting for non-published code - would need to figure out how to get the data to the report developers

Probably best to log to a db - PostgreSQL since already in use by other projects and there is likely already reuse possibilities (TabMon, TabJolt)

Should include 
* endpoint called, 
* endpoint version, 
* start time 
* and duration (or stop time) 

Should possibly revisit TabMon structure for any other integration items

**Comment by 0golovatyi** [comment]
@slewt There were some logging improvements added, specifically call context logging, check https://github.com/tableau/TabPy/releases/tag/v.0.4.1.

**Comment by slewt** [comment]
Thanks, I'll close this request. Looks like most of the items were addressed. Only one I'm not seeing from the docs is the stop time and that is not currently critical for me. It will be a bit before I will have time to evaluate the new release.
