### ISSUE TITLE
Feature Request: Additional elements in logging

### ISSUE THREAD

**Issue by slewt** [tableau/TabPy#69]
When logging interactions where we are storing / executing data (e.g. evaluationplanehandler post method where it logs the script to be executed), we should capture additional items. This could be and probably should be configuration driven as to what log level they happen at. I would expect these to be notice or informational.

* timestamp (preferably UTC)
* source IP
* username, if known
* success/failure

For authenticated functions should also include:
* endpoint updated
* new version

For authentication itself:
* success/failed authentication / authorization

**Comment by nmannheimer** [comment]
Hello @slewt,

Thank you very much for the feedback and suggestions for future TabPy development, these items have been added to our backlog for TabPy!
