### ISSUE TITLE
Tabpy calculated field hits endpoint multiple times.

### ISSUE THREAD

**Issue by mkflagstad** [tableau/TabPy#71]
Hello,
I'm using tabpy to deploy a forecasting model which is working correctly, however there is significant latency because the endpoint is being called multiple times. The workbook needs to forecast multiple metrics, so I have created an endpoint with an appropriately trained model for each metric. 

In the view is a calculated field with logic like if [metric]=x then [x predictions] where [x predictions] are the results of one of the tabpy endpoints and [metric] is a parameter. I noticed that when I change the [metric] parameter, or any change to the view actually, tableau fetches results for all values of [metric]. In addition, when only [x predictions] is in the view, this endpoint is hit twice. The result is that it takes several minutes to create the view.

Any idea what might be going on or how to prevent tableau from making unnecessary calls?

**Comment by Alfredo-63** [comment]
Hi Mary,

Tableau is not short-circuiting expressions (at least when TabPy is involved). This means that Tableau will evaluate all references in a calculated field, even though some intermediate results are not logically required to compute the final value.
Therefore, one answer to your question is actually avoiding multiple calls to the TabPy server:
You created an endpoint for each model, then you choose the model according to the value of a parameter, programming this logic in a Tableau calculated field.
Consider writing a new endpoint that will also receive the model name as an argument. 
Program the model selection logic in python as part of this new endpoint. The idea is to have a single clean call to this new endpoint from Tableau.
Be careful when sending the parameter to the TabPy as an argument, as you will receive a list and not a scalar value. Therefore you will reference the metric in your python code as metric[0].
Hope this helps.

Yours,
Alfredo

**Comment by Alfredo-63** [comment]
One more thing, the reason why you are hitting the endpoint twice when you only keep a single model, is because you probably have a view with a total. 
Tableau will call your endpoint once for the marks in the view, and once per each total or subtotal.

**Comment by BBeran** [comment]
You can find more information on how Tableau calls Python and what could be causing multiple calls here.

https://community.tableau.com/docs/DOC-10856

I recommend you pass the parameters e.g. [metric] to Python as arguments and write the if..then..else in your Python code.  Tableau always runs all options in if..then..else statements for all types of calculations. SCRIPT_ calculations are no exception.

**Comment by mkflagstad** [comment]
Thank you, that makes a lot of sense.
