### ISSUE TITLE
When using Connection.Deploy(), getting "RuntimeError: LoadFailed: 'Load failed: unsupported pickle protocol: 4'" message

### ISSUE THREAD

**Issue by RaghavanB** [tableau/TabPy#73]
Hi,

I am trying to reproduce the BreastCancer Example but am unable to deploy due to the unsupported picke protocol error. I am using Python 3.6.3. Please help.

Thanks,
Raghav

**Comment by BBeran** [comment]
Are you deploying from Python 3.x to Python 2.x?

This error is observed if you created the pickle object with Python 3.x and you're trying to read it from Python 2.x. 

Do you have any idea why you might have 2 different versions of pickle?

I can make a code change that forces using an earlier pickle protocol but newer protocol has better performance and this shouldn't normally happen.

If you'd like to solve this problem in your current setup you can edit tabpy.py where we create the pickle object.

https://github.com/tableau/TabPy/search?utf8=%E2%9C%93&q=cloudpickle.dump&type=

and add an extra argument to dump function 

protocol=2

to force the older protocol.

**Comment by RaghavanB** [comment]
Thanks a lot. I was deploying from Python 3.x and reading from 2.x. I have now ensured that I read from Python 3.x and it worked. Also, thanks for the method to alter the protocol if we need to read from Python 2.x

Thanks,
Raghav

**Comment by Custos123** [comment]
I have the same problem, but I unfortunately do not understand the solution. I installed tabpy with this tutorial: https://community.tableau.com/thread/236479

Now I also get this error. Can you help me fix it? I am using Python 3.x

Thanks

**Comment by Proteusiq** [comment]
The tutorial is sadly out-dated and uses the wrong version/out-dated git-cloned branch of TabPy(See Bora Beran reply on the same tutorial).
