### ISSUE TITLE
Installation Failure if Windows Power Shell BitsTransfer is not allowed by network proxy

### ISSUE THREAD

**Issue by Pauline-LC** [tableau/TabPy#74]
## Issue
Tabpy installation fails with _"Anaconda-Installer.exe not found"_

During Tabpy-Server install by setup.exe provided from Git-Hub: 
If Windows Power Shell BitsTransfer is not allowed by network proxy, Anaconda-Installer.exe will not be download.

In setup.bat following command is issued:
•	64bit
powershell -Command "Import-Module BitsTransfer; Start-BitsTransfer https://protect-us.mimecast.com/s/0JdzBRCl7d9I7?domain=repo.continuum.io $PWD\Anaconda-Installer.exe"
•	32bit
powershell -Command "Import-Module BitsTransfer; Start-BitsTransfer https://protect-us.mimecast.com/s/wXYWBxcA4MRSw?domain=repo.continuum.io $PWD\Anaconda-Installer.exe"
 
it fails with error:
_Start-BitsTransfer : HTTP status 407 : Proxy Certification Required_

## Resolution
Change proxy setting to allow BitsTransfer or, install Anaconda first and install tabpy-server referring  to Manual Installation of following link:

Manual Installation
[https://protect-us.mimecast.com/s/lNV5Bqcxxe7T2?domain=github.com ](https://protect-us.mimecast.com/s/lNV5Bqcxxe7T2?domain=github.com )

## Additional Links
- [https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916 ](https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916 )
- For  the Japanese Community: [https://community.tableau.com/docs/DOC-10160](https://community.tableau.com/docs/DOC-10160)

**Comment by BBeran** [comment]
Moved to Known Issues wiki
