### ISSUE TITLE
Trying to run example notebook - RuntimeError: LoadFailed: u'Load failed: _fill_function() takes exactly 5 arguments (2 given)'

### ISSUE THREAD

**Issue by kristiewirth** [tableau/TabPy#76]
Hi there,

I'm trying to run the example TabPy notebook, downloaded directly from https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916 with no changes made to it.

Everything is working until this last cell:
```
# Publish the SuggestDiagnosis function to TabPy server so it can be used from Tableau
# Using the name DiagnosticsDemo and a short description of what it does
connection.deploy('DiagnosticsDemo',
                  SuggestDiagnosis,
                  'Returns diagnosis suggestion based on ensemble model trained using Wisconsin Breast Cancer dataset',
                 override = True)
```

When I try to run that cell, I get the following error:
`RuntimeError: LoadFailed: u'Load failed: _fill_function() takes exactly 5 arguments (2 given)'`

I am running Python 2 in both my Jupyter notebook and in the terminal for TabPy. In my terminal window with TabPy, I am getting the following error:
`ERROR:__main__:{"path": "/Users/applemacbook/anaconda/envs/Tableau-Python-Server/lib/python2.7/site-packages/tabpy_server/query_objects/DiagnosticsDemo/4", "ERROR": "Unable to load QueryObject", "error": "_fill_function() takes exactly 5 arguments (2 given)"}`

**Comment by nmannheimer** [comment]
Hello @kristiewirth, I'm sorry you're running into this issue. Are you able to deploy other functions using TabPy or does the command fail in all cases. I think the most straightforward step would be to install the latest version of TabPy. If that doesn't fix the issue, would you be able to attach your exact copy of the jupyter notebook you are using here?
