### ISSUE TITLE
Unknown requires Python '>=2.6, <3' but the running Python is 3.5.3

### ISSUE THREAD

**Issue by MR3118** [tableau/TabPy#78]
when i try to use "pip install tabpy-server" to install the tabpy, the error message showed this.
tabpy does not support python-3.x ?

**Comment by BBeran** [comment]
Can you try installing from Github and see if you're seeing the same message?

I see Python 3.5 listed here (from where pip pulls the package)
https://pypi.python.org/pypi/tabpy-server

Categories
Development Status :: 3 - Alpha
Intended Audience :: Developers
**Programming Language :: Python :: 2.7
Programming Language :: Python :: 3.5**
Topic :: Scientific/Engineering
Topic :: Scientific/Engineering :: Information Analysis

And there is no logic in TabPy code itself that limits it to Python 2.x. So not sure why it is complaining.

**Comment by MR3118** [comment]
Thanks for  reply.
    I have found why the error occurred .When i "pip install" the tabpy ,it would automatically install the model “futures-3.2.0”（https://pypi.python.org/pypi/futures），which just for python2.x .its weired, 'cause  python3.x doesn't need it .
    So,it means that i have to install the anconda to avoid the problem ?

**Comment by Sidneypeacock** [comment]
Hi

Sorry to reignite the thread but I am getting the same (similar - Unknown requires Python '>=2.6, <3' but the running Python is 3.6.1) Error.

This is when I am installing from Github as well as via Pip.

Any thoughts or ideas?

Thanks

**Comment by svennd** [comment]
`CellProfiler requires Python '>=2.7, <3' but the running Python is 3.6.5`

smaller then python 3 it is ?

**Comment by pryan1check** [comment]
TabPy requires Python '>=2.7, <3' but the running Python is 3.6.5

smaller then python 3 it is

**Comment by jmurphy61** [comment]
I encountered this issue as well. This would cause problems for anyone trying to install on Python 3.
The solution in the [futures repo](https://github.com/agronholm/pythonfutures) README.

> It does not work on Python 3 due to Python 2 syntax being used in the codebase. Python 3 users should not attempt to install it, since the package is already included in the standard library.
> 
> To conditionally require this library only on Python 2, you can do this in your setup.py:
> 
> ```
> setup(
>     ...
>     extras_require={
>         ':python_version == "2.7"': ['futures']
>     }
> )
> 
> Or, using the newer syntax:
> 
> setup(
>     ...
>     install_requires={
>         'futures; python_version == "2.7"'
>     }
> )
> ```

Should update setup.py on this repo.
