### ISSUE TITLE
Running TabPy as a Background Process Indefinitely 

### ISSUE THREAD

**Issue by contrerasjdj** [tableau/TabPy#80]
I know that opening a command line and running the startup.bat file will allow you to access TabPy via Tableau Desktop, but once you close the command line, the TabPy closes the connection. Is there anyway to have TabPy as a background process, or will the command line window always have to be open in order for desktop to connect? This is on a Windows Server machine.

**Comment by johng42** [comment]
Yes, you can start command line apps in the background.

You can modify the last line of setup.bat to be something like this:
@ python /B tabpy.py --port %port%

The /B switch causes the python executable to run in the background.

Does this help?

**Comment by contrerasjdj** [comment]
I added the /B but the command was not recognized.

**Comment by johng42** [comment]
What did that last line of file become?  Can you post it?
Also, which version of Windows do you have?

**Comment by contrerasjdj** [comment]
The last line was what you suggested: 
@python /B tabpy.py --port %port%

It does not recognize the /B unfortunately. 

I am on a virtual machine, Windows NT 6.2

**Comment by johng42** [comment]
Odd, that should be there.  There are a number of other ways to do this listed here:
https://superuser.com/questions/62525/run-a-batch-file-in-a-completely-hidden-way

**Comment by Proteusiq** [comment]
I found the best way is to run TabPy in a docker container. As long as docker is running your TabPy connection will be live.

**Comment by nmannheimer** [comment]
Since a number of possible solutions have been provided, I'm going to close this issue.
