### ISSUE TITLE
TabPy 'List Index Out Of Range' 

### ISSUE THREAD

**Issue by pragyanbezbo** [tableau/TabPy#81]
Hello,

I am facing a weird issue with Tableau and TabPy.

I have done Union of 5 files - similar columns - and then used filter to do the calculations based on the file selected. 

I am using TabPy to do the calculations like Cp, Cpk etc and it works completely fine (like the image below) - 

<img width="1440" alt="screen shot 2018-02-02 at 12 52 00 pm" src="https://user-images.githubusercontent.com/5626485/35727072-ef37efca-082c-11e8-9095-ec69dec9dcc8.png">

but it works only with 3 of those files. In 2 files, the error that appears is like the image below - 

<img width="1440" alt="screen shot 2018-02-02 at 12 52 41 pm" src="https://user-images.githubusercontent.com/5626485/35722082-e22ab5c2-081a-11e8-9bd3-93328612ec22.png">

I have done Compute Using Cell. 

<img width="612" alt="screen shot 2018-02-02 at 12 52 54 pm" src="https://user-images.githubusercontent.com/5626485/35726992-b9a47fb8-082c-11e8-9868-945225e8a6e4.png">

This is where the issue lies. I have done it so that I could see the calculations based on each month - which gives a better picture of the data. When I Compute Using Table - it works perfectly for all the files but when I change it back to Compute Using Cell - the error reappears.

Here are the calculations for Cpk, Cpl and Cpu respectively - 

<img width="406" alt="screen shot 2018-02-02 at 3 23 16 pm" src="https://user-images.githubusercontent.com/5626485/35727142-1c1c73ee-082d-11e8-8ff2-bdc2762480f2.png">

<img width="569" alt="screen shot 2018-02-02 at 3 23 28 pm" src="https://user-images.githubusercontent.com/5626485/35727145-2385507e-082d-11e8-9668-2606557dc4e6.png">

<img width="574" alt="screen shot 2018-02-02 at 3 23 37 pm" src="https://user-images.githubusercontent.com/5626485/35727148-28cb3134-082d-11e8-9987-829b5817496c.png">
What could be the issue? Am I missing something in here? Looking forward to some suggestion how to solve this.

Regards,
Pragyan Bezbaruah

**Comment by BBeran** [comment]
Each cell appears to have only 1 point. But you're asking for _arg2[2] and _arg1[1]. Python uses 0 based indexing so the only index that has data with a single point is _arg2[0] and _arg1[0]. You are asking for 2 and 1 which doesn't exist hence the out of range error.

**Comment by pragyanbezbo** [comment]
Hey @BBeran that was really silly of me. Thanks a lot.
I just somehow missed that part. 

But why  _arg2[2] was working for the 3 other files and not working just for those 2 files?
