### ISSUE TITLE
Tabpy Predictive Server Error

### ISSUE THREAD

**Issue by ayushvaishya** [tableau/TabPy#82]
On trying the following RandomForestRegression to predict values , I'm getting an error in tableau . While the same script is easily working in spyder interface.

SCRIPT_REAL(
'import pandas as pd
import numpy as np
s = _arg1
f = _arg2
dates = pd.DataFrame(s)
SALES= pd.DataFrame(f)
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 300)
regressor.fit(dates,SALES)
y_pred = regressor.predict(dates)
',ATTR([Order Date]),ATTR([Sales]))

 
The error I get is : ValueError : Input contains NaN, infinity or a value too large for dtype('float32').

 

The code is working properly in spyder. Any suggestions will help.

**Comment by tmartintableau** [comment]
Based on the error message, I'm thinking the "date" Data Frame has nulls in it. You can handle them using one of the methods outlined here: https://datascience.stackexchange.com/questions/11928/valueerror-input-contains-nan-infinity-or-a-value-too-large-for-dtypefloat32.

**Comment by nmannheimer** [comment]
Hey @ayushvaishya just wanted to follow up on this and see if your issue was resolved by these comments?
