### ISSUE TITLE
Unable to Publish SuggestDiagnosis function to TabPy server

### ISSUE THREAD

**Issue by mkrish29** [tableau/TabPy#85]
Hi Beran

I'm unable to publish the SuggestDiagnosis function to TabPy server(Brest Cancer Example Jupyter Notebook)  and facing the below issues

**1)**An endpoint with that name ('DiagnosticsDemo') already exists. Use 'override = True' to force update an existing endpoint.

when using override='True' i'm facing the below issue 

**2)**RuntimeError: LoadFailed: 'Load failed: code() takes at most 14 arguments (15 given)
Also tried the below comment from you in the  issue #44 

"It looks like the model wasn't successfully trained. When model training fails, you can still publish a function to TabPy server but the error will surface when you try to run the model.

On some Windows machines, this could happen due to a bug in Python when you try to run model fitting by using all the CPU cores you have. This is controlled by the "n_jobs=-1" setting in the Jupyter workbook. I suspect this might be the issue.

The solution is to set n_jobs=1 which will run the training using only a single core. After making this, if you add the argument override=True to your deploy function then run the entire Jupyter workbook (Cell > Run All) I suspect it might fix it."

even when updating the n_jobs=1 i'm continuing to face the same issue.

![image](https://user-images.githubusercontent.com/36915401/36831287-293b6398-1d4d-11e8-8d3e-db02fe4f2832.png)

![image](https://user-images.githubusercontent.com/36915401/36831297-37fec410-1d4d-11e8-8ed4-d49b29274211.png)

![image](https://user-images.githubusercontent.com/36915401/36831323-4f4a94be-1d4d-11e8-848d-a315a95b709f.png)

**Comment by mkrish29** [comment]
Referencing issue #35 i ran the jupyter notebook in Python 2.x and was able to successfully publish the function to Tabpy server.
Still facing the below issue
![image](https://user-images.githubusercontent.com/36915401/36900502-8a7d6622-1e49-11e8-9632-09cb8bd215c8.png)

**Comment by nmannheimer** [comment]
Hi @mkrish29,

Are you able to publish other functions besides the one in the notebook to your TabPy instance? Are you running Python 3.x locally in addition to 2.x?

Sincerely,
Nathan
