### ISSUE TITLE
Parallel/Async Requests

### ISSUE THREAD

**Issue by afreeland** [tableau/TabPy#87]
I am new to using TabPy and have been reading through the documentation but was curious about performance for larger datasets...and the throughput of network request.  

Currently I am using a docker image of [TabPy](https://hub.docker.com/r/emhemh/tabpy/) and was thinking about pushing it out through a [Kubernetes](https://kubernetes.io/) deployment so we could have a load balanced environment and several TabPy containers.  Is there a way to instruct/configure Tableau to crank up the throughput of requests.  I am essentially wanting to be able to process lots of rows through python as fast as possible...any pointers here would be greatly appreciated.

**Comment by johng42** [comment]
There is not much Tableau can do about the throughput of your network - that is hardware limited, if I understand your question correctly.

But you can possibly minimize the number of rows you send via aggregation.  There is a bit of information about this here: https://community.tableau.com/docs/DOC-5313.  That article covers the Rserve functionality, but for this consideration it is the same as Tabpy.

Does this help get you started?

**Comment by afreeland** [comment]
So I started capturing time to understand when and how things were being executed on the TabPy Server.


```
import time
from datetime import datetime

# Before logic begins
millis = int(round(time.time() * 1000))
print('start time: ' + str(millis) )
print(datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])

# ... Logic Here ... web requests, etc.,

# Logic complete and getting ready to return data
print(datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])

```


When I look at my console output I see the following
```
start time: 1520366595122
2018-03-06 20:03:15.121
2018-03-06 20:03:15.125

start time: 1520366595128
2018-03-06 20:03:15.128
2018-03-06 20:03:15.131

start time: 1520366595134
2018-03-06 20:03:15.134
2018-03-06 20:03:15.140

start time: 1520366595143
2018-03-06 20:03:15.143
2018-03-06 20:03:15.146

```
To me this looks like its does the remote execution and waits for a return before the next remote execution is called.  I would like to see the remote execs go out completely independently...

I would think, if they were all async, that it could send out multiple connections at once and look `more` like the following.

```
2018-03-06 20:03:15.121
2018-03-06 20:03:15.125

2018-03-06 20:03:15.121
2018-03-06 20:03:15.126

2018-03-06 20:03:15.121
2018-03-06 20:03:15.127

2018-03-06 20:03:15.122
2018-03-06 20:03:15.127

```

The hardware setup we have implemented can handle this type of load...but if Tableau is not sending it out in an async manner then it doesn't help us process rows any faster.  If I missed something in the article please let me know and I will revisit.  There was a lot of good information in that article though =)

**Comment by johng42** [comment]
Correct - the requests are serial.  Feel free/encouraged to make a request for async calls on our forums: https://community.tableau.com/community/forum

**Comment by afreeland** [comment]
This is more of a Tableau issue as opposed to this repo so I am going to close this issue.  Thanks @johng42 for your help with my questions =)
