### ISSUE TITLE
ResponseError: (400) Endpoint name can only contain: a-z..

### ISSUE THREAD

**Issue by princesden** [tableau/TabPy#88]
Running the last line in the demo notebook gives the error show.  Python version 3.6.0 

     connection.deploy('DiagnosticsDemo',SuggestDiagnosis,'Returns diagnosis suggestion based on 
                                     ensemble model trained using Wisconsin Breast Cancer dataset')

ResponseError: (400) Endpoint name can only contain: a-z, A-Z, 0-9,underscore, hyphens and spaces. {}

**Comment by nmannheimer** [comment]
Hi @princesden, sorry you're having difficulties with this!

Is possible for you to send the exact notebook you're using? One troubleshooting alternative may be tor try a different name.

**Comment by nmannheimer** [comment]
Hi @princesden,

Please let me know if you are continuing to experience this issue, otherwise I'll go ahead and close the tab. Thanks!
