### ISSUE TITLE
When login in to TABPY there comes and error 

### ISSUE THREAD

**Issue by TheTerminator2** [tableau/TabPy#9]
Hey

Have installed TABPY perfectly on my windows 10 computer. But when trying to login to TABPY from TABLEAU it writes the following error message

![image](https://cloud.githubusercontent.com/assets/9933849/20449482/f34e1330-ade9-11e6-9697-bd0b9de5bd30.png)

I have been using the Rserver before on this computer, but it havn't been turn on for a long time, so its weird why Tableau still refers to it.

**Comment by BBeran** [comment]
Hi,
Did you make sure it is configured to point to the correct port? Help->Settings and Performance->Manage External Service Connection..

It could be pointing to the long port. Or Windows could be blocking the port, if so you will need to change your settings to allow it.

Thanks,

Bora

**Comment by TheTerminator2** [comment]
Hi BBeran

Thanks for your comments, I tried to have windows firewall open the port and afterwards restarted the computer. TABPY works now. 

Thanks
Henrik

**Comment by BBeran** [comment]
Hi Henrik,
I am glad you were able to get it to work.

Thanks,

Bora
