### ISSUE TITLE
TabPY in AWS

### ISSUE THREAD

**Issue by pmaloney71** [tableau/TabPy#97]
Hi Folks,

Is it possible to run TabPY on an external server instead of running it locally on the same machine as Tableau Desktop?  What I'd like to do is test the feasibility of running TabPy on a linux server in AWS and then use Tableau Desktop to connect to it's IP address and port.  Here's where I am so far...

I have TabPy running on a Linux server in AWS listening on port 9004. I have configured the AWS security group to allow access to that port.  IPTABLES is also setup correctly.  I've tried to use Tableau to connect to the IP Address/port via the 'Manage Remote Connections' but it's not working. Do I need to make a configuration change on TabPy to accomadate a remote connection?  If so, what are the steps to do this?

Thanks!

**Comment by johng42** [comment]
What error are you getting?

And yes, this is supported.  One of my test configurations has tabpy server running on an Ubuntu machine and I use that to test from a Windows desktop install of Tableau.

**Comment by pmaloney71** [comment]
Hello,

Thanks for the quick response!  I’m getting a timeout and have attached a couple of screenshots.  I have the AWS ec2 instance configured to allow a number of inbound/outbound ports including 9004 so I’m not quite sure what’s going on.

When I start the service from the terminal on AWS, it’s listening on 0.0.0.0 port 9004.   Should it be listening on the actual IP address instead?

Thanks for looking into this.

**Comment by johng42** [comment]
The server should be listening on port 9004.  The ip address the UI shows should be 0.0.0.0

The client needs to point to that server, though.  In the External Service Connection dialog, what have you entered for the Server Name and port?  And can you ping your AWS server from the command line?

**Comment by pmaloney71** [comment]
In the Tableau external service dialog, I have entered the IP address of the AWS Linux server and using port 9004.

I can communicate with the AWS server using other ports but not 9004.  Are there other ports that need to be opened?

**Comment by pmaloney71** [comment]
Yes, 6311 is open.

**Comment by pmaloney71** [comment]
I figured it out, I had the wrong security group applied to the instance.   Thanks again for your help!
