### ISSUE TITLE
cannot import calinski_harabaz_score

### ISSUE THREAD

**Issue by panag** [tableau/TabPy#98]
Hi,

I am using tabpy to do interactive clustering on tableau and then calculate the silhouette and the calinski harabaz scores of a cluster using sklearn.metrics.
Silhouette score works fine however the calinski_harabaz_score function cannot be imported using tabpy (I can import it in any python IDE so it exists in conda installation)

Any idea?

SCRIPT_REAL("
import numpy as np
from sklearn.cluster import KMeans 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import calinski_harabaz_score 
x=np.column_stack([_arg1, _arg2,_arg3,_arg4])
sc=StandardScaler()
df=sc.fit_transform(x)

Kmeans=KMeans(n_clusters=max(_arg5))
r=Kmeans.fit_predict(df)
calinski_harabaz_avg=calinski_harabaz_score(df, r) 

return calinski_harabaz_avg.tolist()

", SUM([Petal.Length]), SUM([Petal.Width]), 
SUM([Sepal.Length]),SUM([Sepal.Width]), [n clusters]
)

**Comment by 0golovatyi** [comment]
@panag What error message do you see?

**Comment by panag** [comment]
@0golovatyi

The error message was "cannot import name calinski_harabaz_score"

The reason was that I followed some old tabpy installation instructions https://community.tableau.com/thread/236479

As a result a new python framework was created that had a really old scikit learn version installed.

I have updated the sklearn package and now works fine.

However I haven't managed to install tabpy using conda install to an existing python environment. The installation seems to complete without errors but when I try to run the relevant startup.bat, it crashes. Is this a known error?

Thanks

**Comment by nmannheimer** [comment]
Hi @panag,

The startup.bat file is for the moment specifically designed to operate on the assumption that TabPy was installed using Anaconda. Try running startup.py to start the server without it. You can do this from the command line with <python startup.py> assuming python has been added to your system path. 

Since the original issue with the out of date sklearn version has been resolved, I'm going to close this tab for now.

**Comment by ningmenghongcha** [comment]
try
`from sklearn.metrics import calinski_harabasz_score`
